### ISSUE TITLE
sngrep load 100% cpu . and loss capture

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#103]
Sngrep load 1% cpu for per dialog .

final cpu 100% then start loss captrue new dialog

**Comment by Kaian** [comment]
Are you using the last commit? I changed the way rtp packers are parsed may be the reason.

I will test a live capture asap. Thanks for reporting!

**Comment by Kaian** [comment]
I've tried to test this but was unable to reproduce.

Can you try the latest commit to check if CPU cosumption improves?

Thanks @michael2009 !!

**Comment by Kaian** [comment]
After some testing in a heavy load server, I was able to reproduce this problem.
I've also tested with 1.2.0 version and has the same problem, so It's not a recent problem.

I think I will leave memory and cpu usage changes for the next release, so I will consider this a required enhancement.

Thanks!

**Comment by michael2009** [comment]
yes . i  had confirm issue with sip replay
1. if replay SIP without rtp traffic and capture with SNGREP then nerver issue 
2. if replay SIP with rtp traffic and capture with SNGREP then 2% cpu  increase with per calls 

full replay step : 

tcpdump -i any -w test.pcap udp

tcprewrite --dlt=enet --enet-smac=00:90:8f:15:01:04 --enet-dmac=00:E9:24:13:13:C8 -i test.pcap -o replay.pcap

bittwist -i eth2 replay.pcap -l 1

**Comment by Kaian** [comment]
Yes, the problem is related with the process of searching the call owner of every RTP packet. We receive a lot of RTP packets and we search the call in the list who belongs to. If we have lots of calls the process becomes slower and slower. 

But It seems this is nothing new, it happens since a long time. I'll try to improve this logics for the next release.

**Comment by michael2009** [comment]
then best add one parameter to full disable RTP fuction .

**Comment by Kaian** [comment]
I like the setting option to totally disable RTP, for those who are only interested in SIP. I will try to implement that for 1.3.0 :))

**Comment by Kaian** [comment]
Also, remember to **use bpf filters** from command line if you have lots of traffic. Otherwise you're requesting sngrep to parse ALL packets of the system (even your ssh connection...)

`sngrep port x` or `sngrep portrange x-y` most probably will avoid capturing rtp (and many other useless packets).

**Comment by Kaian** [comment]
I think the best approach for not parsing RTP (and using lot of CPU for parsing its contents) is to properly use command line filters to avoid capturing it at all: **port** filter will apply to both src and dst port, so I think that should be the way to go. 

`sngrep port 5060 or port 5061`

If anything thinks this is not enough feel free to reopen this issue.

**Comment by michael2009** [comment]
ok . but can work with port range ?

**Comment by Kaian** [comment]
Yes, it already works with port ranges.
BPF Filtering is **the most powerful filtering** of all libpcap tools (sngrep, ngrep, tcpdump, sipgrep, and so on). 

`sngrep portrange 5000-6000`  # Capture everything between these ports

Or you can skip local RTP ports if you know them
`sngrep portange not 13000-190000` # Skip packets with src or dst port between these ports

You can also filter packet  using the hex you mentioned

`sngrep 'udp[8] & 0xc0' != 0x80`   # Skip packets that have RTP header


And of course you can combine multiple of them whith **and** and **or** words.

**Comment by michael2009** [comment]
sngrep 'udp[8] & 0xc0' != 0x80 -I issue.pcap 

then issue for loss sip flow .
