### ISSUE TITLE
TLS not decrypted if connection is TLS 1.1 or 1.2

### ISSUE THREAD

**Issue by Kaian** [irontec/sngrep#104]
Reported in #64 by @michael2009 and confirmed

**Comment by kevinlong206** [comment]
Thanks Kaian! The gnutls decrypt is working on my system for aes-256 TLS connections.

**Comment by michael2009** [comment]
Yes , work with gnutls . but when add for openssl ?

**Comment by Kaian** [comment]
Hi @michael2009 

Not sure if it will be included in 1.3.0 but it will be fixed soon. As explained in #101 I personally won't encourage using weak SSL ciphers that can be decrypted just with the private key. 

Anyway, I think maintaining two implementations of SSL decrypt is not good and we'll be dropping one of them for 2.x versions. Most probably we will drop OpenSSL and use gnuTLS because that way we keep sngrep only with GPLv3 license and, what is most important, we're basing our decrypting process on wireshark code, which is more than awesome, and uses gnuTLS. The initial code was based on ssldump (uses openssl) but it seems discontinued. We won't reinvent the wheel for this, we prefer standing on the shoulders of giants.

Thanks both of you for the testing!

**Comment by michael2009** [comment]
Hi Kaian

Maybe bad idea with GNUTLS + Centos6/7, becuse no libgnutls-openssl with default yum or rpm package. if run sngrep + gnutls then must reinstall gnutls , libnettle , libgcrypt .

**Comment by Kaian** [comment]
Hi!

Thanks for pointing that! If we do that move, we will remove the need of gnutls-openssl. It includes some compatibility wrappers for migrating from OpenSSL to gnuTLS easily, which came in handy when we added gnuTLS support long time ago. If we take the gnuTLS route the only dependencies in CentOS will be gnutls-devel and libgcrypt-devel which should be in the default repositories.

**Comment by michael2009** [comment]
HI Kaiwan,
Did try failed with Centos6 build --with-gnutls because depend gnutls-openssl .
When can remove remove gnutls-openssl?

**Comment by Kaian** [comment]
Hi michael!

If we make that change (only use gnutls) it will be for the next mayor release (2.0.0) which can be released next month, next year or never because depends on the free time the other projects we are working on leave us everyday.

Updating Openssl will be sooner than that. I'll try to fix it this week as soon as I have some spare time and close 1.3.0 with that changes.

Stay tuned!

-------- Mensaje original --------
De: michael2009 <notifications@github.com> 
Fecha: 14/03/2016  3:58  (GMT+01:00) 
Para: irontec/sngrep <sngrep@noreply.github.com> 
Cc: Kaian <Kaian@irontec.com> 
Asunto: Re: [sngrep] TLS not decrypted if connection is TLS 1.1 or 1.2 (#104) 
 
HI Kaiwan,
Did try failed with Centos6 build --with-gnutls because depend gnutls-openssl .
When can remove remove gnutls-openssl?

**Comment by Kaian** [comment]
Hi michael!

If you have time, give it a try to the last `master` commit. I have ported the changed from gnutls to openssl code and seems to work fine with the pcap provided for this issue.

Thanks in advance

**Comment by michael2009** [comment]
Good . tls work with openssl now

**Comment by Kaian** [comment]
Thanks for the feedback!

**Comment by jungle-boogie** [comment]
Are there plans not to build with openssl? How would that affect, if at all, libressl?
I remember that we can link to it with c flag things, so would that still be a possibility? 

If not, I would respectfully disagree with making this work only with gnuTLS. Perhaps you could try making it work only with libressl instead.

**Comment by Kaian** [comment]
Hi @jungle-boogie !

If we go the gnuTLS only path, sngrep won't be compatible with openssl nor libressl (as they share the same functions api afaik). More than a license freedom, the real problem is that, as mentioned in a note before in this issue, the decrypting code uses wireshark as basecode to test if we're doing it properly (which uses gnuTLS). We're far for experts in SSL/TLS so having a tool already doing the work helps a lot while coding and testing. If there's a tool with SSL decryption implemented with libreSSL, we could consider it. I don't think implementing the same thing with two totally different libraries is the way to go. 

Of course, we're open to all kind of feedback in this regard. After all we don't use TLS as much as we should.

**Comment by jungle-boogie** [comment]
Hi @Kaian!

Thanks for the reply and the recent updates to sngrep!

My opinion is just in limiting the number of dependencies needed to run sngrep, and gnuTLS isn't necessarily a dependency because you don't necessarily need TLS support.

Is it possibly to statically link gnuTLS as some way to resolve this issue?

**Comment by kevinlong206** [comment]
I may be having the same issue, I built the gnutls version OK on Debian Jessie , but my main target system is FreePBX distro which is based on (?) CentOS (6.5 I think) .. can’t seem to find a good way to get the gnutls-openssl library/dev files ..  which seems to be a dependency? 


checking for gnutls_init in -lgnutls... yes
checking for SSL_new in -lgnutls-openssl... no
configure: error:  You need to have gnutls installed to compile sngrep

**Comment by kevinlong206** [comment]
but I do have gnutls files, just not gnutls-openssl 

[root@pbx-de-ext sngrep]# rpm -qa | grep gnutls

gnutls-2.8.5-14.el6_5.i686
gnutls-2.8.5-14.el6_5.x86_64
gnutls-devel-2.8.5-14.el6_5.i686
gnutls-utils-2.8.5-14.el6_5.x86_64
gnutls-devel-2.8.5-14.el6_5.x86_64

**Comment by Kaian** [comment]
@kevinlong206 Right now, sngrep 1.x requires gnutls-openssl which makes OpenSSL the only choice for CentOS systems. BUT if we decice to remove openssl support, gnutls-openssl won't be required for compiling with TLS support, just gnutls-devel and libgcrypt-devel (which are available even on CentOS 5). 

Don't worry, there's still plenty of time for discussion to choose between OpenSSL (or LibreSSL) and gnuTLS. I just mentioned that most propably is not a good idea to maintain two source codes for decrypting. Any fix or enhacement (maybe more ciphers) will have to be done twice!

Anyway, sngrep 2.x is not even being development in our minds but as mentioned, all kind of feedback is appreciated.

@jungle-boogie Yep, most probably it could be statically linked without problem, and maybe we can create two packets, one thas simple pulls gnutls and libgcrypto and ones that doesn't require that. But linking statically is not recomended, in case of security fault, you depend on me to create a new linked package version with the ssl library fix. Not really fun of that.

What I am discovering is that CentOS users are not friends of gnutls and libgcrypt :laughing:  
For the next release (1.4.x), most probably we will remove the gnutls-openssl requirement so CentOS users can choose between OpenSSL/LibreSSL and gnuTLS. For 2.x.... thats a more distant future.

Thanks for the feedback!

**Comment by jungle-boogie** [comment]
Hi @Kaian,

> . But linking statically is not recomended, in case of security fault, you depend on me to create a new linked package version with the ssl library fix.

Yep, that's something to consider for your development and it makes sense if that's not what you want to do.
