### ISSUE TITLE
Call state incorrect with CANCEL

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#105]
Call state incorrect with CANCEL , 487

Call State = IN CALL

**Comment by michael2009** [comment]
I had sent mail with incall.pcap

**Comment by Kaian** [comment]
Hi @michael2009 

The problem is more related with the 200 OK before the CANCEL.
When the 200 OK is received, the call enters IN CALL, and CANCEL is not handled for calls with IN CALL state. In fact, we should wait for the ACK of the 200 OK to enter IN CALL state.

Thanks for the pcap!

**Comment by Kaian** [comment]
We should now enter IN CALL state when we receive the ACK of the INVITE instead of 200 OK.
If you can, confirm this is working as expected.

Thanks!

**Comment by davemidd** [comment]
I'm afraid commit #007bfba stops my calls from entering the IN CALL state; they stay at CALL SETUP.
If I revert to commit #e9de1c9 the same call does enter IN CALL ok.
What can I upload to help fix this?

**Comment by Kaian** [comment]
Hi @davemidd 

What messages have your dialog? INVITE -> 1XX -> ... -> ACK ?

Maybe we're failing to find the INVITE's ACK that we now require to consider the call established. A pcap example by email is always helpful :))

Thanks for reporting!

**Comment by davemidd** [comment]
Hi @Kaian 
I've got UAC -> SBC -> UAS so it's a slightly more complex scenario.
I have found that when the UAC and UAS are SIPp instances, the call does show as IN CALL.
It's only with 'real' agents that the problem occurs. I can only see 2 main differences in the scenarios:
- For the 'real' agents, the INVITE is with authentication and so is challenged (401) whereas with my SIPp agents, there is no authentication.
- For the 'real' agents, the UAS does re-transmit the 200 before getting the ACK.
I'll mail you some info.
Thanks for an amazing tool :)

**Comment by Kaian** [comment]
I think I found it. We were not properly storing the INVITE's Cseq after 401, so the received ack was not considered the call establishment confirmation.

If you have time, give it a try to the latest commit to check if it solves the problem :)

Thanks for reporting!

**Comment by davemidd** [comment]
Perfect - that's fixed it.
Thanks for the quick response :)

**Comment by Kaian** [comment]
Thanks to you for reporting!
