### ISSUE TITLE
Incorrect call state with version 1.3.0

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#109]
I have calls with marked as call setup but captured is a full flow
```
INV ---->
<--- 100
<--- 180
<--- 200
ACK---->
<----BYE
200----->
```
this call is the first call leg of a b2bua seperated call flow the other leg is marked correct.

**Comment by Kaian** [comment]
Hi dunst!

Could you please check with a compiled version from `master`?
Could it be duplicate from #105 ?

Thanks in advance!!

**Comment by dunst0** [comment]
yep, it is fixed with master. Thanks a lot :relieved:

**Comment by Kaian** [comment]
You welcome :)
