### ISSUE TITLE
dead repos

### ISSUE THREAD

**Issue by dragonfly-net** [irontec/sngrep#110]
https://github.com/irontec/sngrep/wiki/Installing-Binaries#centos--fedora--rhel

http://packages.irontec.com/dist/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

**Comment by Kaian** [comment]
Hi @dragonfly-net !!

It may be possible that repositories are broken, we have made some changes recently, but I think I made a couple of test to check if they were working.

Anyway, according to the wiki page you linked: ```Replace dist with centos, fedora or rhel.```

Could you please give it a try changing the word `dist` in the url?

Thanks for reporting!

**Comment by dragonfly-net** [comment]
Sorry, my fault, I was inattentive.

**Comment by Kaian** [comment]
No problem! :+1:
