### ISSUE TITLE
sngrep loss flow with SIP tcp acked unseen segment packet

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#113]
sngrep loss flow with SIP tcp acked unseen segment packet

please check mail with tcp.pcap

**Comment by Kaian** [comment]
Hi michael,

I have checked the pcap you send me and comparing the messages with wireshark I don't find the lost flow.
Can you help me to identify where the problem is? 

![sngrep-113](https://cloud.githubusercontent.com/assets/800069/14956192/b410da58-107e-11e6-952b-905b46a13073.png)

Thanks!

**Comment by michael2009** [comment]
No bye msg 
------------------ Original ------------------

**Comment by Kaian** [comment]
In the second dialog (yellow one)? 

Well.. there are no bye message in the PCAP file for that dialog.
Neither sngrep nor other capture tool will ever print a packet it has not captured.... :thought_balloon:

**Comment by michael2009** [comment]
you can check second one pcap file .  lossTCP.pap
