### ISSUE TITLE
sngrep crash with TLS

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#117]
./sngrep -I 1.pcap -k 1.key 
had sent mail to you .

**Comment by michael2009** [comment]
#0  0x00007ffff78853da in EVP_Cipher () from /lib64/libcrypto.so.10
#1  0x0000000000407c5a in tls_process_record_data (conn=conn@entry=0x7fffe8001d40, fragment=0x7fffe8032f75 "\372\a@\220%\202\352\215\327'\372*\351k<\347\365\001x`.", <incomplete sequence \365>,
    len=len@entry=8970, out=out@entry=0x7ffff4a9bce8, outl=outl@entry=0x7ffff4a9bce4) at capture_openssl.c:566
#2  0x0000000000408138 in tls_process_record (conn=0x7fffe8001d40,
    payload=payload@entry=0x7fffe8032f70 "\027\224\060#\n\372\a@\220%\202\352\215\327'\372*\351k<\347\365\001x`.", <incomplete sequence \365>, len=len@entry=116, out=out@entry=0x7ffff4a9bce8,
    outl=outl@entry=0x7ffff4a9bce4) at capture_openssl.c:374
#3  0x0000000000408281 in tls_process_segment (packet=packet@entry=0x7fffe80008c0, tcp=tcp@entry=0x7ffff4a9bd64) at capture_openssl.c:315
#4  0x0000000000406336 in parse_packet (info=<optimized out>, header=<optimized out>, packet=<optimized out>) at capture.c:305
#5  0x00007ffff6896e59 in pcap_offline_read () from /lib64/libpcap.so.1
#6  0x00007ffff688816f in pcap_loop () from /lib64/libpcap.so.1
#7  0x0000000000404f1a in capture_thread (info=<optimized out>) at capture.c:771
#8  0x00007ffff6662df5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffff63901ad in clone () from /lib64/libc.so.6

**Comment by Kaian** [comment]
Hi @michael2009 !

Thanks for the test file to debug this crash. It helps as always :+1: 

The problem in this case was that sngrep was trying to decode a SSL connection before parsing the SSL handshake messages, so not all required data was available for the process.

The crash has been fixed, but sadly the information in the pcap won't be printed. That connections use TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 that can not be decrypted with just the private key.

Thanks again for taking your time to report so many bugs!

**Comment by michael2009** [comment]
That's sngrep with TLS key . but crashed when ssh login to ippbx server .
