### ISSUE TITLE
Does SNGREP supports Centos 4?

### ISSUE THREAD

**Issue by jafri92** [irontec/sngrep#119]
I am trying to install sngrep on my centos 4 servers but unable to do that, it seems that sngrep is only supported for centos 5+ versions. I have to mirror my SIP traffic to a Homer server.

Any help in this regard would be highly appreciated. Thank you

**Comment by Kaian** [comment]
Hi @jafri92 

There are no binary packages for Centos4 but you can still compile, copy binaries or create your own ones. Source code seems to compile and work fine.

I have tested in a CentOS4.8 image, just [downloading the required packages](https://github.com/irontec/sngrep/wiki/Building#centosfedora) and [the latest tar.gz](https://github.com/irontec/sngrep/releases):

```
[root@dbd3ba2f1aa3 ~]# lsb_release -a
LSB Version:	:core-3.0-amd64:core-3.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 4.8 (Final)
Release:	4.8
Codename:	Final
[root@dbd3ba2f1aa3 ~]# sngrep -V
sngrep - 1.3.1
Copyright (C) 2013-2016 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ivan Alonso [aka Kaian]
```

**Comment by jafri92** [comment]
Hi @Kaian , 

Its working now, Thank you so much for your help. :smile:
