### ISSUE TITLE
Unable to send the packets to HOMER

### ISSUE THREAD

**Issue by saigauravmehra91** [irontec/sngrep#120]
i m useing this command 
sngrep portrange 5060-5061 -k ./privkey.pem -H udp:10.10.10.10:9060 --no-interface -q

and i can't see any packets not sending not receiving both side 
by this 
 
ngrep -W byline -d any portrange 9060
noresult

Plz help me

**Comment by Kaian** [comment]
Hi @saigauravmehra91 

If you remove the `--no-interface` option, do you see the dialog counter increasing?
You can also test if it's sending data properly by using an input file (with `-I file.pcap` option).

If your HOMER has a password, you must also configure your ~/.sngreprc file to include it
`echo set epp.send.pass yourpassord >> ~/.sngreprc`

Also, if you plan to keep sngrep running for a long time take into account that it never free the used memory (there is a pending enhancement to rotate stored data) so it may end eating all your system's memory (or reach a capture limit and stop capturing).

**Comment by saigauravmehra91** [comment]
i can see the  dialog counter increasing when i run 
sngrep portrange 5060-5061 -k ./privkey.pem -H udp:10.10.10.10:9060  -q

but still there is no packet to sending HOMER

**Comment by Kaian** [comment]
Can you please provide the output of `sngrep --version` ?

Is the line ` * Compiled with EEP/HEP support.` present? 

Thanks!

**Comment by saigauravmehra91** [comment]
**output of sngrep --version**
sngrep - 1.3.1
Copyright (C) 2013-2016 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ivan Alonso [aka Kaian]

**Comment by Kaian** [comment]
Is that sngrep compiled by you or installed by packages?

I assume the first one, because I think binary packages should have HEP enabled.
In that case,  configure the sources using:
```
make clean
./bootstrap.sh
./configure --enable-eep --enable-openssl
make
make install (as root)
```

I will remove those command line options (-k, -H, -L, ..) for the next release if corresponding compiler options has not been enabled (OpenSSL/GnuTLS and HEP support) during configure time.

**Comment by saigauravmehra91** [comment]
i have done this process
make clean
./bootstrap.sh
./configure --enable-eep --enable-openssl
make
make install (as root)


it showa one error
configure: WARNING: unrecognized options: --enable-openssl

**Comment by Kaian** [comment]
Sorry, my bad!

Options that require external dependencies have `with` prefix.

Try `--with-openssl`

**Comment by saigauravmehra91** [comment]
now when i run this it show 
[root@cloud2 ~]# sngrep portrange 5060-5061 -k ./privkey.pem -H udp:10.0.0.1:9060 --no-interface -q
./privkey.pem does not contain a valid RSA private key.
[root@cloud2 ~]#

**Comment by saigauravmehra91** [comment]
is it possible to send RTP info to HOMER ??

**Comment by Kaian** [comment]
Hi!

Ensure the file contains only the private key (with the tipical headers BEGIN PRIVATE...). 

If you want to decrypt TLS take into account sngrep only supports two ciphers right now (#59) and you must capture initial tcp connection.

For the RTP:  nope. Not plans to implement it right now (#118)

**Comment by saigauravmehra91** [comment]
that  file contain only Key 
what i want 
i want to show formation In HOMER as i seen in sngrep interface

**Comment by Kaian** [comment]
Could you confirm the not-TLS traffic is reaching HOMER now  capturing in 9060 with ngrep like you mentioned in the first note?

That way we can focus in each problem one by one :)

**Comment by saigauravmehra91** [comment]
[root@cloud2 ~]# ngrep -W byline -d any portrange 9060
interface: any
filter: ( portrange 9060 ) and (ip or ip6)
#
U 192.40.222.82:59116 -> 192.40.222.86:9060
HEP3.;...................................
W>.....
.
..!.............
.........
.(.R.....
.(.S......myhep......INVITE sip:919633308116@192.40.222.83:5080 SIP/2.0.
Record-Route: <sip:192.40.222.82;r2=on;lr=on;ftag=760D4F7A1676C4AB79B4AA813401DDC0;did=ccf1.7df1;nat=yes>.
Record-Route: <sip:192.40.222.82:443;transport=tls;r2=on;lr=on;ftag=760D4F7A1676C4AB79B4AA813401DDC0;did=ccf1.7df1;nat=yes>.
Via: SIP/2.0/UDP 192.40.222.82;branch=z9hG4bK000e.76b6e734b45424817ef07a36c21866e8.0;i=a3b.
Via: SIP/2.0/TLS 10.10.48.14:54942;received=104.200.140.71;branch=z9hG4bKn0kqZ718WnTT5eUK;rport=54942.
Contact: <sip:971553963391@104.200.140.71:54942;transport=tls>.
Max-Forwards: 69.
From: <sip:971553963391@s.talkupon.com:443>;tag=760D4F7A1676C4AB79B4AA813401DDC0.
Allow: OPTIONS, INVITE, ACK, REFER, CANCEL, BYE, NOTIFY, MESSAGE.
Supported: replaces, path.
User-Agent: TalkUpon/4.1.3.
To: <sip:919633308116@s.talkupon.com:443>.
Content-Type: application/sdp.
Call-ID: 13FBF279A6F532E0A5C3E39B017E516C24150BE4.
CSeq: 2 INVITE.
Content-Length: 301.
.
v=0.
o=- 9127591548 46377 IN IP4 192.40.222.82.
s=tpfiqum.
c=IN IP4 192.40.222.82.
t=0 0.
m=audio 28508 RTP/AVP 3 103 101.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:103 opus/48000/2.
a=fmtp:101 0-15.
a=fmtp:103 maxplaybackrate=8000;useinbandfec=1;usedtx=1.
a=ptime:30.
a=sendrecv.
a=nortpproxy:yes.

**Comment by Kaian** [comment]
Hi!!

Seems like a hep packet to me so I assume the issue topic has been fixed. Is correct?

**Comment by saigauravmehra91** [comment]
yes!!
thanks you for your all help!!

**Comment by Kaian** [comment]
Nice! Feel free to open a new issue if you need help with the keyfile error.

TLS decryption is no so easy as it requires servers cipher configuraron and capture before conection establishment so we shoul addres it in another issue :)

Best regards

**Comment by sangeeth-ytel** [comment]
Hi .. i had installed homer with kamailio(4.4),mysql and web .. and on the other freeswitch(1.6) i installed captagent  by following the steps (https://www.powerpbx.org/content/homer-voip-monitoring-install-guide-v1) . i am able to see    hep on freeswitch server and also on the homer server  ( ngrep -W byline -d any portrange 9060) . but unable to see the  QOS reports at homer.

**Comment by Kaian** [comment]
Hi @sangeeth-ytel 

sngrep does not support QOS reports for Homer.

If you are using captagent to send hep, you should open an issue in its project. Sngrep is not related to the developers of Homer.

Regards!!

**Comment by sangeeth-ytel** [comment]
can you help me with this to configure QOS and MOS for each call and send it to homer.

**Comment by sangeeth-ytel** [comment]
my QOS shows me an empty page
![image](https://user-images.githubusercontent.com/15207603/39572826-5fd4f914-4eee-11e8-99b3-85551bdcda7b.png)

and inspect element shows me "no rtcp stats" . not sure if i am missing anything

**Comment by Kaian** [comment]
Hi @sangeeth-ytel 

Could you please open an issue at https://github.com/sipcapture/homer/issues? Maybe they can help you there.

Thanks

**Comment by sangeeth-ytel** [comment]
my QOS report is empty and when i inspect it shows me "no rtcp stats"

![image](https://user-images.githubusercontent.com/15207603/39572968-ea3a147c-4eee-11e8-9440-b9ae6f2ac6d5.png)

**Comment by Kaian** [comment]
I've seen the issue there, so I'm locking this. There is no reason to revive an issue from two years ago.
