### ISSUE TITLE
segmentation fault after a few TLS messages

### ISSUE THREAD

**Issue by kevinlong206** [irontec/sngrep#123]
Hello,

I have compiled sngrep with gnu-tls support, and am running it on Debian 8.  I am sniffing on eth0 , which  is promiscuous mode because I cannot compile sngrep on the actual FreePBX system because of the gnutls-openssl wrapper development files are not available for that OS so it will not compile. 

I am able to see a few TLS messages in sngrep, but it soon segfaults. I would love to provide debug info .. can I help ?

**Comment by Kaian** [comment]
Hi @kevinlong206 

Thanks for reporting the crash :))
There are a couple of things that you can make to help me debug the problem. 

The easiest one is, if you're able to reproduce the crash in a development environment (not with a production private key), you can try to capture with other tool (tcpdump or ngrep) while you using sngrep. Stop the capture when sngrep crashes and try to open it using sngrep. (`sngrep -I crash.pcap -k develop.key`). If sngrep crashes again, then It's a 100% reproducible crash!!!: send me both pcap and key to my mail and I will debug it.

If you're running sngrep on a production environment, dont compromise your key. Install a debugger to provide some process backtrace information and compile sngrep with _--enable-debug_ flag or install the debugging version of sngrep (this will uninstall the _normal_ sngrep).

`apt-get update && apt-get install gdb sngrep-dbg`

Then run sngrep from the debugger with the crashing arguments, for example:

`gdb --ex 'set logging on' --ex run --args sngrep --key *blahblah.key*`

When the crash occurs, the gdb prompt will appear `(gdb) `
Enter following commands:
```
info threads
thread apply all backtrace
thread apply all backtrace full
```

This will generate a file in curren directory *gdb.txt* that can provide some information of what was running in the moment of the crash.

Thanks a lot for your time!
(I should documment this processes int the wiki :sweat_smile:)

**Comment by Kaian** [comment]
I will close this for lack of activity.

TLS has changed a bit, and while still there are some crashes, may or may not be related to this :)

Feel free to reopen if you consider this must be debugged again!
