### ISSUE TITLE
can't open pcap file

### ISSUE THREAD

**Issue by kevinlong206** [irontec/sngrep#124]
Not sure why but it says No such file or directory when I try to open a pcap file:

root@dev1:~# ls -lh packet_capture.pcap 
-rw-r--r-- 1 arrow arrow 448K Jun 16 13:00 packet_capture.pcap

root@dev1:~# sngrep -k halo-pbx.key -IO packet_capture.pcap 
Couldn't open pcap file O: O: No such file or directory
root@dev1:~#

**Comment by davemidd** [comment]
-I is the option to read a pcap file.  You've used -IO.
-O is a different switch to write to a pcap file.

**Comment by kevinlong206** [comment]
Ah yes I see this now. Sorry

**Comment by Kaian** [comment]
You can get a list of available command line flags runing `sngrep --help`.
I try to mantain the wiki updated with [all the flags](https://github.com/irontec/sngrep/wiki#how-to-use).

You can update the wiki if you find an undocumented option :))
