### ISSUE TITLE
Message flow diagram visibility enhancement for time value

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#126]
For calls with a lot of messages and SIP nodes, it is hard to match the time with the message when navigating through the diagram.

I was thinking that it may not be too complex to highlight the corresponding time for the message, in the same way the arrow is highlighted (making it bold/brighter).

**Comment by Kaian** [comment]
Hi @miconda!

Yep, not hard at all, give it a try to the latest commit.

I could also highlight the delta time between messages, but it was no so clear when i was testing (too many bold texts), so I only highlighted the time as you suggested.

Thanks ! :)

**Comment by miconda** [comment]
Hi @Kaian -- looks good, thanks!

The delta time is easy to spot being just above the highlighted time, so I am fine the way it is now.

I am closing this one.
