### ISSUE TITLE
Mac OS X compilation issues when enabling ssl, pcre, unicode, ipv6

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#127]
Trying to compile sngrep after enabling the extra features, like:

```
./configure --enable-unicode --enable-ipv6 --with-openssl --with-pcre
```

It results in errors during the configure, like:

```
checking ncursesw/ncurses.h usability... no
checking ncursesw/ncurses.h presence... no
checking for ncursesw/ncurses.h... no
configure: error:  You need to have ncurses development files installed to compile sngrep.
...
checking pcre.h usability... no
checking pcre.h presence... no
checking for pcre.h... no
configure: error:  You need libpcre development files installed to compile with pcre support.
```

However, pkg-config reports those being installed:

```
pkg-config --cflags --libs ncursesw
-D_DARWIN_C_SOURCE -I/opt/local/include -L/opt/local/lib -lncurses
....
pkg-config --cflags --libs libpcre
-I/opt/local/include -L/opt/local/lib -lpcre
```

This libraries are installed via macports, I tried to provide the paths for include and libs, like:

```
./configure ... --includedir=/opt/local/include --libdir=/opt/local/lib
```

But still no luck.

I am not familiar with building configure scripts, apparently there are some macros for checking for .h files -- wondering if you can provide pointers of how to make it find these libs.

For ssl and ipv6, the configure finishes ok, but when running the make command, the result is:

```
  CC       capture.o
In file included from capture.c:45:
./capture_openssl.h:50:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
...
  CC       sip.o
In file included from sip.c:35:
In file included from ./sip.h:41:
In file included from ./sip_call.h:36:
In file included from ./rtp.h:36:
In file included from ./capture.h:63:
/usr/include/netinet/ip6.h:113:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
                        ^
/usr/include/netinet/ip6.h:113:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
/usr/include/netinet/ip6.h:114:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_dst;        /* destination address */
                        ^
/usr/include/netinet/ip6.h:113:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
/usr/include/netinet/ip6.h:259:29: error: array has incomplete element type 'struct in6_addr'
        struct in6_addr  ip6r0_addr[1]; /* up to 23 addresses */
                                   ^
/usr/include/netinet/ip6.h:113:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
3 errors generated.
```

I am going to investigate more once I get more time, but I thought of opening the issue here to track it and maybe someone else has time to look/fix.

**Comment by Kaian** [comment]
Hi @miconda!

I haven't a MacOSX testing envorinment but we can do some basic checks to discover why autotools don't find that header files.

As far as I remember, you use clang for compiling sngrep, so `clang -E -x c - -v < /dev/null` should print the default include paths it searches:

```
$ clang -E -x c - -v < /dev/null
...
#include <...> search starts here:
 /usr/local/include
 /usr/bin/../lib/clang/3.5.0/include
 /usr/include
End of search list.
....
```

If the files we are looking for are not in the default system path (which seems the case), maybe we can manipulate the compiler flags to include them:

```
$ export CFLAGS=$(pkg-config --cflags ncursesw libpcre openssl)
$ export LDFLAGS=$(pkg-config --libs ncursesw libpcre openssl)
$ ./configure --disable-silent-rules --enable-unicode --with-openssl --with-pcre
```

You should see each clang invocation with the new paths and the linker using the configured libraries.

The macros we use in configure.ac are very basic, just checks if a include file is pressent or if a library has some function defined. There are more complex [macros that use pkg-config](https://autotools.io/pkgconfig/pkg_check_modules.html). The basic ones were enough for most of the gnu/linux distributions I've tested.

-- 
The  ipv6 error don't seem to be related with include paths as it refers to a found header file in your system.
`/usr/include/netinet/ip6.h:113:18: error: field has incomplete type 'struct in6_addr'`
This kind of error usually appears when there are some missing headers. Most probably in the environments I've tested ip6.h also includes other hearders it needs to work, while in MacOSX it doesn't, so I have to check what other header it requires to make struct inet6_addr a complete type. I'll try to dig it :)

Thanks!

**Comment by miconda** [comment]
Doing the export of CFLAGS and LDFLAGS, as you pointed above, made it for pcre and ssl.

However, for unicode is still not working:

```
checking ncursesw/ncurses.h usability... no
checking ncursesw/ncurses.h presence... no
checking for ncursesw/ncurses.h... no
configure: error:  You need to have ncurses development files installed to compile sngrep.
```

I think in this case it should just check for "ncurses.h", not for "ncursesw/ncurses.h", but not sure if this is messing up the way linux deploys ncurses and ncursesw. It may be that mac os x only deploys ncurses with unicode enabled by default.

**Comment by Kaian** [comment]
Usually there are two different ncurses.h files, depending if you require wide-character support or not:

```
 kaian@kaian $ find /usr/include -name ncurses.h
/usr/include/ncurses.h
/usr/include/ncursesw/ncurses.h
```

If you think MacOSX versions of ncurses already has widechar support by default, then you don't require to even use `--enable-unicode`. Also, don't worry to much with unicode: implementing utf8 and unicode in the printed sip payload is still [part of TODO list](https://github.com/irontec/sngrep/blob/master/TODO)  :-/

**Comment by miconda** [comment]
Wasn't --enable-unicode added for the mosh display issue reported in #26? I will have to try it again once I get a chance.

**Comment by Kaian** [comment]
That's true!

Totally forgot about that because I always see arrows, lines and corners ok even with unicode disabled using other clients like ssh or putty (for this one I need to configure Remote Character Set option).

It seems some programs like mosh or screen mess with locale and NCURSES_NO_UTF8_ACS enviroment var and compiling against wide-character ncurses makes them happy.

If the ncurses you're using has wc by default, disabling unicode will in fact include the ncurses.h file that has unicode enabled :). Maybe that's the reason why the [brew formula for MacOSX](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sngrep.rb) doesn't enable unicode: because is already enabled.

**Comment by miconda** [comment]
For the records -- I added some notes based on the discussion here about installing on mac os x in the wiki:

  * https://github.com/irontec/sngrep/wiki/Building

Maybe the reamde should be updated from:

```
You can find detailed instructions for some distributions on wiki.
```

to:

```
You can find detailed instructions for some Linux distributions or Mac OS X on wiki.
```

At the end distribution can cover anything, including windows, although people think more about linux/unix.

**Comment by Kaian** [comment]
Hi @miconda !

Thanks for the contribution to the wiki, it really needs a lot of updates :]]

I try the make the Readme file the most generic possible so it doesn't require to be changed as often as the wiki should be. Things like pointing to the FAQ (one day I will have the time to add more things to that...) instead of actually contain any documentation. To be honest, I've made an exception with the binaries, just because they are an effort of different people and I think it should be highlighted.

In that regard, I like more the term _systems_ or _distribution_ instead of mentioning the actual kernel names, because sngrep could (but won't) actually be built on anywhere where ncurses and libpcap works (although we personally only use it on a couple of GNU/Linux distros).

**Comment by miconda** [comment]
My proposal was based on my experience that the main README.md gets better visibility and most of the projects try to list there the top keyworks for distros, like "known to work on Linux, Windos and Mac OS X". I am fine anyhow.

**Comment by Kaian** [comment]
Yep, I get your point. Sorry if I've sound too picky with the kernel names and thanks again for the Mac instructions using macports :))

**Comment by Kaian** [comment]
Hi @miconda!

For this isssue, I think it is still pending the `--enable-unicode` problem.

As you menstion, macports ncurses [seems to have wide character support](https://trac.macports.org/browser/trunk/dports/devel/ncurses/Portfile#L30) by default, so for this case compiling without enable unicode should have the same effect that enabling it in other systems. Is this correct?

Thanks for you help!

**Comment by Kaian** [comment]
I will close this for now. Not sure If there is pending task related to this.

Feel free to reopen if something is still pending 0:-)

Thanks!
