### ISSUE TITLE
don'nt restore screen after kill sngrep or crashed

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#131]
don'nt restore screen after kill sngrep or crashed

**Comment by michael2009** [comment]
first tty run sngrep
second tty send killall -9 sngrep
then first tty screen issue

**Comment by michael2009** [comment]
maybe need 
   curs_set(1);
   endwin();

**Comment by Kaian** [comment]
Hi michael!

Theres nothing a C program can do when a crash (generally SIGSEV) or SIGKILL (kill -9) signal is received. As far as I know, there is no option to do any final instructions or cleanup when those signals are received, they can not be captured.

If you want that sngrep stops ncurses mode properly as if I have quited using Q/Esc keys, use a different signal (like SIGINT, kill -2) or something. Or let's try to fix those crashes :)

**Comment by michael2009** [comment]
because htop work with kill -9 . but sngrep issue

**Comment by Kaian** [comment]
Umm.. :thought_balloon: 

![htop](https://cloud.githubusercontent.com/assets/800069/16834087/83e2bfe6-49b2-11e6-81df-81f1a7c3ae0e.png)

**Comment by michael2009** [comment]
Did fix with shell command   "stty sane"

**Comment by Kaian** [comment]
Nice! Thanks for sharing a workaround :+1:
