### ISSUE TITLE
Don't display flow with SRTP

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#135]
Don't display flow with SRTP

I had sent mail with srtp_issue.pcap

**Comment by Kaian** [comment]
Sadly I haven't received the mail, maybe the mail server spam filter is removing it.

I'll try to talk to the administrators to try to whitelist your address, as usually I receive your mails flagged as '{spam}' but I still receive them.

Thanks for reporting!

**Comment by Kaian** [comment]
Hi @michael2009 !

I have received your pcap. Give it a try to the commit showed above.

Thanks!

**Comment by michael2009** [comment]
ok . solved
