### ISSUE TITLE
Add New Column to Show SIP Hangup Cause Text

### ISSUE THREAD

**Issue by kismetgerald** [irontec/sngrep#138]
First of all @Kaian , thanks for a very awesome monitoring tool.  This is follow-up to our discussion on IRC.

I'm a FusionPBX user and I've configured follow-me on some of my extensions to deliver calls to a mobile phone in the event a phone is unregistered.  I noticed today that in this scenario, FreeSWITCH sends a SIP 480 - Temporarily Unavailable message.  In this message is embedded a Reason/Hangup Cause of 601 - ATTENDED_TRANSFER (actually the full line is  **SIP;cause=601;text="ATTENDED_TRANSFER"** ).  SNGREP then displays the Call State as REJECTED.

Now in the SIP Message Flow Viewer, it would be nice to have a new column that displays the Reason/Hangup Cause.  So that in this particular instance, the Call State of REJECTED will be more meaningful (i.e., call rejected because of ..........).

**Comment by Kaian** [comment]
Thanks for the request, I will try to add this for the next release after my holidays :) :+1

**Comment by nshopik** [comment]
@Kaian  In case you need field syntax here it is https://tools.ietf.org/html/rfc3326#section-2

**Comment by Kaian** [comment]
Hi!

I assume this header only makes sense for INVITE dialogs?
Also the column will only display the last Reason header _text_ value (in case there are multiple messages with the header in the dialog)

**Comment by Kaian** [comment]
I have set the default column width to 25 which can be changed using _sngreprc_ file (sadly, right now columns are configured based on position and not what attribute is displaying).

**Comment by kismetgerald** [comment]
thanks @Kaian .  Is this change released to the packages yet?  if so, then I can test when I get in the office in about 3 hours.

**Comment by Kaian** [comment]
Hi @kismetgerald 

If you're using the Debian packages, yes: they are built for each commit. You can use the bleeding repos or dowload them manually [here](http://packages.irontec.com/debian/pool/main/s/sngrep/) (check the package times :))

If you are using rpms, I haven't an automated RPM repository created yet (not even sure what software could even use for creating SPEC files on the fly, to be honest) :-(

**Comment by Kaian** [comment]
At this point this should be available in version 1.4.2 in both rpm and debian packages.

**Comment by Kaian** [comment]
This change should be present since a lot of time.

Feel free to reopen if I'm missing something here!

Regards!
