### ISSUE TITLE
Packets Unexpectedly Disappearing from Flow Viewer

### ISSUE THREAD

**Issue by kismetgerald** [irontec/sngrep#140]
**Good-day,**

Thank you for adding the _**-R**_ functionality in v1.4.0, thus making it possible to rotate out old records during a live capture when the capture limit is reached.  Unfortunately, however, I've noticed an odd behaviour which might otherwise go unnoticed by someone how using SNGREP for long-term live monitoring of calls.

So it appears that when I issue this command:  _**sngrep -l 5000 -R port 5060**_ the output is as expected and the older call records get rotated out (which is as expected).  What's unexpected is that the calls keep getting rotated out even if no new calls have come in that would push the capture to the limit.  Oddly enough, the display in the Flow Viewer is also misleading.  That is to say, when the window is kept open long enough for all the packets to rotate out the display still shows **Dialogs: 5000 (26 displayed**.  This is not actually true - well see the image below for yourself.  As you can see in the image below all the packets have rotated off the screen, yet the screen says that 26 dialogs should be displayed.

Can someone please take a look.  I'm not knowledgeable enough in code to be able to tell what's wrong, but it would seem that once the capture limit is reached and a call is rotated out that limit is now reduced by that call that just got rotated out.  So the next rotation shouldn't be happening until the capture limit has been reached again.

![snap 2016-08-29 at 08 36 11](https://cloud.githubusercontent.com/assets/14914151/18051859/0ae233d8-6dc5-11e6-8273-d28bb666978d.png)

**Comment by Kaian** [comment]
Hi @kismetgerald 

I have tried without success to reproduce this problem :( 

To make it easier, i have run `sngrep -l 10 -R port 5060` and set only INVITE and REGISTER in the filters panel. The _displayed_ counter seems to increase and decrease based on what's being showed on the screen. As dialogs are rotated, some of the new dialogs can make the oldest (that may be being displayed because it matches the display filter) to disappear. That's the expected behaviour. The dialog counter will say the same number (5000 -1 +1) but if the dialog rotated was being displayed, the displayed counter should decrease...

This is an example as I see rotated-filtered dialogs:
![rotate-filtered](https://cloud.githubusercontent.com/assets/800069/18084609/1fc9320e-6ea8-11e6-99bf-462d60a56ff6.gif)

**Comment by kismetgerald** [comment]
Hey @Kaian, what you show in your example is the exact behaviour I'm seeing.  So if you say that's the designed behaviour then I'm good with it.  I know not everyone uses SNGREP as a long-term live monitoring application, so this may not be an issue for most.  I actually use this in a NOC so I have it on a screen and it just struck me as odd when I saw packets disappearing which I didn't expect to.

This may perhaps lead to another discussion about the possibility of considering a parameter on the Filter (F7) dialog - where one is asked if they want to discard unfiltered dialogs.  That is to say, current when a filter is engaged, the non-filtered packets are still being captured and count towards the capture limit.  It would be nice to have the option to discard those non-filtered dialogs so that the capture limit represents the true population of filtered dialogs.  Hope that makes sense?

But regarding the issue at hand I'll just file it in the "you just gotta deal with it" pile and move on.  Thanks again for a great product.

**PS.  How did you do that animated gif capture?  That's cool.**

**Comment by Kaian** [comment]
Hi!

Most probably the filters you set in the Filter dialog (that are handled as <i>Display filters</i>) can be specified as <i>Captured filters</i> using command line match expression. The first ones only "hide" dialogs (but they're still stored and rotated), while the second one ignores them complety.

For example, you can capture only INVITE or REGISTERS using 
`sngrep -l 5000 -R "(^INVITE|^REGISTER)" port 5060` 

The gif was made using [ttyrec](http://0xcc.net/ttyrec/) + [ttygif](https://github.com/icholy/ttygif) :smile:

**Comment by kismetgerald** [comment]
Awesome, will try the Captured filters approach.

**Comment by jungle-boogie** [comment]
@Kaian, I setup the filter like you did, `sngrep -l 5000 -R "(^INVITE|^REGISTER)" port 5060`. I saw some traffic and pressed enter to see the stream. Pressed enter again to see the raw view (I think that's what it's called). Now I can escape back to the stream view.  I usually press esc to get back to stream and then the view in your little movie.

Is there a different way to escape back now?

**Comment by jungle-boogie** [comment]
^^ my mistake. Looks like it works fine.

**Comment by Kaian** [comment]
Rotating the packages while updating the displayed ones (when there is a filter enabled) is something expected. But _26 displayed_ when nothing is being displayed is something odd and wrong, so If you manage to reproduce that behaviour feel free to reopen the issue.

Thanks both!
