### ISSUE TITLE
Packet fragment issue with flow viewer

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#142]
Packet fragment issue with flow viewer. Please check mailed pcap file .
![1111](https://cloud.githubusercontent.com/assets/12387494/18225055/791a85ac-721c-11e6-841b-7854be918f7d.png)

**Comment by Kaian** [comment]
Hi @michael2009 

Thanks for the testing pcap  one more time :)))

I have changed the way the length is calculated for IP reassembly, instead of trusting libpcap captured length, I will use the IP header content length.

Give it a try whenever you have time to the latest commit

Thanks!!!

**Comment by michael2009** [comment]
Thanks , fixed
