### ISSUE TITLE
Support "tel" and "urn" schemes in Request-URI

### ISSUE THREAD

**Issue by NGSegovia** [irontec/sngrep#143]
Hi all!
I'm doing some testing and I note that sngrep is not capturing SIP messages that contains in Request-URI addresses which use "tel" scheme (RFC-2806). Probably it only handles "sip" scheme for addressing. 

Example of one of theses messages (captured with tcpdump):
```
    xx.xx.xx.150.sip > xx.xx.xx.192.sip: [udp sum ok] SIP, length: 802
        INVITE tel:+358-555-1234567 SIP/2.0
        Via: SIP/2.0/UDP xx.xx.xx.150:5060;branch=z9hG4bKd21f586514f7dd8d3f0cb904cbbc0b27;rport
        Max-Forwards: 70
        From: 26044628022 <sip:26044628022@xx.xx.xx.150>;tag=f8e0b369b39ac53788b88fb0538564c2
        To: 8129118104 <tel:+358-555-1234567>
        Call-ID: 2F6Ve5CouECIiOOzceWqHemCOgkiFe71
        CSeq: 200 INVITE
        Contact: Anonymous <sip:xx.xx.xx.150:5060>
        Expires: 300
        User-Agent: XXX
        Call-Info: XXX.com
        Geolocation: MyGeolocationValue
        Content-Length: 271
        Content-Type: application/sdp
``` 
  

Thank you

**Comment by Kaian** [comment]
Hi @NGSegovia 

You're true. sngrep only supports `sip:` and `sips:` schemes, but I think i won't be difficult to implement `tel:`

Would be possible to send me a pcap so I can test the new scheme?

Thanks for reporting!!

**Comment by Kaian** [comment]
Also, the RFC you mention includes `fax:` and `modem:` schemes, but I can't see `urn:` anywhere :thought_balloon:

**Comment by NGSegovia** [comment]
Hi!
This comes from other RFC https://tools.ietf.org/html/rfc5031 (check page 4) and it's related to emergency services.

According to SIP RFC 3261 there can be multiple schemes:
```
Request-URI: The Request-URI is a SIP or SIPS URI as described in
           Section 19.1 or a general URI (RFC 2396 [5]).  It indicates
           the user or service to which this request is being addressed.
           The Request-URI MUST NOT contain unescaped spaces or control
           characters and MUST NOT be enclosed in "<>".

           SIP elements MAY support Request-URIs with schemes other than
           "sip" and "sips", for example the "tel" URI scheme of RFC
           2806 [9].  SIP elements MAY translate non-SIP URIs using any
           mechanism at their disposal, resulting in SIP URI, SIPS URI,
           or some other scheme.
```
I think that maybe is better to relax the condition over Request-URI instead of support all posibles schemes.
 
Here is a zipped pcap [tel.pcap.zip](https://github.com/irontec/sngrep/files/459292/tel.pcap.zip)

**Comment by Kaian** [comment]
Hi!

As you suggested, I have updated the matching expression to allow any kind of schemes in the Request-URI.

If you have time, give it a try to the latest `master` commit.

Thanks for your time and the testing pcap :)

**Comment by NGSegovia** [comment]
Hi!
I have compile it and is working great! 

Thanks!
