### ISSUE TITLE
Loss TLS flow view when reconnect tcp

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#144]
Run ./sngrep -k ca.key
Step: 
1. login TLS softphone then show flow view
2. close softphone and open softphone again, then don'nt show flow view

**Comment by Kaian** [comment]
Hi @michael2009 

Could you provide a pcap file with both 1. and 2. steps with a testing key? 
I could check why the 2. step is not handled correctly. It always helps A LOT.

Thanks in advance!
