### ISSUE TITLE
If click Max, min console , Then form display misplace

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#145]
If click Max, min console , Then form display misplace

**Comment by Kaian** [comment]
I thinks only Call List (the first screen you see when you open sngrep) implements resize. The other screens doen't have the function implemented. I will add this as an enhancement!

**Comment by michael2009** [comment]
yes

**Comment by michael2009** [comment]
Still resize issue with Calls list.

**Comment by Kaian** [comment]
Yep, I know I know, but right now I'm focusing in bugs and crashes, because I'm also working in another project that requires a lot of my time.

I don't forget the open issues on GitHub! :innocent:

**Comment by Kaian** [comment]
Fixed in #200
