### ISSUE TITLE
include warning header in columns selection

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#148]
It will be nice to have separate column for warring header. We just need number in it, nothing else, so I guess should be straight forward

https://tools.ietf.org/html/rfc3261#section-20.43
http://www.iana.org/assignments/sip-parameters/sip-parameters.xhtml#sip-parameters-5

**Comment by Kaian** [comment]
HI @nshopik 

Like #138 I assume this header information is only interesting for INVITE dialogs.
Also, only the last Warning header will be printed in the column (as the row displays calls and not messages)

I have notice some of my testing pcaps have Warning header, but the value is quite long, what would you think would be a default width for this column?

Thanks!

Thanks!

**Comment by nshopik** [comment]
> I have notice some of my testing pcaps have Warning header, but the value is quite long, what would you think would be a default width for this column?

Number is enough, usually servers use 399 number for custom messages to give you more details why it failed. And I could easily go into dialog details which have potential interesting number.

**Comment by Kaian** [comment]
Ok, so 4 chars width could be enough then :)

Thanks for the info!

**Comment by nshopik** [comment]
Working as expected
