### ISSUE TITLE
don't show call flow

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#152]
don't show call flow
I had sent mail with pcap file .

**Comment by Kaian** [comment]
Hi @michael2009 

Thanks for the pcap file for testing this issue.
This is a known problem and part of [TODO things](https://github.com/irontec/sngrep/blob/master/TODO#L5), as IP fragments are not ordered.

First packet contains the end of the second packet, so they must be assembled in different order than captured. I will try to improve the assembly process to see I'm able to archive that easily.

Thanks!

**Comment by Kaian** [comment]
Ok, so I have reworked how IP assembly determines a packet has all fragments.

Before, I was waiting for a fragment with _"No more fragments"_ flag, which usually comes in the last position. Now, when I receive that fragment, I use its offset to calculate what is the actual total packet size, and wait more fragments until captured data matches that size.

Give it a try to the latest commit and feel free to report back if I've broken anything.

Thanks for the testing @michael2009

**Comment by michael2009** [comment]
Thanks , fixed
