### ISSUE TITLE
expose cl.sortswap to set via settings

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#161]
There is no cl.sortswap available in settings even though it could be set manually `z` by default to change sorting order

**Comment by Kaian** [comment]
Hi!

Sounds a nice setting and seems not hard to code. I'll give it a try as soon as I can!

Thanks for the request!

**Comment by Kaian** [comment]
I have added two settings `cl.sortfield` and `cl.sortorder` [documented on wiki](https://github.com/irontec/sngrep/wiki/Configuration#options)

The first one have the attribute name (there is also a list on wiki), the secondone 'asc' or 'desc' .
You can even sort by any field (even if it's not being displayed).

If you want to simply change the default order (but not the field), just add
```
$ echo 'set cl.sortorder desc' >> ~/.sngreprc
```

Best regards,
