### ISSUE TITLE
SIP 600 Busy everywhere showing as Call State REJECTED instead of BUSY

### ISSUE THREAD

**Issue by gergernaut** [irontec/sngrep#165]
Really like your tool and the newly implemented call states busy & diverted!
Could you kindly add SIP response code 600 (Busy everywhere) to the codes, that trigger 
"Busy" for the call state column? Currently, whenever a SIP/2.0 600 Busy everywhere is
the response, the call state is shown as "REJECTED".

Thanks a lot and best regards
Kevin

**Comment by Kaian** [comment]
Hi @gergernaut 

Glad to hear that! :)
We must thank those new states to @khoegh [[PR]](https://github.com/irontec/sngrep/pull/154)

I have added the response code to the busy list (now setted by 480, 486 and 600), but I dont have a test file with that response, so If you can give it a try and confirm latest `master` works as expected it will be helpful.

Thanks in advance!

**Comment by gergernaut** [comment]
That was fast :-) 
Just tested: works like a charm, thank you very much!

**Comment by Kaian** [comment]
That was an easy one, hehe!

Closing then. Thanks for the testing!
