### ISSUE TITLE
1.4.2 rpm for CentOS 7

### ISSUE THREAD

**Issue by Ad5t4r** [irontec/sngrep#175]
No rpm package for 1.4.2 build of sngrep.

**Comment by Kaian** [comment]
Hi @Ad5t4r 

You're totally right, the job in task of creating RPM packages stopped and I didn't even notice, sorry for that.

The build have some configure error that happens on centos 7, but not 5 nor 6. I'll add the log here for my fututre myself :)

```
[...]
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for x86_64-redhat-linux-gnu-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... configure: error: in `/builddir/build/BUILD/sngrep-1.4.2':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
[...]
```

**Comment by Kaian** [comment]
Some permission problem in the ccache system of the building enviroment.

The RPMS for centos7, fedora21 and fedora22 should be [now available](http://packages.irontec.com/epel/7/x86_64/).

Thanks for reporting!! :+1:

**Comment by Ad5t4r** [comment]
Awesome stuff. I have updated and works perfect.
Thanks Kaian

**Comment by Kaian** [comment]
Nice! Thanks to you for the warning!
