### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by river9100** [irontec/sngrep#178]
./configure: line 6231: syntax error near unexpected token `SSL,'
./configure: line 6231: `       PKG_CHECK_MODULES(SSL, libssl libcrypto)'
os: debian 8.6 x64
kernal: 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
gcc: gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by Kaian** [comment]
Hi @river9100

This error is due to the changes done in #176
I recommend you to use [latest stable](https://github.com/irontec/sngrep/releases/tag/v1.4.2) release to avoid that problem

Thanks for reporting!!

**Comment by Kaian** [comment]
Also, what OS/distribution are you using?

I had the same problems, but only with very very old systems.

**Comment by goharahmed** [comment]
I got the same problem on Debian 8.7 
Any resolution/workaround so far ?

**Comment by digitaltoast** [comment]
I had the same I just had to rerun ./bootstrap before ./configure and it was ok

**Comment by Kaian** [comment]
Debian Jessie shouldn't be problematic, didn't bootstrap.sh fix the problem?

I will try to check if the pkgconfig macro is available and fallback to the tradicional library search macro if not.

Thanks for the fallback

**Comment by Kaian** [comment]
As mentioned in the commit, this is not actually related with the distribution, so what I was pointing about jessie is not actually true.

If pkg-config is not present in the system the macro is not available making configure fail, even after bootstrap.sh is used

The previous commit should work for both systems with and without pkg-config.

Thanks for reporting and the feedback of everyone in the thread.
