### ISSUE TITLE
Request: Releases include an attached Distribution tarball

### ISSUE THREAD

**Issue by abelbeck** [irontec/sngrep#181]
It looks like a new release may be on the horizon, as such it would be very helpful if a Distribution tarball was attached (and SHA1 hash if you wish) with the configure script pre-generated.

Additionally, attached files are more convent for distros to download since the filenames can be of the form: ```sngrep-1.4.3.tar.gz```

For example the netcalc project:
https://github.com/troglobit/netcalc/releases

**Comment by Kaian** [comment]
Hi @abelbeck 

In the initial releases (0.x.x) a configure script was included in the releases, but it worked/failed depending on the version of automake of the system (See [this comment](https://github.com/irontec/sngrep/issues/20#issuecomment-73230315)), so I dediced to include the _bootstrap.sh_ (like other projects include _autogen.sh_) so everybody could do a working configure script by themselfs. In other words, I still don't know how to release a generic flawless configure script for everyone :sweat_smile: 

For the tarball of the source, I will do it from now on. It's not too much effort to attach a couple of files :)

https://github.com/irontec/sngrep/releases/tag/v1.4.2

Thanks for the feedback!

**Comment by abelbeck** [comment]
@Kaian Thanks for the explanation, the tarball helps a lot.

**Comment by Kaian** [comment]
No problem!

I'm closing then.

Reopen if you need anything more. Or if someone has any trick to do a good configure screen or any related documentation
