### ISSUE TITLE
User part of SIP URI is optional

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#183]
if some message (OPTIONS for example) contain such header
```
From: <sip:192.0.2.1>;tag=4E324FD8-692`
```
It will be incorrectly parsed in main list and show as `192.0.2.1>;tag=4E324FD8-692` as SIP From row

https://tools.ietf.org/html/rfc3261#section-19.1.1

**Comment by Kaian** [comment]
Hi @nshopik 

I think I can adapt the parsing regular expressions to handle this header formats!

Thanks for the report.

**Comment by Kaian** [comment]
It should be fixed in the latest `master` commit.

I also updated the columns SIP From User and SIP To User that was displaying the IP/domain of the URI in the header instead of empty.

Thanks for reporting! :))

**Comment by Kaian** [comment]
This should be fixed in 1.4.3 

Feel free to reopen if it doesn't work as expected and will try to fix for the next release.

Thanks @nshopik !!
