### ISSUE TITLE
Official token for comment in config

### ISSUE THREAD

**Issue by SebastianThorn** [irontec/sngrep#184]
Seems like both # and ; works for comments in config-file,
but none of those are defined on the wiki https://github.com/irontec/sngrep/wiki/Configuration

What is preferred for the config-parser?
Thanks for awesome software!

**Comment by Kaian** [comment]
Hi @SebastianThorn !!

The _official_ comment characteris is # (or at least [the code ignore those](https://github.com/irontec/sngrep/blob/master/src/option.c#L120) on purpose).

Other characters may work, as the config parser only handles lines starting with a couple of directives (set, alias, and so on) ignoring the rest of the lines that doesn't match (so ;set %set *set are all ignored) without printing any warning at all.


I have [updated the wiki](https://github.com/irontec/sngrep/wiki/Configuration#comments) encouraging the use of # at the beginning of the line to ignore lines :)
Feel free to edit the wiki if you want to add any extra information, anyone can :dagger: 

Thanks for the feedback!

**Comment by Kaian** [comment]
It seems I also used that comment style for the [default sngreprc file](https://github.com/irontec/sngrep/blob/master/config/sngreprc) :smile:

**Comment by Kaian** [comment]
I hope this is a bit more clear now. Thanks for the feedback!

Feel free to reopen if you have any question or suggestion
