### ISSUE TITLE
Certain files coming up blank in sngrep

### ISSUE THREAD

**Issue by mattrea10** [irontec/sngrep#189]
I have a specific pcap file that is opening on sngrep, but not displaying any of the file's data in sngrep. The file displays the data just fine when I open it in Wireshark. I have a suspicion that this has something to do with the fact that it is a "tcpdump capture file" that is in a pcap format, but I am not sure what route I should take to resolving this. Any help would be much appreciated.

**Comment by Kaian** [comment]
Hi @mattrea10 

If the information of the pcap is not too sensible, you can send it to me so I can debug it.
It could be related with assembly or SIP payload CRLF end of lines (or anything else).

Thanks for reporting!

**Comment by mattrea10** [comment]
Hi @Kaian 
Here's the file. I hope you have better luck than I did :)
[4f8ec403613ab335086cb25d78840884@10.128.77.226-5060.pcap.gz](https://github.com/irontec/sngrep/files/1025569/4f8ec403613ab335086cb25d78840884.10.128.77.226-5060.pcap.gz)

**Comment by Kaian** [comment]
Hi @mattrea10 

Next time, If you prefer not attaching sensible info, you can send it to my email address (should be in my github profile) :+1:

I have debugged the pcap and it seems it has Q802.1Q VLAN header. 
sngrep, only [detects this headers](https://github.com/irontec/sngrep/blob/master/src/capture.c#L385) if the link type is ethernet and the ether_type indicates the header is present.

Sadly your pcap has Linux cooked link (DLT_LINUX_SLL) which [also seems to have that field](https://linux.die.net/man/7/pcap-linktype), so maybe I can implement a logic to skip the header in this cases.

Btw, I have also notice that ngrep doesn't show anything for this file :thinking: 

Thanks for reporting and the testing pcap!

**Comment by Kaian** [comment]
If you can, give it a try to the latest `mater` commit. It should now show messages with those headers.

**Comment by Kaian** [comment]
No problem! How are you installing sngrep? From sources? Or some binary package?

**Comment by mattrea10** [comment]
i installed sngrep with homebrew. So `brew install sngrep`

**Comment by mattrea10** [comment]
Ok, well thank you @Kaian for all of your help!  😊

**Comment by Kaian** [comment]
Thanks to you for reporting. Now we support something that we didn't before :)

Feel free to reopen if you need to add any extra information. Also, if you try compiling from sources in Mac and you find any useful information, the linked wiki page can be modified by anybody.
