### ISSUE TITLE
480 Temporarily unavailable, but overview still shows "CALL SETUP"

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#19]
The remote party answered  to my INVITE:
100 Trying
183 Session Progress
480 Temporarily Unavailable
Then I answer with ACK.

sngrep still shows the call as "CALL SETUP"

I can send you the packet capture privately.

**Comment by Kaian** [comment]
Hi @ssinyagin !

Thanks for reporting :)

I was only considering 486 and 603 response codes as REJECTED, but I think all Client (4XX), Server (5XX) and Global (6XX) failures should be displayed as REJECTED too. 

If a new INVITE request is sent after a failure, call status will be again in CALL SETUP, so dialog can change from REJECT to CALL SETUP after a failure response code.

For example:

    INVITE -> CALL SETUP
    404 Unauthorized -> REJECTED
    ACK
    INVITE -> CALL SETUP
    100 Trying 
    180 Ringing
    200 OK -> IN CALL
    ACK
    BYE -> COMPLETED
    ACK

**Comment by ssinyagin** [comment]
yes, that one in my tests was a call without authentication. Actually 404 is a special and frequently-used case, so maybe a special display string is even better, like AUTHREQ

thanks for the great tool, by the way :)

**Comment by Kaian** [comment]
Actually this feature is inspired in wireshark VoIP Calls dialog, where only following states are considered:

    CALL SETUP
    RINGING
    IN CALL
    CANCELLED
    COMPLETED
    REJECTED
    UNKNOWN

Creating more states will be nice for feedback, but some states will last only milliseconds.

In Authentication responses (404, 407,..), most probably a new INVITE request with authentication will be sent right away so AUTHREQ won't be shown to our human eyes.

Glad to know this tools helps!!

**Comment by ssinyagin** [comment]
I saw the link in freeswitch-user mailing list, and I posted it to G+ :)
actually in case of unsuccessful authentication, the corresponding status indication will be nice

**Comment by ssinyagin** [comment]
the fix worked fine, we can close this ticket

**Comment by Kaian** [comment]
Nice!

 If while using sngrep you actually feel the need that the new state for Authentication is actually required, feel free to open a new issue :)

Thanks again!
