### ISSUE TITLE
Patch: Fix Ncurses wchar detection.

### ISSUE THREAD

**Issue by aduskett** [irontec/sngrep#190]
Currently; sngrep has issues detecting Ncurses wchar support in Buildroot.
I did some digging and found a program (htop) that does a good job of detecting wchar support in Buildroot and modified the relevant files to fix sngrep.

This patch does the following:
 - Add SNGREP_CHECK_SCRIPT to configure.ac which checks for a
   libname, a function in that library, sets a define if found, and
   if not found, moves on to the next part. This is taken from the
   htop configure.ac.

 - Adds SNGREP_CHECK_LIB to configure.ac which checks for a
   library, a function within that library, sets a define if that function
   is found, and if not found, moves on to the next part.
   This is taken from the htop configure.ac

 - Modifies scrollbar.h and ui_panel.h to include <wctypes.h> instead of
   <ncursesw/ncurses.h> if unicode is supported.

Let me know what you think!

Adam
[0001-sngrep-fix-wchar-detection.txt](https://github.com/irontec/sngrep/files/1029333/0001-sngrep-fix-wchar-detection.txt)

**Comment by Kaian** [comment]
Hi @aduskett 

Sorry for the delay, quite busy these days.

The wide character support in sngrep is quite _bleh-meh_. Altough we use the widechar ncurses version, we don't actually use its functions to print anything (nor event SIP payload which is UTF-8), so there's still a lot to improve in the source.

In the future, maybe I start using the _ax_with_curses.m4_ part of autotools archive to detect wide-character support of ncurses. Not sure if you have any thoughts about that macros.

I have created a PR #191 for this change, moving the macros to a custom file so the configure scripts only contains the main directives. Feel free to add any comment or suggestion there. After all it's your code and I want your approvement.

Thanks for all !

**Comment by aduskett** [comment]
Hey Kaian!

Thanks for getting back to me! That's fantastic news!  I am currently testing the commit!  As for the ax_with_curses.m4 part of autotools, I will gladly take a look at the macro for you, although I might be busy in the next few weeks.

Thanks again for using the patch!

Adam

**Comment by Kaian** [comment]
Merged in #191 

Thanks!!

**Comment by abelbeck** [comment]
@aduskett I see you reverted this in upstream Buildroot ...

sngrep: remove ncurses wchar support
https://git.buildroot.net/buildroot/commit/package?id=84f774587506e036872c1572d0415c8f24f8d6c5

Should PR #191 be reverted here ?

**Comment by aduskett** [comment]
No, I don't think so.

When Sngrep uses wchar's a bit more, then we will just re-include it.  :)
