### ISSUE TITLE
Save filters

### ISSUE THREAD

**Issue by cerienj** [irontec/sngrep#192]
Great tool, many thanks !

Is there a way to save the filters (F7) so that at next restart, they are restored ?

J.

**Comment by Kaian** [comment]
Hi @cerienj 

Thanks! Glad to hear that!

From that screen you can only save the enabled methods in _filter.methods_ setting. For example:
```
echo set filter.methods INVITE,MESSAGE,PUBLISH >> ~/.sngreprc
```

To see current value for the setting, you can run:
```
$ sngrep -D | grep filter.methods
SettingId: 36	 SettingName: filter.methods       Value: INVITE,MESSAGE,PUBLISH
```

Best regards!

**Comment by cerienj** [comment]
Works like a charm, thanks !

Again, congrats on this superb tool
