### ISSUE TITLE
Show if sngrep listening for EEP packets

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#194]
Currently there no indication that sngrep also listening for EEP packets in interface. I'd be helpful to have it   in `Current Mode` field

**Comment by Kaian** [comment]
As always, the main problem with the UI is the limited space.

I could add an indicator, something like `Current Mode: [eth0][eep:L:9060]` or `Current Mode: [eth0][eep:H:9060]` to indicate we're sending or receiving packets through eep. Although not sure about the port :thinking:

**Comment by nshopik** [comment]
Looks good to me, and usually you rarely need capture on both interface and HEP, so space shouldn't be a problem

**Comment by Kaian** [comment]
As described in the previous commit I have decided to set the labels to [H:port] and [L:port] because sngrep actually supports both modes to be enabled at the same time :)
