### ISSUE TITLE
Issue on Window Resize.

### ISSUE THREAD

**Issue by fsantulli** [irontec/sngrep#197]
As NCURSES support Terminal window resize, i was wondering if is possible to redraw the current status window when this happens.

**Comment by Kaian** [comment]
HI @fsantulli 

There're actually [handlers for window resizing](https://github.com/irontec/sngrep/blob/master/src/curses/ui_call_list.c#L58) in the code, but the implementation is quite bad. Only Call List (the first window) implements it and it has noticeable flaws.

sngrep only redraw screens when required (honoring redraw function of each window), and only the _dynamic_ content. The static part of the screen is created on window initialization.

I have time, I will try to implement the rest of the window resizing functions. As a workaround if you're in call flow and resize the window, go back to the list window (that should resize) and forth to the arrow flow: the new flow should be drawn with the new updated windows size.

This was also requested long time ago in #145

Thanks for the feedback!

**Comment by fsantulli** [comment]
I've created a Pull Request (https://github.com/irontec/sngrep/pull/200) with small fixes. Please review and eventually merge the code.

Best Regards.
- Federico Santulli

**Comment by Kaian** [comment]
I think this has been fixed by the reporter!

Thanks Federico for your contribution!
