### ISSUE TITLE
Regression in pcap file search and save to new pcap file

### ISSUE THREAD

**Issue by khoegh** [irontec/sngrep#199]
I use the following command:
`sngrep -q -N -I <input>.pcap -O <output>.pcap <searchstring>`

After updating sngrep, the output pcap file is always 24 bytes (empty).
I bisected to commit be708634c13e771a79ebf719ffa42c04961b3505

Am I doing something wrong?

Keep up the good work :-)

**Comment by Kaian** [comment]
Hi @khoegh 

Hmm, you're correct. That commit in fact has broken the input more than the output.
If you remove the -q flag, you'll see no packet is being even parsed and Dialog count is always 0.

I'll will check it asap.

Thanks for reporting!

**Comment by Kaian** [comment]
Hi,

The above commit should fix the problem.
The condition to keep running in no interface mode was only working while capturing from devices, but not while reading from input files. It exited directly without reading anything!

Thanks for reporting, any kind of testing is highly appreciated.

**Comment by khoegh** [comment]
It works, that was quick.
Sorry, I couldn't keep up with your pace :-)
Thanks a lot.

**Comment by Kaian** [comment]
Thanks to you for reporting!

I had too little spare time last year, but i think I will do 1.4.4 with this and the latest fixes.

Closing then!
