### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [irontec/sngrep#201]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by abelbeck** [comment]
I currently run shellinabox on my sngrep box and works quite well on most any device with a web browser.

**Comment by Kaian** [comment]
Hi @timofonic 

It sounds quite nice for a 2.0 release (this is a huge change), but there are some UI components that are not classic widgets (like flow diagrams for example), so I don't think this will be easy to implement.

Also, I've been searching a bit the [project documentation](https://doc.opensuse.org/projects/libyui/HEAD/annotated.html) and I'm not sure if libyui is designed for C projects (as examples are C++ code).

Do you know other C project using this?

Thanks for the feedback and suggestion!

**Comment by Kaian** [comment]
As mentioned before, I was unable to find **C** bindings for libyui, so sadly, this can not be used by sngrep.

Feel free to reopen if you have any further info!
