### ISSUE TITLE
Compile fails on CentOS 5.11

### ISSUE THREAD

**Issue by khoegh** [irontec/sngrep#202]
Yes, I know CentOS 5.11 is very old.

I've got the following installed:
autoconf-2.59-12
automake-1.9.6-3.el5
gcc-4.1.2-55.el5
git-1.8.2.1-1.el5
libpcap-devel-0.9.4-15.el5
make-3.81-3.el5
ncurses-devel-5.5-24.20060715
openssl-devel-0.9.8e-36.0.1.el5_11
pcre-devel-6.6-9.el5

git clone https://github.com/irontec/sngrep ; cd sngrep ; ./bootstrap.sh ; ./configure
<snip>
configure: sngrep configure finished                            
configure: ====================================================== 
configure: GnuTLS Support               : no
configure: OpenSSL Support              : no 
configure: Unicode Support              : no  
configure: Perl Expressions Support     : no              
configure: IPv6 Support                 : no               
configure: EEP Support                  : no               
configure: ====================================================== 
configure: 
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: Makefile.in

After adding AM_PROG_CC_C_O to configure.ac I get:
<snip>
configure: sngrep configure finished                            
configure: ====================================================== 
configure: GnuTLS Support               : no
configure: OpenSSL Support              : no 
configure: Unicode Support              : no  
configure: Perl Expressions Support     : no              
configure: IPv6 Support                 : no               
configure: EEP Support                  : no               
configure: ====================================================== 
configure: 
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands

make fails:
Making all in src
make[1]: Entering directory `/usr/local/src/sngrep/src'
make  all-am
make[2]: Entering directory `/usr/local/src/sngrep/src'
if gcc -DHAVE_CONFIG_H -I. -I. -I.      -g -O2 -MT sngrep-capture.o -MD -MP -MF ".deps/sngrep-capture.Tpo" -c -o sngrep-capture.o `test -f 'capture.c' || echo './'`capture.c; \
        then mv -f ".deps/sngrep-capture.Tpo" ".deps/sngrep-capture.Po"; else rm -f ".deps/sngrep-capture.Tpo"; exit 1; fi
In file included from capture.c:37:
capture.h:72:22: error: pcap/sll.h: No such file or directory
capture.c: In function ‘capture_packet_reasm_ip’:
capture.c:401: error: dereferencing pointer to incomplete type
capture.c: In function ‘capture_set_bpf_filter’:
capture.c:856: warning: passing argument 3 of ‘pcap_compile’ discards qualifiers from pointer target type
make[2]: *** [sngrep-capture.o] Error 1
make[2]: Leaving directory `/usr/local/src/sngrep/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/sngrep/src'
make: *** [all-recursive] Error 1

**Comment by Kaian** [comment]
Hi @khoegh 

I think the key message is `config.status: error: cannot find input file: Makefile.in`

Automake (one of the commands run in [bootstrap.sh](https://github.com/irontec/sngrep/blob/master/bootstrap.sh#L40) should crete Makefile.in from Makefile.am

I've time I will try to test why automake is not generating the Makefiles templates in a docker container

Regards!

**Comment by khoegh** [comment]
Sorry, the bad formatted bug report.
I add AM_PROG_CC_C_O to configure.ac, then rerun  ./bootstrap.sh ; ./configure
Now Makefile is created, and make fails

**Comment by Kaian** [comment]
Then the key message must be ... `capture.h:72:22: error: pcap/sll.h: No such file or directory`

This include was added in e50176a534f71e5730b851e07f6e6ae1d653d02e when I made the assumption that if DLT_LINUX_SLL is defined the file pcap/ssl.h will exist, and it seems wrong.

While I fix this, i recomend to reset to the latest stable version after cloning.

`git clone https://github.com/irontec/sngrep ; cd sngrep ; git reset --hard v1.4.3 ; ./bootstrap.sh ; ./configure`

Thanks for reporting!

**Comment by khoegh** [comment]
You are right @Kaian , I still need AM_PROG_CC_C_O in configure.ac
git reset --hard v1.4.3 ; echo "AM_PROG_CC_C_O" >> configure.ac ; ./bootstrap.sh ; ./configure

The following also works :-)
git clone https://github.com/irontec/sngrep ; cd sngrep
git show e50176a534f71e5730b851e07f6e6ae1d653d02e | patch -p 1 -R
echo "AM_PROG_CC_C_O" >> configure.ac
./bootstrap.sh ; ./configure

**Comment by Kaian** [comment]
Okey! I'll try to remember that. According to docs It has been replaced in newer versions of automake.
It's strange because I was quite sure I had [rpm for centos 5](http://packages.irontec.com/centos/5/x86_64/) in 1.4.2  :confused: 

> AM_PROG_CC_C_O
> This is an obsolescent macro that checks that the C compiler supports the -c and -o options together. Note that, since Automake 1.14, the AC_PROG_CC is rewritten to implement such checks itself, and thus the explicit use of AM_PROG_CC_C_O should no longer be required.

**Comment by dunst0** [comment]
The file is also not available on FreeBSD.

**Comment by Kaian** [comment]
If you have time, check latest commit. Thanks!

**Comment by khoegh** [comment]
It works for me.
Thanks @Kaian

**Comment by dunst0** [comment]
Btw for me as well. 👍
