### ISSUE TITLE
Debian Stretch / tmux  layout screwed up

### ISSUE THREAD

**Issue by sumitbirla** [irontec/sngrep#205]
sngrep version 1.4.2 installed from Debian Stretch repo,  the call flow window layout is messed up in tmux.  The same screen is rendered properly if I don't view in a tmux session.  The main screen is fine whether it is a tmux session or not.

**Comment by Kaian** [comment]
Hi @sumitbirla 

If you mean the border lines are not properly displayed, this is a known problem. There is a workarround that uses ascii chars to draw borders and arrows (worse looking but usable). Simply export an environment variable before running sngrep.

```
export NCURSES_NO_UTF8_ACS=1
```

If this is not the case, please attach an screenshot of the problem :D

Regards!

**Comment by sumitbirla** [comment]
It is more than just the borders.  Here is a screenshot:

![screen shot 2017-09-25 at 7 43 20 am](https://user-images.githubusercontent.com/394599/30806863-6488db28-a1c5-11e7-8468-22bcc02dc810.png)

Thanks.

**Comment by Kaian** [comment]
I was unable to reproduce this on Debian 9.1 with a fresh install tmux neither with sngrep 1.4.2 (from debian repositories) nor 1.4.4 (from irontec repositories).

I have tested with multiple terminals (guake, xterm and terminator) even with small cols/lines without luck :(

![tmux](https://user-images.githubusercontent.com/800069/30928073-c7cabf20-a3ba-11e7-9c00-509b629d834f.png)

**Comment by sumitbirla** [comment]
I apologize; I just checked my set up again and the machine from where I launch tmux is actually Ubuntu 16.04.3 LTS.   The SSH sessions are all to Debian 9.1 machines running sngrep 1.4.2.     Thanks for looking into this.

**Comment by Kaian** [comment]
From my gentoo box via ssh to a Debian 9.1 still no luck.

kaian@kaian ~ $ tmux -V
tmux 2.5

**Comment by Kaian** [comment]
My first thought was COLS and LINES ncurses variables was not giving the proper dimensions of the terminal, but the vertical lines used in the columns and the separator of the payload preview panel are drawn in a single call function each, so it has no sense that part of the line is missplaced :(

**Comment by sumitbirla** [comment]
I have a feeling that perhaps there is nothing wrong with tmux or sngrep.   It works fine from all my Debian machines except for the one Ubuntu server I have.  I will launch another Ubuntu server to see if the problem is there as well and report my findings here.

**Comment by Kaian** [comment]
Any news about these problems? :)

**Comment by Kaian** [comment]
I will timeout this. Feel free to reopen if you have further info! Thx!

**Comment by whyteks** [comment]
I know this is old, but I experienced it and solved it with TERM=screen
