### ISSUE TITLE
RPMs for Centos 6 & 7

### ISSUE THREAD

**Issue by daniel-lucio** [irontec/sngrep#206]
Enjoy
http://inside-out.xyz/technology/sngrep-1-4-4-rpm-for-centos-6-7.html

**Comment by Kaian** [comment]
Nice!

Could you provide the spec file for building those RPMs?

Do you know if it will work for Centos5? We could update [this one](https://github.com/irontec/sngrep/blob/master/pkg/rpm/SPECS/sngrep.spec)
