### ISSUE TITLE
F2 save error if pcap include vrrp packet

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#207]
Run sngrep -I 001.pcap
Press F2 and save file , then show error "/tmp/test.pcap: link-layer type 1984662150 isn't supported in savefiles"
[sip+vrrp.zip](https://github.com/irontec/sngrep/files/1366677/sip.vrrp.zip)

**Comment by Kaian** [comment]
Hi @michael2009 

In fact the problem can be reproduced with any offline pcap (even the one in tests/aaa.pcap) and was introduced while fixing #199

If you have time to test the latest commit and check if it fixes the problem it would help.

Thanks for reporting!!

**Comment by michael2009** [comment]
Thanks. 
Solved now .
