### ISSUE TITLE
Loss tcp flow with online cap, but show with sngrep -I

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#209]
![003](https://user-images.githubusercontent.com/12387494/31314490-5b922244-ac34-11e7-9a52-399a054aa0db.png)
[loss.zip](https://github.com/irontec/sngrep/files/1366674/loss.zip)

**Comment by michael2009** [comment]
[loss.zip](https://github.com/irontec/sngrep/files/1366673/loss.zip)

**Comment by michael2009** [comment]
First transaction with UDP , Second transaction with TCP
Then issue happen.

**Comment by michael2009** [comment]
Maybe other tcp issue .
[tcp_loss2.zip](https://github.com/irontec/sngrep/files/1366714/tcp_loss2.zip)

tcpdump and sngrep startup same time . 
tcpdump.pcap with sip tcp .
sngrep_online.pcap no tcp flow .

**Comment by Kaian** [comment]
Hi @michael2009 

This is quite hard to debug, because it can not be reproduced in offline mode (using pcap).
Contrary to tcpdump, sngrep tries to assemble TCP segments and if somehow it fails data may not be displayed at all. 

Are you using any command line filtering options or you just run `sngrep`?

Regards,

**Comment by michael2009** [comment]
I can do tcp test with you at AWS server .

**Comment by Kaian** [comment]
This seems to be the same problem that #214 describes...

Can be this reproduced with **all TCP traffic**? I will try to capture some TCP dialogs whenever I have the time...

Thanks @michael2009 !

**Comment by michael2009** [comment]
Yes, cap issue with all online tcp
 
 
------------------ Original ------------------
From: "Kaian"; 
Date: 2017年10月28日(星期六) 凌晨0:02
To: "irontec/sngrep"; 
Cc: "michael2009"; "Mention"; 
Subject: Re: [irontec/sngrep] Loss tcp flow with online cap, but show withsngrep -I (#209)

 

This seems to be the same problem that #214 describes...
 
Can be this reproduced with all TCP traffic? I will try to capture some TCP dialogs whenever I have the time...
 
Thanks @michael2009 !

**Comment by michael2009** [comment]
I can show test at AWS sip tcp server . do it ?

**Comment by Kaian** [comment]
I leave the AWS test as last resort.
There are things I can still test related to TCP issues.

One thing, are you using any TLS keyfile in your command line or configuration file like #214 reports?

Thanks!

**Comment by Kaian** [comment]
Hi, 

If you have time, please give it a try to previous commit to check if it fixes the TCP problem.

Thanks for the testing!

**Comment by michael2009** [comment]
Hi,
Solved for exist tcp connection . But still issue for new tcp connect, example issue for new tcp register

**Comment by michael2009** [comment]
Yes, confirm issue if with -k for tcp . but no solved with new commit

**Comment by michael2009** [comment]
I have one idea , add fuction for  support tls ip:port define . then will solve two issue 
1. solve tls capture issue if tls handshake before run sngrep .
2. will solve tcp flow loss issue. 

Then sngrep will recod ssl connect use tls handshake or ip:port static recod

**Comment by michael2009** [comment]
sngrep -k tls.key and F2 save tls dialog to test.pcap
next sngrep -k tls.key -I test.pcap , then no callflow .
maybe bug.

**Comment by michael2009** [comment]
Did sngrep F2 save , then saved TCP data packet only . nerver save tcp connect or tls handshake 
Then must issue.
