### ISSUE TITLE
selection not visible in monochrome terminal

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#21]
hi again
in SecureCRT in monchrome mode, the selection is not visible on the overview screen. I will test in more detail later tonight.

**Comment by Kaian** [comment]
Also, try with the option `set background dark` in the sngreprc file (in /etc/ or your system dir)

You can change this option only for your user in `$HOME/.sngreprc` file.

Most of the testing is done with terminals with color enabled, so a screenshoot will be appreciated.

Thanks!

**Comment by Kaian** [comment]
I was able to reproduce this issue disabling ncurses color mode.

There are still parts that are not properly drawn (like colum headers, titles and keybindings), but at least now it can be used.

If you can, give it a try to fix_monochrome branch.

**Comment by ssinyagin** [comment]
yes, now it works fine in monochrome.

Another issue: the output doesn't fit into 132 columns (standard wide terminal size), and completely broken in 80 columns (standard terminal size). I think it makes sense to fit it into 132 columns, and print an error if the terminal is 80 symbols wide.

Also, "destiny" has a completely different meaning than "destination". I think it's better to cut it to "dest".

**Comment by Kaian** [comment]
I try to avoid width restriction (initially set to 120 columns in v0.0.0). 

Even with very little space on screen, users can configure what columns want to fit in that space  in `sngreprc` file (maybe method, from and msg count is enough for them) 
In Call flow , Raw preview panel can toggled, so at least two or three address columns can be displayed. Displayed columns width can also be configured in `sngreprc`.

If you provide some screenshots, I may distinguish between broken or not properly configured for your terminal width :)

About "destiny"... Oops! The proper column name should be Destination I guess.  It's title width, again, will be the one configured in `sngrep` file, which by default is enough to fit all the word without abbreviation.

Thanks a lot for the feedback!

**Comment by Kaian** [comment]
I have changed first two columns width to 30:

    # echo set cl.column0.width 30 >> ~/.sngreprc
    # echo set cl.column1.width 30 >> ~/.sngreprc

And it fits in 132 columns, so I am considering reducing the SIP From and To columns to 30 so the default Call List panel can be properly displayed by default with that width. Less than that, user _should_ configure what to see :)

**Comment by ssinyagin** [comment]
thanks. I found another glitch with F10 and toggling the columns -- the
display isnot always re-drawn correctly. I'll make it a more through test
over the weekend.

**Comment by Kaian** [comment]
I also found a bug about that feature. If you set too many columns using a small screen width ... it crashes. 

If you don't mind, I prefer handling each problem in different issues :D

I will merge fix_monochrome on monday
