### ISSUE TITLE
Error while writing file (F2)

### ISSUE THREAD

**Issue by Olpag** [irontec/sngrep#212]
sngrep 1.4.4 installed from Irontec RPMs repository

1. Run sngrep -l 10000 -R -N -O capture2.pcap

2. I closed and opened sngrep again: 
sngrep -I capture2.pcap

3. I highlighted several dialogues and tried to save them to a file. 
And got an error "link-layer type 1984662150 isn't supported in savefiles" like [#207](https://github.com/irontec/sngrep/issues/207)

Then I copied the file capture2.pcap to another server and repeated points 2 and 3 with sngrep 1.4.2
No problems. Saved file "0507794968.pcap"
[bug_save.zip](https://github.com/irontec/sngrep/files/1406456/bug_save.zip)

**Comment by Kaian** [comment]
Hi Olpag,

 Could you give it a try to latest `master` branch commit? It should address this issue

Thanks!

**Comment by Olpag** [comment]
Hi Kaian,
Latest `master `branch commit solwed problem. Thanks!
