### ISSUE TITLE
sngrep does not build (--with-openssl) with OpenSSL >= 1.1.0

### ISSUE THREAD

**Issue by kvrban** [irontec/sngrep#213]
e.g see that comment what to do:
https://github.com/openssl/openssl/issues/962#issuecomment-208792020

**Comment by Kaian** [comment]
Hi @kvrban 

Thanks for reporting! The previous commit applies the changes suggested in the issue you mentioned and I have successfully tested with OpenSSL 1.0.0 and below.

Would you mind giving it a try with OpenSSL 1.1.0?

Thanks in advance!

**Comment by kvrban** [comment]
Hi, i can confirm. It does build now with OpenSSL 1.1.0.
