### ISSUE TITLE
TLS/TCP Issues

### ISSUE THREAD

**Issue by iliesh** [irontec/sngrep#214]
I don't see any information in sngrep when using TLS protocol.

I'm using the following command:
**root@debian:/# sngrep -k /home/user/privkey1.pem**

**root@debian:/# sngrep --version**
sngrep - 1.4.4
Copyright (C) 2013-2017 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with GnuTLS support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with EEP/HEP support.

Written by Ivan Alonso [aka Kaian]

With TCP is the same issue, i can see only UDP packets. What i'm missing?

_sngrep was compiled from source code. OS: Debian 9.2 x64_

**Comment by Kaian** [comment]
Hi @iliesh 

Currently only two ciphers are supported. (check #59)
Also, sngrep must capture the initial ssl handsake in order to get the ssl session data (is not possible to decrypt starting sngrep after the connection has been established).

You can check the used cipher in ServerHello message using ssldump, wireshark or other tool.

Thanks for reporting!

**Comment by iliesh** [comment]
Hi @Kaian ,
Thank You for the info.  What about TCP connections? I can't see them as well.

**Comment by Kaian** [comment]
Hi @iliesh 

Can you provide a pcap from a raw capture tool like tcpdump or ngrep with some TCP SIP messages? If messages doesn't show while opening with sngrep in offline mode it may be a bug.

Having testing files helps a lot in these cases. You can zip and attach it to the issue or send it to my email.

Thanks for your time!

**Comment by iliesh** [comment]
Hi @Kaian,
Well, i found that sngrep are not showing TCP messages when it is started with "-k" option.
_sngrep -k /home/user/privkey1.pem_

If i'm starting without any options - then all messages (UDP&TCP) are showing normally.
I don't know if this is a bug - but you can replicate this issue on your server and check. If you still need pcap file from me - i can provide it as well.
Thank You.

**Comment by Kaian** [comment]
Hi @iliesh 

I've been able to reproduce this with a pcap file thanks to your hint of using the private key.

The problem can easily be reproduced if the pcap contains the initialization SYN, SYNACK, ACK sequence. It seems capturing that sequence makes sngrep to think the connection is TLS when it may be a normal TCP connection establishment. If sngrep is started after TCP connection has been established (so no SYN packet is captured), it should show the SIP dialogs without problem.

I'll debug it and give some feedback here.

**Comment by Kaian** [comment]
Hi, 

If you have time, please give it a try to previous commit to check if it fixes the TCP problem.

Thanks for the testing!

**Comment by iliesh** [comment]
Hi  @Kaian,
Now is better. Thank You for the fix and generally for this great software ;)
