### ISSUE TITLE
Sngrep -c  is not working correctly

### ISSUE THREAD

**Issue by gudge25** [irontec/sngrep#215]
![image](https://user-images.githubusercontent.com/2346208/32167267-18dc27f8-bd71-11e7-9b85-59e85fee886e.png)

MUST BE    <-----SIP/2.0 401 Unauthorized 
between 2  packades

**Comment by gudge25** [comment]
1 have ~ 200 concurrent calls

**Comment by Kaian** [comment]
Hi @gudge25 

Could you provide a pcap file from another raw capturing tool like ngrep or tcpdump so I could debug why the contents are not being displayed?

Thanks for reporting!

**Comment by gudge25** [comment]
ok i will do IT

**Comment by Kaian** [comment]
Is this still a problem in latest versions?

**Comment by gudge25** [comment]
willl update  U ASAP

**Comment by gudge25** [comment]
seems it was a problem with  errors  on network interfaces  --- we transfer Asterisk to a new server and i cant see same behavior ---
if it will appear again i will reply U ASAP
THANKS
