### ISSUE TITLE
Feature Request: B-Leg Correlation

### ISSUE THREAD

**Issue by marrold** [irontec/sngrep#218]
Thanks for a great tool.

Some B2BUAs support inserting the Call-ID from the A-Leg into the B-Leg in a custom header, so they can then be correlated in a SIP trace.

It would be nice if sngrep could have this feature.

**Comment by Kaian** [comment]
Hi @marrold 

I think this is already implemented in sngrep. Just add X-Call-Id or X-CID header to B-leg and use extended call flow (default keybinding _x_)

The [FAQ](https://github.com/irontec/sngrep/wiki#frequent-asked-questions) mentions it (would be nice to have more entries).

Thanks for the feedback!!

**Comment by pavelanyri** [comment]
Hi
I have two call-legs 
A call-leg has call-id Call-ID: 2xli4ci3qv1xx51ubi3cwruqwvq2w4v1
B call-leg has 30 first caracters from A call-id 
Call-ID: 2xli4ci3qv1xx51ubi3cwruqwvq2w4_418115-3719789270-557056
Is it possible to correlate such calls? I cannot insert x-CID into outgoing message due to licence restriction

**Comment by Kaian** [comment]
Automatic correlation is only implemented using headers.
Other kind of dialog association must be done manual (selecting dialogs with space bar in the list)

You can change columns layout to display Call-ID column and use display filter to look for all dialogs starting with the same value. Or you can use filters screen to display all dialogs with part of the Call-ID in its initial message payload.

But it must be done manually.

**Comment by davemidd** [comment]
Not wishing to hijack the discussion, but is it possible to define the header name that the A leg call id is in?
Thanks.

**Comment by Kaian** [comment]
Right now B-Leg header name is hardcoded as part of the SIP payload parsing [regular expressions](https://github.com/irontec/sngrep/blob/master/src/sip.c#L173)

The supported values are X-Call-Id and X-CID (case insensitive).

I don't have any problem of adding new header names to the expression (let's say X-BLeg-Call-Id). Making those regular expressions configurable via sngreprc would require more time.

Regards!

**Comment by Kaian** [comment]
The header name on the B legs to look for A callid can now be configured using `sip.xcid` settings thanks to @linuxmaniac 

See PR for an example in configuration file!
