### ISSUE TITLE
Add support for any SDP configured stream

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#219]
SDP:
m=application 50468 UDP/BFCP *

**Comment by michael2009** [comment]
then maybe same issue for any  application 
example T38 fax

**Comment by Kaian** [comment]
Hi @michael2009 

The only supported streams are RTP.

Others streams like the ones you mentioned or even SRTP are not implemented at all.

Regards!

**Comment by michael2009** [comment]
Can support application type stream later ?

**Comment by Kaian** [comment]
We can keep this as a feature request, but currently we're only implementing bugfixes in 1.x so it may take some time until this is implemented.

Thanks for the suggestion!

**Comment by michael2009** [comment]
--- sngrep-1.4.5/src/sip.c      2018-10-10 23:45:52.000000000 +0800
+++ sngrep-1.4.5.1/src/sip.c    2018-10-17 21:28:59.562597998 +0800
@@ -668,7 +668,7 @@
     while ((line = strsep(&payload2, "\r\n")) != NULL) {
         // Check if we have a media string
         if (!strncmp(line, "m=", 2)) {
-            if (sscanf(line, "m=%s %hu RTP/%*s %u", media_type, &dst.port, &media_fmt_pref) == 3) {
+            if (sscanf(line, "m=%s %hu RTP/%*s %u", media_type, &dst.port, &media_fmt_pref) == 3 || sscanf(line, "m=%s %hu UDP/TLS/RTP/%*s %u", media_type, &dst.port, &media_fmt_pref) == 3) {

                 // Add streams from previous 'm=' line to the call
                 ADD_STREAM(msg_rtp_stream);

**Comment by michael2009** [comment]
UDP type for DTLS or UDP/BFCP

**Comment by Kaian** [comment]
I have added this to the next release, I don't think this is a final solution but makes no harm as far as I can tell!

Thanks @michael2009 !!
