### ISSUE TITLE
Output broken in 80-column terminal

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#22]
I'm at f8d78a74a2e17 in branch fix_monochrome.

I launch xterm in default geometry (80x24), and then F10, and select "SIP From", "SIP To", and "Time", and deselect all other columns.

sngrep displays only Sip From correctly. The second column has number "1", then space, then time. If deselect "Time", there's still "1" in the second column (time disappears).

**Comment by Kaian** [comment]
Confirmed.

I think the column width for SIP To is being set to 1, so only the first character of the column is displayed. 

Thanks for reporting!

**Comment by Kaian** [comment]
I think now is fixed fix_monochrome.

Also changed the default width for SIP From and SIP To to 30, so your column combination should fit into 80 columns (selectbox+30+30+8).

Also fixed _the destiny_ :angel: translation

**Comment by Kaian** [comment]
_The crash when selecting too many columns still exists._

Now fixed in e850c6084ce5dbceb701f95cfbe3fa02bdf2d3c2

**Comment by ssinyagin** [comment]
By the way, here's my dialer that I used for tests. Glad if you find it
useful.
https://github.com/voxserv/freeswitch-perf-dialer

**Comment by Kaian** [comment]
I'm not a voip engineer, just a developer that designs tools for my co-workers. Its quite rare that I use sngrep for actually debugging  :D
 
They may find it useful but I think they work more with asterisk than freeswitch.

Tomorrow I will merge fix_monochrome branch into master and update the release tag.
One again, thanks a lot for the testing and feedback.

**Comment by ssinyagin** [comment]
the fix works fine now, thanks.
That call generator sends SIP calls wherever you tell it to do, so the other end can also be an asterisk host. But in general, I prefer FreeSWITCH over Asterisk -- it makes many things much easier.
