### ISSUE TITLE
sngrep cannot parse NFLOG interface

### ISSUE THREAD

**Issue by uazham** [irontec/sngrep#222]
sngrep cannot parse pcap file if the pcap file contains "Linux Netfilter NFLOG" instead on "Ethernet II" in the packet details
Error:
Unable to handle linktype 239

**Comment by Kaian** [comment]
Hi @uazham 

Can you send me a pcap with a sip dialog? I'll check if is easy to implement. 

Thanks!

**Comment by uazham** [comment]
pcap was sent to email from your profile
Thank you.

**Comment by Kaian** [comment]
Hi @uazham 

Thanks for the PCAP, it helps a lot :)

NFLOG headers are variable so this is not as easy as skipping N bytes of the package. Those headers mut be parsed to know the actual Link layer size of the packet in order to skip them properly. I'll try to implement it as soon as I have some spare time.

Thanks!

**Comment by Kaian** [comment]
Hi @uazham 

Taking a look into wireshak code I have implemented a simple loop to skip NFLOG headers.

With the above commit applied, I was able to display the dialog from the pcap you sent me. This change will only affect to NFLOG linktypes so I've not tested enough if it works for every scenarios.

If you can, give it a try in your enviroment. Any feedback is highly appreciated.

Regards!

**Comment by uazham** [comment]
Hello!

Thank you very much!
It is working now. Tested on 3MB pcap files.
Will you make the new build of binaries (http://packages.irontec.com/centos/$releasever/$basearch/)?

**Comment by Kaian** [comment]
Binary packages are only done when release has been completed. 

This will be included in 1.4.5 that we'll try to release before the end of the year. Right now we only have a couple of commits from 1.4.4 so I will wait a bit more to fix other pending bugs.

Thanks for the testing @uazham !!

**Comment by uazham** [comment]
I have tried to compile on Centos 7 but have an error
configure: error:  You need to have libpcap installed to compile sngrep.

But libpcap is installed
Package 14:libpcap-1.5.3-9.el7.x86_64 already installed and latest version

**Comment by Kaian** [comment]
You need the development version of the packages installed (the ones ending with _-devel_)
They contain the header files (*.h)  required to compile the software. 

You can find a list of required build depdendencies in the wiki 

https://github.com/irontec/sngrep/wiki/Building#centosfedora

**Comment by uazham** [comment]
Ah, sorry, yes I already found.
Tested on Centos 7 too - it works
Thank you!

**Comment by Kaian** [comment]
You welcome!

I'm closing then. Feel free to reopen if you find anything crashing :)
