### ISSUE TITLE
RTP and signalling packets reordering

### ISSUE THREAD

**Issue by sergey-safarov** [irontec/sngrep#234]
I captured PCAP file using `dumpcap` utility and I then want find and save one call to dedicated file.
When call is saved, then RTP and signalling packets is reordered.
To reproduce please:
1. open file `original.pcapng` in attached archive;
2. mark call;
3. save using `F2` key;
4. open saved file in wireshark;
5. check that first RTP packed goes after BYE message.

Example of saved file also attached in archive.

[pcap.zip](https://github.com/irontec/sngrep/files/1743644/pcap.zip)

**Comment by Kaian** [comment]
Hi @sergey-safarov 

Thanks for reporting and the test files. According to the save logic code, the intention is to [sort saved packets based on packet time](https://github.com/irontec/sngrep/blob/master/src/curses/ui_save.c#L520). 

As you mention, this seems not be working as expected, and the sorter function is not doing anything at all, so I'll try to debug as soon as I can. 

Regards!

**Comment by Kaian** [comment]
Hi

I have updated all the sorter functions to actually do something :sweat_smile: 

Now packets should be saved in the captured order.

This also fixes a bug where displaying multiple dialogs flows at the same time was being affected  by the order they were selected in the call list with spacebar. 

If you have the time to test the latest master changes, it would help a lot.

Thanks for reporting!

**Comment by sergey-safarov** [comment]
Hello @Kaian 
I tested current master and looks like issue is fixed.
Packer ordering is correct and time stamp of original packet is preserved.
