### ISSUE TITLE
sngrep does not build on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by mnhauke** [irontec/sngrep#239]
sngrep does not build on openSUSE Tumbleweed.

```
[   38s] gcc -DHAVE_CONFIG_H -I.    -I/usr/include/p11-kit-1   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -D_GNU_SOURCE -I/usr/include/ncurses5/ncursesw -I/usr/include/ncurses5 -c -o curses/sngrep-ui_column_select.o `test -f 'curses/ui_column_select.c' || echo './'`curses/ui_column_select.c
[   38s] curses/ui_column_select.c: In function 'column_select_move_item':
[   38s] curses/ui_column_select.c:473:26: error: dereferencing pointer to incomplete type 'ITEM {aka struct tagITEM}'
[   38s]      info->items[item_pos]->index = item_pos;
[   38s]                           ^~
[   38s] make[2]: *** [Makefile:957: curses/sngrep-ui_column_select.o] Error 1
[   38s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/sngrep-1.4.5/src'
```

Tumbleweed uses a recent version of ncurses (6.1-20180224)
https://build.opensuse.org/package/show/openSUSE:Factory/ncurses

Here's the full buildlog:
[sngrep-failed-build-openSUSE_Tumbleweed-x86_64-full-buildlog.txt](https://github.com/irontec/sngrep/files/1864584/sngrep-failed-build-openSUSE_Tumbleweed-x86_64-full-buildlog.txt)
https://build.opensuse.org/package/live_build_log/home:mnhauke/sngrep/openSUSE_Tumbleweed/x86_64

**Comment by Kaian** [comment]
Hi @mnhauke 

I've been trying this in opensuse/tumbleweed docker container.

It seems the ncurses5-devel version of this release is actually ncurses6-devel with OPAQUE ncurses sctructures (the header files are symlinks to ncurses6).

If I remove the three problematic lines that use internal structure fields no longer available, I also find some linking problems: while the header files for ncurses5 are actually ncurses6, there is a libncursesw.so.5.9 library in the system. Not sure if ncurses6 headers can be used for libncursesw5 library but I get undefined reference errors.

Anyway I will focus on making this work for ncurses6, updating the code to properly use those structures and also some other fixes related to max screen dimensions. This may take a while.

Thanks for reporting!

**Comment by Kaian** [comment]
The above commit removes the usage of ITEM struct fields so it should be compatible with libncurses version compiled with `--enable-opaque-menu`, `--enable-opaque-form`, and so on.

I have tested this with libncurses5 using the configuration from your logs 
`
CFLAGS='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -D_GNU_SOURCE -I/usr/include/ncurses5/ncursesw -I/usr/include/ncurses5'
`

And configuration script:
`./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/lib --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --with-gnutls --with-pcre --enable-ipv6 --enable-eep --enable-unicode`

This generates undefined errors
```CE -I/usr/include/ncurses5/ncursesw -I/usr/include/ncurses5   -o sngrep sngrep-capture.o sngrep-capture_eep.o sngrep-capture_gnutls.o  sngrep-address.o sngrep-packet.o sngrep-sip.o sngrep-sip_call.o sngrep-sip_msg.o sngrep-sip_attr.o sngrep-main.o sngrep-option.o sngrep-group.o sngrep-filter.o sngrep-keybinding.o sngrep-media.o sngrep-setting.o sngrep-rtp.o sngrep-util.o sngrep-hash.o sngrep-vector.o curses/sngrep-ui_panel.o curses/sngrep-scrollbar.o curses/sngrep-ui_manager.o curses/sngrep-ui_call_list.o curses/sngrep-ui_call_flow.o curses/sngrep-ui_call_raw.o curses/sngrep-ui_stats.o curses/sngrep-ui_filter.o curses/sngrep-ui_save.o curses/sngrep-ui_msg_diff.o curses/sngrep-ui_column_select.o curses/sngrep-ui_settings.o -lgnutls -L/usr/lib64 -lgcrypt -ldl -lgpg-error  -lpcre -lmenuw -lformw -lpanelw -L/usr/lib64/ncurses5 -lncursesw -ltinfo -lpcap -lpthread  
curses/sngrep-ui_panel.o: In function `ui_panel_create':
/usr/src/sngrep/src/curses/ui_panel.c:165: undefined reference to `LINES'
/usr/src/sngrep/src/curses/ui_panel.c:166: undefined reference to `COLS'
curses/sngrep-scrollbar.o: In function `ui_scrollbar_draw':
/usr/src/sngrep/src/curses/scrollbar.c:70: undefined reference to `acs_map'
/usr/src/sngrep/src/curses/scrollbar.c:59: undefined reference to `acs_map'
```

Looks like it's finding the ncurses library first in `-L/usr/lib64/ ignoring the `-L/usr/lib64/ncurses5`, disabling the gnutls support actually removes the first library path and compiles properly.

This code should also compile for libncurses6, so you can switch to ncurses-devel if you prefer. 
While testing the generated binaries, the output is a bit glitchy, popups without borders and bad window refreshing. I have also experienced this with the other ncurses programs (like htop) in the same environment. 

Regards

**Comment by mnhauke** [comment]
Thanks for the patch!
It's building fine now on openSUSE Tumbleweed with ncurses5.
