### ISSUE TITLE
Ability to set a username filter from command line arguments?

### ISSUE THREAD

**Issue by giggsey** [irontec/sngrep#24]
Is it possible to set up the filters before I launch the program (as arguments).

I'm trying to use sngrep on a heavy traffic server, and it just fills the screen too quickly if I launch it.

**Comment by Kaian** [comment]
Hi @giggsey!

No, right now. As a workaround, you can specify a default initial display filter (just matches text in first screen rows) setting this option in `~/sngreprc`

      set cl.filter text_to_filter

Anyway, It won't be hard to implement a -F argument to do the same from command line, so I'll give it a try.

**Comment by Kaian** [comment]
Implemented a -F command line option to set initial display filter in `filter_arg`  branch.
Remember you can also use bpf filters for host, ports, etc

**Comment by Kaian** [comment]
I'm not sure If -F option will help with your problem.

There are several more options that you could do. For example, you could start sngrep, pause its capture thread using `p`, clear the screen pressing `F5` and set whatever filter you want, then resume the capture.

I'm also considering implement a command line option to match message payload (like ngrep does with its match expresion argument).

If you could describe a bit more your problem maybe we can find the best approach.

**Comment by giggsey** [comment]
Okay, so at the moment, we use ngrep a lot, and we most commonly filter by sip username or IP/Port. For example, we will execute `ngrep -qt -d any -W byline 200010050 port 5060`.

However, we do like the look of sngrep, and would like to move to it. But as our SIP servers are handling a lot of traffic, launching sngrep and applying a filter is a PITA. We would like to be able to do something similar to our ngrep command above, and start sngrep straight away filtering.

**Comment by Kaian** [comment]
Then I think the perfect enhancement will be to implement the ability to  handle *match expresion* like ngrep does (200010050 is actually a ngrep match expresion):

    usage: ngrep [ .. other options.. ] <match expression> <bpf filter>

That's also something other people has requested me, so I'll try to implement it whenever I can.

**Comment by Kaian** [comment]
Ok, I implemented a very very simple first approach in match_expression branch.
It's experimental, so beware of crashes.

This first implementation just checks the given <match expression> is part of message payload. It would be nice to make it a regexp, and much better, a pcre regular expresion.

This change requires some testing.

**Comment by Kaian** [comment]
Since 3b0c9ca in `match_expression` branch, the given expression can be a POSIX extended expression.

This keeps previous functionality and also allows more flexible matching. Also added two flags: `-i` for case insensitive matching and `-v` for reverse matching (like ngrep does).


For example this line will capture all dialogs with invites and registers in port 5060

    sngrep -i "cseq [0-9]+ (invite|register)" port 5060

**Comment by Kaian** [comment]
Hi  @giggsey 

  If you have time for testing `match_expression` branch to see if it fixes your needs. it will be appreciated.
  You can download it [here](https://github.com/irontec/sngrep/archive/match_expression.zip)

Thanks!

**Comment by giggsey** [comment]
Thanks, I will do.

Our internal developer who requested this is away this week, so I might not
have any feedback until next week.

**Comment by Kaian** [comment]
Hi @giggsey 

After some testing, match expression is now part of `master`, and I think it works as ngrep does.
If you feel this changes doesn't fit your needs or they are buged, feel free to reopen or comment.

Thanks a lot for the feedback :)
