### ISSUE TITLE
How to use sngrep in background mode with rotate output .pcap files?

### ISSUE THREAD

**Issue by akolomyts** [irontec/sngrep#247]
How to use sngrep in background mode with rotate output .pcap files?

thx

**Comment by Kaian** [comment]
Hi @akolomyts 

sngrep can not save output to multiple files. Rotate just remove oldest dialogs from memory when configured limit is reached.

As far as I know, that feature is already present in *tcpdump* so I recommend using it for background captures.

Regards!

**Comment by akolomyts** [comment]
Thank you very macth

**Comment by Kaian** [comment]
You welcome!
