### ISSUE TITLE
Don'nt show callflow line with ood INFO 

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#249]
Don'nt show callflow line with ood INFO

**Comment by Kaian** [comment]
Hi @michael2009 

Do you have a pcap to reproduce this problem?

Thanks as always for reporting!

**Comment by michael2009** [comment]
[ood_info.zip](https://github.com/irontec/sngrep/files/2136889/ood_info.zip)

**Comment by michael2009** [comment]
Get same issue with ood REFER .

**Comment by Kaian** [comment]
Hi @michael2009 could you try the above commit adding this setting to your sngreprc file?

```
echo set filter.methods REGISTER,INVITE,SUBSCRIBE,NOTIFY,OPTIONS,PUBLISH,MESSAGE,INFO,REFER > ~/.sngreprc
```

Thanks for reporting!

**Comment by michael2009** [comment]
I had checked ,woking fine.  Then must enable with rc file ?  It's best add to F7 settings list .

**Comment by Kaian** [comment]
I will add them to the filter screen you mention, but before I wanted to check if that was the problem you mentioned.

The commit is just a line, and updating the screen is much more change.

Thanks for the testing!

**Comment by Kaian** [comment]
Above commit should add three new checkboxes in the filters screen you mentions (when pressing F7)

This should fix this issue!

**Comment by michael2009** [comment]
Yes , fixed!
