### ISSUE TITLE
sngrep exit delay 

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#251]
first ethX up, but no cable
sngrep -d ethX  then exit delay or never exit

**Comment by michael2009** [comment]
Can solve ?

**Comment by michael2009** [comment]
ip link add dummy0 type dummy
ip link set dev dummy0  up mtu 65536

Exit delay or nerver exit.  if sngrep -d dummy0

**Comment by Kaian** [comment]
I will try this as soon as I can. 

Thanks for the commands to test this, its more handy that plugging and unplugging cables 😀

**Comment by Kaian** [comment]
This problem should be fixed with the above commit. Now, instead of waiting to capturing threads to finish, we cancel them.

More info can be found in [this thread](http://seclists.org/tcpdump/2006/q2/135) and [pcap_breakloop man page](https://www.tcpdump.org/manpages/pcap_breakloop.3pcap.html)

> Note also that, in a multi-threaded application, if one thread is blocked in pcap_dispatch(), pcap_loop(), pcap_next(3PCAP), or pcap_next_ex(3PCAP), a call to pcap_breakloop() in a different thread will not unblock that thread. You will need to use whatever mechanism the OS provides for breaking a thread out of blocking calls in order to unblock the thread, such as thread cancellation or thread signalling in systems that support POSIX threads

**Comment by michael2009** [comment]
Fixed. Good!!
