### ISSUE TITLE
IDX wrong when calls more 10000 count

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#252]
![xxx](https://user-images.githubusercontent.com/12387494/43047550-3b9f9be4-8dc8-11e8-8566-fbc2b14cdeb5.jpg)

IDX wrong when calls more 10000 count

**Comment by Kaian** [comment]
Hi @michael2009 

Call list columns has fixed width that can be configured in sngreprc file. If you plan to display too many dialogs, consider increasing the first column width.

```
echo 'set cl.column0.width 5' >> ~/.sngreprc
```

Regards!
