### ISSUE TITLE
sngrep crash when exit

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#253]
sngrep crash when exit
[crash.zip](https://github.com/irontec/sngrep/files/2217163/crash.zip)

**Comment by Kaian** [comment]
Hi @michael2009 

From the backtrace I see you are receiving a HEP packet while closing.

Does this problem also reproduce when HEP listen mode is not enabled?

Thanks for the info!

**Comment by michael2009** [comment]
[crash.zip](https://github.com/irontec/sngrep/files/2223380/crash.zip)
New test without HEP listen.

**Comment by Kaian** [comment]
I have updated the changes we did for #251 to wait for cancelled capture threads.

If you can test if this fixes the problem, it would be great.

Thanks @michael2009 !

**Comment by michael2009** [comment]
Fixed! Thanks!!!

**Comment by michael2009** [comment]
Still exit issue if with HEP traffic.
