### ISSUE TITLE
Request, not an issue.

### ISSUE THREAD

**Issue by davidcsi** [irontec/sngrep#258]
Hello guys!

It would be amazing if the display window could scroll-down automatically.

Thanks!

**Comment by Kaian** [comment]
Hi @davidcsi 

If you mean the call list (the first screen displayed) you can press 'A' keybinding to autoscroll. Autoscroll will stop if you move manually the selected row.

Regards!

**Comment by davidcsi** [comment]
Yep! just discovered that looking into the source code, that's really nice!
Maybe that binding should be added to the readme :)

Thanks!

**Comment by Kaian** [comment]
We could add it to the help screen for call list (displayed pressing h)

You can also bind it to another key in your sngreprc file. Check `sngrep -D` for a list of configurable settings and keybindings.

Regards!!
