### ISSUE TITLE
display via mosh

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#26]
Sometime when I have to deal with slow connections (e.g, 3G), I am using mosh instead of ssh:

  * https://mosh.mit.edu

mosh is forcing the locales to UTF-8 and that might be the reason sngrep is no longer displaying the graphics as usual. For example, the arrow for signaling diagram is like:
```
x qqqqqqqqqqqqqqqqqqqqqqqqqq> x
```
Otherwise, the settings are the same -- I connect with ssh from same terminal app to same server and all ok, using mosh instead of ssh breaks the graphics.

The output is still usable, just wanted to point it here in case there is something easy to fix. mosh is available on most of linux distros by now, reuses ssh for authentication, has clients for mobile, so might be good to have sngrep working properly, if not a big investment -- I consider this more as an enhancement than a bug now.

**Comment by Kaian** [comment]
Hi @miconda!

Thanks for reporting.! There was a similar problem using putty with the default configuration (#8) that could be solved changing remote character encoding. I also found some encoding problems using sngrep inside screen or tmux.

I'll do some digging if there is an easy solution without linking to ncursesw (wide-character version of ncurses library).

**Comment by miconda** [comment]
The link in #8 seems no longer available. However, mosh is working with LOCALE set to UTF8 only and they make that clear on their project.

**Comment by Kaian** [comment]
After some tests, it seems impossible to do without linking against ncursesw, which seems to be available in most distributions. If you have time, give it a try to `wide_chars` branch.

I've tested with mosh 1.2.4 and seems to work fine. If your mosh is older, be sure to `export NCURSES_NO_UTF8_ACS=1` environment variable that makes those borders be drawn using unicode characters.

I'm not sure if making this the default behaviour or enable it as a configure flag.

Thanks for the feedback!

**Comment by Kaian** [comment]
I have added an option to configure. To enable ncurse unicode support, please configure using `--enable-unicode` flag.

I have also added a configurable feature summay at the end of the script.

```
kaian@kaian $ ./configure --enable-unicode

configure: 
configure: sngrep configure finished                            	
configure: ====================================================== 	
configure: OpenSSL Support		: yes  						
configure: Unicode Support		: yes  						
configure: ====================================================== 	
configure: 
```

**Comment by miconda** [comment]
It works with the branch wide_chars. As a note, I had to disconnect and connect again with mosh, I tried to use new compiled version with an existing connection and was showing the old format.

I guess you are going to merge to master at your convenience, so I am closing this item.

Many thanks for working on it.

**Comment by Kaian** [comment]
If the old format is displayed, be sure the NCURSES_NO_UTF8_ACS enviroment variable is set to 1.

In mosh 1.2.4 its done by default when you connect, but previous versions require to export it manually (or place it in any system environment file).

Another workaround is creating an alias like 

    alias sngrep='NCURSES_NO_UTF8_ACS=1 sngrep'


I could export it in sngrep source, but I'm not sure if it's always the right thing to do.

Thanks for the testing :)

**Comment by miconda** [comment]
I have mosh 1.2.4 on client and 1.1.3 on server (ubuntu 12.04, I just installed it from distro, not bothering for putting a newer version from sources or other repos).

Disconnecting a rather old mosh connection was not a problem for me to get it working.

As I had another old connection to the host, I tried with NCURSES_NO_UTF8_ACS=1 and still no good graphics. Anyhow, I won't bother looking further at this particular situation, it is waste of time.

**Comment by miconda** [comment]
Not sure why, but the latest master is still showing broken graphics over mosh, although compiled with './configure --enable-unicode' . Previous branch was deleted and I removed my local copy as well.  I tried also with NCURSES_NO_UTF8_ACS=1.

Wondering if for you the master is working fine over mosh...

**Comment by Kaian** [comment]
Umm... I have tested master through mosh 1.2.4 with NCURSES_NO_UTF8_ACS enabled without problem. 

Is `ldd $(which sngrep)` showing libncursesw linkage?

I'm also thinking about adding compiled features in `sngrep --version`

**Comment by Kaian** [comment]
Also, the last commit of `wide_chars` branch was:

`git reset --hard 930b07eb71b337e038e6d995c8fa39465c406ea3`

In case you want to test.

**Comment by miconda** [comment]
Got the pattern of the issue -- if I open the pcap as the user I connect over mosh, it is working fine. But if I do 'sudo su' (to switch to root) after connecting via mosh, then it is showing old broken style. Could be some setting that have to be propagated for root. I will investigate more ...

**Comment by Kaian** [comment]
Have you tried to see if variable NCURSES_NO_UTF8_ACS is exported to the new shell after sudo?
`echo $NCURSES_NO_UTF8_ACS`.

Mosh code is:
```
 /* ask ncurses to send UTF-8 instead of ISO 2022 for line-drawing chars */
    if ( setenv( "NCURSES_NO_UTF8_ACS", "1", true ) < 0 ) {
      perror( "setenv" );
      exit( 1 );
    }
```

I'm not sure if its the same as `export NCURSES_NO_UTF8_ACS=1`

**Comment by miconda** [comment]
Printing the variable $NCURSES_NO_UTF8_ACS after sudo showed it empty. I exported it with value 1, still not proper graphics... anyhow, I guess I need to read a bit more on those LOCALE settings with mosh.

**Comment by Kaian** [comment]
Ummm.. quite strange, I followed the steps you provided to reproduce the problem with good results.

* connect via mosh as user: NCURSES_NO_UTF8_ACS set to 1 by mosh -> sngrep looks ok
* sudo su -> NCURSES_NO_UTF8_ACS not set -> sngrep looks bad
* export NCURSES_NO_UTF8_ACS=1 -> sngrep looks ok again

I must be missing something.

**Comment by caasi** [comment]
@miconda:

Just realized that one can set `SETENV:` in the `/etc/sudoers` file and `sudo -E` to [preserve environment variables](https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo). It fixed my problem.
