### ISSUE TITLE
Add support for realtime input

### ISSUE THREAD

**Issue by korden32** [irontec/sngrep#260]
I'm currently experiencing same issues described in #246 , even "port 5060" doesn't show up all packets (~300+ concurrent calls).

I'm thinking about things like `tcpdump -U -w - port 5060 | sngrep -I -`  then play with buffering parameters on tcpdump side.

From what I can see, `-I` option only accepts files and not a pipe. Is it possible to add realtime capture from given input (STDIN, named pipe, etc), not just from net device?

**Comment by Kaian** [comment]
Hi @korden32 

This was actually implemented in [1.4.4](https://github.com/irontec/sngrep/releases/tag/v1.4.4) requested in #198


Testing with the sample pcap also seems to work.

kaian@kaian ~/projects/sngrep $  cat tests/aaa.pcap | sngrep -I - -N
Dialog count: 6

**Comment by korden32** [comment]
Hmm... Now testing on local machine (Ubuntu 16.04, sngrep 1.4.5 binaries from packages.irontec.com):
```
~# tcpdump -c 500 -w test.pcap
...
~# tcpdump -r test.pcap | grep SIP | wc -l
reading from file test.pcap, link-type EN10MB (Ethernet)
16
~# sngrep -I test.pcap -N
Dialog count: 3
```

But doing `cat test.pcap | sngrep -I - -N` (with or without `-N`) just hangs the console until SIGINT

**Comment by Kaian** [comment]
The above commit should do the trick for both reading pcap data from stdin and keystrokes for the tests.

If you have the chance to test if it works it would be great.

Thanks!

**Comment by korden32** [comment]
Now it works, thanks
