### ISSUE TITLE
sngrep-1.4.6: error: assignment of read-only variable 'stdin'

### ISSUE THREAD

**Issue by micmac1** [irontec/sngrep#261]
Hi all,

The new release doesn't compile here. This is on OpenWrt 18.06 with gcc 7.3.0.

configure: ====================================================== 	
configure: GnuTLS Support               : no		
configure: OpenSSL Support              : yes 			
configure: Unicode Support              : yes  		
configure: Perl Expressions Support     : yes              
configure: IPv6 Support                 : yes               
configure: EEP Support                  : yes               
configure: ======================================================

It dies pretty much in the beginning:

```
make[5]: Entering directory '/home/sk/tmp/sdk/openwrt-sdk-18.06.0-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/sngrep-1.4.6/src'
  CC       sngrep-capture.o
capture.c: In function 'capture_offline':
capture.c:194:21: error: assignment of read-only variable 'stdin'
         if (!(stdin = freopen("/dev/tty", "r", stdin))) {
                     ^
make[5]: *** [Makefile:519: sngrep-capture.o] Error 1
```

The previous release compiles fine. But I understand there have been some slight changes to capture.c.

I'm not big into programming, but it looks like there is a simple typo.

`if (!(stdin = freopen("/dev/tty", "r", stdin))) {`

should be

`if (!(fstdin = freopen("/dev/tty", "r", stdin))) {`

With this change sngrep compiles. Haven't run-tested it yet.

Could this be it? I'll raise a PR just in case.

Regards,
Seb

**Comment by Kaian** [comment]
Yep, this was a mistake while fixing #260 

I didn't get any warning in gcc but your PR has the intended code (although fstdin var is not used, is set to silent another compiler warning _sigh_)

Thanks!
