### ISSUE TITLE
add support to IP over IP capture layer

### ISSUE THREAD

**Issue by facalvino** [irontec/sngrep#264]
Hola Ivan!

Como estas? instale SNGREP en Centos 7. Al día de hoy y después de varios intentos no puedo lograr que me muestre paquetes SIP.
Primero creí que era algún problema de virtualizacion, pero luego de instalar Centos7 en un server como SO principal y único lo descarte.
Tengo un server que envía muchísima cantidad de señalizacion hacia mi SNGREP server pero no logro verlos, si hago un TCPDUMP veo que los paquetes y la señalizacion llegan a la IF del server.
Se te ocurre que puede estar sucediendo o que podría configurar? descarte problemas de conectividad, de configuración de red en el server, desactive el firewall. Hice DE TODO, lo mismo me ocurrió intentando implementar HOMER.
Si precisas de algún dato particular me lo haces saber.
Que tengas un buen día!!

Abrazo!

**Comment by Kaian** [comment]
Hola @facalvino !

¿Sabes si es un problema relacionado con la última versión o nunca te funcionó? 
¿Has probado ha realizar una captura en un PCAP con tcpdump y abrirlo con sngrep a ver si ve los dialogos?
¿Estas enviando información empleando HEP o directamente capturando desde el interfaz?

Un saludo!
----

Hi @facalvino 

Do you know if the problem is realted to the latest version or it never worked?
Did you try to capture with tcpdump into a PCAP file and open it with sngrep to check if you can see any dialogs?
Are you sending information using HEP or directly capturing from the network inteface?

Regards!

**Comment by facalvino** [comment]
Hi Kaian!!

The SNGREP never worked for me, When I start the program "Dialogs" appears
and ever stay in "0".
I´ve also tried to make a capture saving the data to a PCAP using the
funcionality of SNGREP but it didn´t work.
If I make a TCPDUMP on the interface I´m able to see all the SIP (not using
SNGREP, just a Linux TCMPDUM).
I´ve desactivated SELINUX, FIREWALL and nothing happens, I´m lost.
My objective in first place is have fully functional SNGREP and see how it
works, and if everything goes ok try to send HEP to HOMER.

Regards,

Facundo

**Comment by Kaian** [comment]
That's pretty strange. Are you sure what you see with tcpdump is SIP and not HEP (which also has SIP in the package and may look like SIP)?

Can you send me an small pcap file with a capture done with tpcdump so I can check what's wrong?

Thanks!!!

**Comment by facalvino** [comment]
I´ve tried executing:

*sngrep -d em2 -O /tmp/sip_capture2.pcap port 5060* -> empty PCAP attached.

I´ve also tried with "*sngrep port 5060*" and saving with "s" the file and
is also empty.

[image: image.png]

I´m lost...

Thanks for your help!

**Comment by Kaian** [comment]
HI @facalvino 

Capture a small pcap **with tcpdump** only port 5060 and send me to my email, I'll check it

```sudo /usr/sbin/tcpdump -i em2 -s 0 -w /tmp/Capture.pcap port 5060```

and send it to kaian@irontec.com

Thanks!

**Comment by Kaian** [comment]
After debugging sample data we discover this is a problem related to IPIP extra heders

https://en.wikipedia.org/wiki/IP_in_IP

sngrep does not support IP over IP

**Comment by kevin-olbrich** [comment]
I have met a similar problem on debian stretch. Sngrep shows nothing for the interface (sngrep -i eth0).
It works with "tcpdump -i eth0 -w foo.pcap" and "sngrep -I foo.pcap". Seems like the official build is broken.

**Comment by Kaian** [comment]
This is a bit different, because the data that @facalvino generated with tcpdump wasn't displayed at all (because capture data has headers not supported in sngrep).

I'll change the issue title to reflect the actual problem.

**Comment by alaertegv** [comment]
Hi, I have similar problem, what I did to try to get it work partially is using tool called "stripe" (https://github.com/theclam/stripe) after capture with tcpdump. Then use sngrep -I over the file which stripe removed the headers. But it is instable, lots of time I get "Segmentation fault (core dumped)" and sngrep closes.

**Comment by Kaian** [comment]
This should be possible in 1.5.0 thanks to above pull request.

Thanks!
