### ISSUE TITLE
I can't install Sngrep on CentOS 5.10.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#27]
Hi everybody,

When I execute "./bootstrap.sh" It gives me the following error:

------------------
[root@pbx sngrep]# ./bootstrap.sh
Generating the configure script …
aclocal:configure.ac:4: warning: macro `AM_SILENT_RULES’ not found in library
configure.ac:4: error: possibly undefined macro: AM_SILENT_RULES
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
[root@pbx sngrep]#
------------------

I have CentOS 5.10 / 64.

Is this a bug?

Best regards,

Ramses

**Comment by ramses-0000** [comment]
Hi,

I am trying to install it in a Elastix 2.4.0.2 / 64bits.


Regards,

Ramses

**Comment by Kaian** [comment]
Hi Ramses,

I think the problem is your automake version is a bit old. The default configure template is designed for automake 1.10 while yours is probably 1.9.

As a workaround, you can adapt your the `configure.ac` script with [this patch](https://gist.githubusercontent.com/Kaian/fcd1413a3eae9c5de87f/raw/7f73dafc516350586d7b99197509f7eb91d5f97f/automake-1.9.6.diff) (you could also make the changes manually, it's only three lines)

    cd sngrep
    patch -p0 < automake_1.9.6.diff
    ./bootstrap.sh
    ./configure --disable-openssl 
    make && make install

**Comment by ramses-0000** [comment]
Hi Kaian,

The automake version is 1.9.6-3.

I have patched the "configure.ac" script and the "./bootstrap.sh" no give me the error.

First, I have needed install "ncurses-devel" and "libpcap-devel" to execute "./configure --disable-openssl" correctly.

Now, I have installed "sngrep" and working.

Summarizing, I have did this:

-------------------------------------------------------------------------------------
cd sngrep
wget https://gist.githubusercontent.com/Kaian/fcd1413a3eae9c5de87f/raw/7f73dafc516350586d7b99197509f7eb91d5f97f/automake-1.9.6.diff --no-check-certificate
patch -p0 < automake_1.9.6.diff
yum install ncurses-devel libpcap-devel
./bootstrap.sh
./configure --disable-openssl 
make && make install
sngrep -d any udp and port 5060 and host 192.168.0.100
-------------------------------------------------------------------------------------


Very thanks,

Ramses

**Comment by Kaian** [comment]
Yay! Nice, I'll try to update configure template to make it compatible with older automake version then.

Depencies for CentOS are in the wiki, sorry for not pointing there before 
https://github.com/irontec/sngrep/wiki/Building#centosfedora

**Comment by ramses-0000** [comment]
Ok

Very thanks,

Ramses
