### ISSUE TITLE
hep3 from heplify

### ISSUE THREAD

**Issue by gmaruzz** [irontec/sngrep#272]
hello Kaian,
thanks for this unrivaled tool!
I am unable to get sngrep visualize hep3 packets coming from heplify
(same sngrep visualize hep3 packets sent from another sngrep)

**Comment by Kaian** [comment]
Hi @gmaruzz 

Whe have updated how HEPv3 packets are parsed in the last commit, could you try a compiled sngrep from master and check if the problem persist?

Thanks!

**Comment by Kaian** [comment]
I'm closing this as it should work in current master. If not, feel free to reopen with new information.

Thanks!
