### ISSUE TITLE
X-CallId missing when portrange

### ISSUE THREAD

**Issue by gmaruzz** [irontec/sngrep#273]
Hello Kaian,
thanks again!!

If I start sngrep with a portrange 5060-5090, then it does not get the correlation Aleg/Bleg
If I start it without portrange, X-CallId and correlation is perfect (but the load is obviously much higher)

**Comment by Kaian** [comment]
Hi @gmaruzz 

With correlation you mean pressing _X_ keybinding so sngrep looks for the other X-Call-Id call?
Can you provide a pcap capture where correlation does not work?

Also beware: When using BPF filters with ports, libpcap may discard IP fragments. Port is in the UDP header that is only present in the first IP fragment, so the others _does not match_ the BPF filter. From sngrep point of view nothing can be done (we can only process what libpcap gives us), but I think there is a BPF filter that also considers IP fragments.

`sngrep portrange 5060-5090 or (ip[6:2] & 0x1fff) != 0`

If this is not the case, please ignore the above parragraph :-)

Regards!

**Comment by gmaruzz** [comment]
I see your comment just now. Works perfect, and solve the problem! Thank you!
