### ISSUE TITLE
Códigos Raros / Basura que entra al guardar la salida sobre un fichero.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#28]
Hola,

Cuando realizo una captura guardando el contenido en un fichero con la opción -O, además de las trazas me mete alguna basura de este tipo:

----------------------------------------------
*sëTÐ   XXÄ4k"óE`HRÅ@ÈÀšÈúÀšÈlÄÄ4þOPTIONS sip:4002@192.168.0.10:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.20:5060;branch=z9hG4bK126e75e5
Max-Forwards: 70
From: "Unknown" <sip:Unknown@192.168.0.20>;tag=as44d6986b
To: <sip:4002@192.168.0.10:5060>
Contact: <sip:Unknown@192.168.0.20:5060>
Call-ID: 4d5d255d3b2ad1b0748e24ec51b12b11@192.168.0.20:5060
CSeq: 102 OPTIONS
User-Agent: FPBX-2.11.0(11.7.0)
Date: Mon, 23 Feb 2015 18:36:26 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Supported: replaces, timer
Content-Length: 0

----------------------------------------------

Como vemos, delante del OPTIONS hay códigos raros...

¿Hay forma de que esa "basura" no quede reflejada en el fichero?

Saludos

**Comment by Kaian** [comment]
Buenas @ramses-0000 

Cómo estás abriendo el fichero capturado?

Al usar la opcion `-O` o usar la tecla de salvar en el listado de llamadas, la captura es guardada en formato `.pcap`

Estos ficheros contienen no solo el contenido del mensaje sino también cabeceras del paquete recibido.

Si quieres guardar un dialogo en modo texto, puedes [visualizarlo en texto](https://github.com/irontec/sngrep/wiki/CallRaw) y guardar solo ese diálogo en texto plano, presionando la `s` (el fichero sera .txt) mientras estás en esa pantalla.

Opcionalmente, puedes emplear herramientas para mostar el contenido de los paquetes capturados, como por ejemplo ngrep.

    ngrep -Wbyline -pqt -I fichero-capturado.pcap


Un saludo!

**Comment by ramses-0000** [comment]
Kaian, muchas gracias.

No sé por qué pensé que se guardaban en modo texto normal...

Por cierto, la opción "F2 - Save" no me funciona, cuando pulso F2 me sale un diálogo preguntando si realmente deseo salir.

Sin embargo, si pulso en la lista de llamadas "s", sí me pregunta por el nombre del fichero y esas cosas.


Saludos

**Comment by Kaian** [comment]
Hola @ramses-0000,

  Ese creo que es un problema de como traducen algunos emuladores los códigos de funciones. En principio _creo_ que no se puede hacer nada desde el lado de la aplicación (por eso todas las funciones tienen asociaciones también letras). 

  Si tienes otra aplicación basada en Ncurses, por ejemplo **htop**, podrías probar si el F1 funciona?

Saludos!

**Comment by ramses-0000** [comment]
Sí, uso el "mc" y me funcionan las teclas de función, y acabo de instalar el "htop" y también.

Saludos

**Comment by Kaian** [comment]
Pues entonces, si es posible hacer algo!
Te importaría abrir otra incidencia indicando el programa emulador de terminal que usas?

Gracias!
