### ISSUE TITLE
Get powerline working with sngrep in Centos 7

### ISSUE THREAD

**Issue by richilp** [irontec/sngrep#281]
Hello there !!

we've been unable to get powerline working with sngrep in Centos 7.
Powerline is ok in the shell but no way to have it working with sngrep.

Any ideas?

Thanks !!!

**Comment by Kaian** [comment]
Hi @richilp 

sngrep does not use powerline fonts at all! You must be having some problems related to ncurses and UTF-8 characters. This is something a locale or terminal emulation issue, 

Something like #236, #158, #36 or #26

Regards!

**Comment by richilp** [comment]
Hi Kaian,

spot on !!
Just added export NCURSES_NO_UTF8_ACS=1 to the .bashrc and now we can see the arrows instead of weird characters.

Thank you so much !!

**Comment by ruslanguns** [comment]
@richilp thank you!
