### ISSUE TITLE
Display name instead of IP on Call Flow Window

### ISSUE THREAD

**Issue by alaertegv** [irontec/sngrep#282]
[Showing IPv6 – how to show name instead.pdf](https://github.com/irontec/sngrep/files/3769398/Showing.IPv6.how.to.show.name.instead.pdf)
Hi, do you know if there is solution to display name instead of IP on the call flow windows? 

I tried to add names for IPv6 addresses in /etc/hosts but SNGREP keep showing IPv6 instead of the name.

Best Regards

**Comment by Kaian** [comment]
Hi @alaertegv 

Check configuration section in the project wiki. In this case, you can use [alias](https://github.com/irontec/sngrep/wiki/Configuration#alias) directive.

Be sure to enable display alias on configuration.

```
echo set displayalias on >> ~/.sngreprc
echo alias my_full_ipv6 my_host_nname >> ~/.sngreprc
```

Regards
