### ISSUE TITLE
Feature request, Debian Buster package

### ISSUE THREAD

**Issue by powerpbx** [irontec/sngrep#286]
It appears the Debian Stretch package works on Debian Buster for now. It would be nice to eventually have a separate Debian Buster package.

**Comment by Kaian** [comment]
Hi @powerpbx 

Buster packages for 1.4.6 should be now available in Irontec's Debian repository.

Thanks for reporting

**Comment by linuxmaniac** [comment]
oh no! No one is using the Official Debian then? :-/

**Comment by Kaian** [comment]
That's what I was actually thinking, because right now the available version in Irontec repositories is the same version that the one provided by debian...

**Comment by powerpbx** [comment]
The stretch repo version is older than irontec version.  I presume that will eventually happen with buster.
