### ISSUE TITLE
Function keys not work in the panel.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#29]
Hi,

When I push any function keys in the panel appears the question " Are you sure you want to quit?".

This occurs with any function key.

I have installed "mc" and "htop" and the function keys work well.

Thanks,

Ramses

**Comment by ramses-0000** [comment]
Hi,

I am working with Putty 0.63.

In the keyboard configuration of Putty (Terminal -> Keyboard) It appear selected "ESC[n~" by default.

If I change it and I configure "Xterm R6" or "VT100+" the function keys work fine.


Thanks,

Ramses

**Comment by Kaian** [comment]
Hi @ramses-0000,

 I've been reading htop sources and it seams they redefine some codes as function keys, so I have copied the codes to archieve the same behaviour.

It should be fixed in master.

Thanks for reporting!
