### ISSUE TITLE
Lines/columns not lining up properly

### ISSUE THREAD

**Issue by sdwru** [irontec/sngrep#290]
See attached screenshot.

This is on a CentOS v8 install.  I tried installing the binary from the CentOS v7 repository with those dependencies and I also tried compiling it myself from `master` branch using the CE8 versions of the dependencies.

![sngrep](https://user-images.githubusercontent.com/40401953/71648107-db1bf780-2cb4-11ea-8a73-85a73fe46628.png)

**Comment by Kaian** [comment]
Hi @sdwru 

This is a bug in your terminal emulator (Xterm, Konsole, Guake, etc). Ncurses library started to use an special character call REP to repeat the previous character that not all terminal emulators implemented. This problem has been around since a couple of months now, so It may be already fixed in newer versions.

https://invisible-island.net/ncurses/ncurses.faq.html#xterm_generic

> REP is used to indicate that the preceding character in the data stream, if it is a graphic character (represented by one or more bit combinations) including SPACE, is to be repeated n times, where n equals the value of Pn. If the character preceding REP is a control function or part of a control function, the effect of REP is not defined by this Standard.

> 
> ... in mid-2017, an update to the xterm terminal description added the ECMA-48 REP (repeat character) control. It was part of xterm since January 1997, but a terminal description using the feature was part of xterm only (not ncurses). After adding it to ncurses, it was observed that:
> 
> * rxvt is unaffected, since it does not use TERM=xterm.
> * mlterm and OSX Terminal supported REP, using TERM=xterm.
> * VTE, konsole, PuTTY, iTerm2 did not support this standard, longstanding feature, of xterm although they set TERM to xterm or xterm-256color.
> * screen and tmux use a different TERM setting, and seemed to work (although tmux had some other issue with the test).


Regards!

**Comment by sdwru** [comment]
Thanks for enlightening me.  It had not occurred to me to try update PuTTy.  That seems to have corrected it.
