### ISSUE TITLE
close call (dialog) for CANCEL, 487, ACK

### ISSUE THREAD

**Issue by gmaruzz** [irontec/sngrep#292]
outbound INVITE
inbound 100
inbound 180
outbound CANCEL
inbound 487
outbound ACK

still the dialog (call) is shown as IN CALL (forever)

**Comment by Kaian** [comment]
That's strange, according to the logic [here](https://github.com/irontec/sngrep/blob/master/src/sip_call.c#L218) when a CANCEL is received during CALLSETUP status, the calls enters CANCELLED state. From that state you can not progress to INCALL.

- What version of sngrep are you using?
- Can you provide a sample PCAP to reproduce this problem?

Thanks!

**Comment by gmaruzz** [comment]
mmmmh, I see is a complex sequence during an attended transfer in a complex topology...
I will see if I can reproduce and generate a pcap...
sngrep latest version
I close this ticket, I will reopen if I can provide pcap
