### ISSUE TITLE
Inbound SIP OPTIONS not being displayed

### ISSUE THREAD

**Issue by solarmon** [irontec/sngrep#294]
Hi,

Platform: CentOS Linux release 7.4.1708 (Core)
Version: sngrep-1.4.6-0.el7.x86_64

I use sngrep on a SIP server and it displays the SIP OPTIONS message going out from it OK. However, it does not seem to display the SIP OPTIONS messages going to it.

The SIP OPTIONS does get to it and gets processed by opensips - so it is not a infrastructure or firewall issues. A Wireshark capture on the other end shows the SIP OPTIONS packet being sent and being responded to. See attached capture.

What would be the scenario or circumstances that would prevent sngrep from display those particular SIP OPTIONS packets?

Thank you for such an awesome tool!

[SNGREP-MISSING-SIP-OPTIONS.zip](https://github.com/irontec/sngrep/files/4192938/SNGREP-MISSING-SIP-OPTIONS.zip)

**Comment by Kaian** [comment]
Hi @solarmon 

I think this a duplicate from #156 

It looks like the message in the zip attached (thanks for the test file btw) is not formatted according to the SIP RFC rules[1]. Every header should end with CRLF (0x0d0a).
Some software allow behavior, but sngrep doesn't as mentioned in #156

[1] https://tools.ietf.org/html/rfc3261

>   The start-line, each message-header line, and the empty line MUST be
   terminated by a carriage-return line-feed sequence (CRLF).  Note that
   the empty line MUST be present even if the message-body is not.

**Comment by solarmon** [comment]
@Kaian 

Thanks for the quick response and for referencing #156 

I now understand that sngrep does not display the inbound SIP OPTIONS if it is not formatted correctly (with a CRLF). However, what about the response to the SIP OPTIONS - the "503 Maintenance" message in the capture example?

Thank you.

**Comment by Kaian** [comment]
Hi @solarmon 

sngrep only displays a dialog if the first message is a Request, so you won't see a response displayed in the list (unless you disable sip.noincomplete setting)

In this case, 503 response message also has the same format problem. Status-Line ends with CRLF as expected, but Call-Id header ends with just CR. Same happens with CSeq, From and To headers, but Via and Content-Lenght ends with CRLF as expected.

Best regards!

**Comment by solarmon** [comment]
Hi @Kaian,

Thanks for the clarification.

It looks like our SIP server may just be passing back those certain headers as it has received them.

I will look at how we can resolve this non-conformance issue for the incoming SIP OPTIONS messages (the other ones, like INVITE, seem to be OK).

Thanks once again for your support. I will close this ticket now.
