### ISSUE TITLE
Installing on centos 8

### ISSUE THREAD

**Issue by utrumo** [irontec/sngrep#295]
How can i install it on centos 8?

**Comment by Kaian** [comment]
Hi @utrumo 

We use _mock_ to build CentOS rpms and I wasn't able to make it work for Centos 8 yet, so there are no Irontec repositories for that version. 

I'll give it a try if I have some spare time and update this issue.

Meanwhile you can try building from sources or trying another version RPM.

Regards,

**Comment by Kaian** [comment]
It should be Centos 8 x86_64 RPMs available at irontec repository.

You can find instructions in the [wiki](https://github.com/irontec/sngrep/wiki/Installing-Binaries#centos--fedora--rhel) to setup up the repository.

Regards!

**Comment by mslonnyweblab** [comment]
thanksssss
