### ISSUE TITLE
Adding a column with a counter (index) for displayed calls

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#30]
This is a request for a new features.

It would be easier to refer to a call in a trace by its index number. If the trace has just a few calls, it is not a problem to figure out its index, but for large traces it can take a lot to count.

One can refer to a call by caller+callee+time or call-id, but that takes time to localize.

Not being a ncurses developer, nor that much familiar with sngrep code, if it would not be much effort, I think it would be useful to just say "look the 25th call in the trace", then one can navigate with the cursor and open the 25th call, provided that there is a column displaying the index of each call.

**Comment by Kaian** [comment]
Umm.. It won't be hard to add a numeric id to each call and and make it an attribute to display in the Call list. 

The only problem is that the actual width is more or less configured for a 132 columns terminal by default, so it would be necesary to configure the column in `sngreprc` file. Would be that a problem?
It could also be added or moved during runtime like any other column. 

Also, "Counter" o "#" seems a right label for this column, and the width 4 characteres (9999 seems to be enough).

Just as a note: You can also save selected dialogs with sngrep, so you can share only a few dialogs.

**Comment by miconda** [comment]
It is ok to be able to be added at runtime via F10, or made as permanent option via sngreprc. Eventually, if possible, to be added as first column.

Since we are at proposing new features for the main display view and you mentioned the size of the line -- might be good to have an option for displaying only the username for From and To. In many cases, the domain part is the same for all calls, e.g., when troubleshooting for single PBX/SIP server that routes calls between its phones. Source and destination IP addresses are displayed already. Domain is indeed important for carriers interconnecting providers, so I find that useful as well. I'm fine with the current state for To/From, this is more like a suggestion if you are constrained on the size of the line, you find it useful as well and of course, you have time to develop it.

**Comment by Kaian** [comment]
As non-user of my own software I have lots of doubts of what would be the most situable layout of the displayed information. 

Of course, they can be configured statically so everyone can always see what consider more usefull, but columns configuration syntax in sngreprc is not the best....

I'm also thinking about adding a button in F10/t panel, to save current displayed layout of columns and order to sngreprc. I could also make two new attributes SipFromUser and SipToUser and display them by default instead of SipFrom and SipTo.

Thanks a lot for the suggestions :)

**Comment by Kaian** [comment]
There is a new column available in Column Selector panel (F10 or t) called **Idx**.  You can enable it using `spacebar` and move to the first position using `-`. Yes, this panel usability requires some rework...

Also, display filter now accepts POSIX regexps, so if you have Idx as first column you could easily _jump_ to 25th call by pressing F3 (or `/`) and entering `^25`.

**Comment by miconda** [comment]
Nice, thanks, works perfectly.

Your suggestion with new columns SipFromUser and SipToUser is ok for getting smaller size per line.

**Comment by Kaian** [comment]
Thanks, I close this for now. New Sip attributes will be soon in master. Columns Selector panel requires more time to rework.

**Comment by miconda** [comment]
Column selector panel is ok for me -- not looking for anything fancy, it does the job now. Thanks again!
