### ISSUE TITLE
Last call on top

### ISSUE THREAD

**Issue by A5DkjGQUZx** [irontec/sngrep#300]
Possible to show last captured call on top of the list instead of going down?

**Comment by Kaian** [comment]
What about sorting by idx descending?

You can select the sorting column with <> keys.

Regards

**Comment by A5DkjGQUZx** [comment]
Yes! sorry to put it here
though maybe a good idea to add this <> inside the footer bar of the program. I had no clue there is such an option...
Thanks!

**Comment by Kaian** [comment]
It should be documented at least in the Help screen.
There are too many keybindings and too little space in the bar, so we must choose.

Thanks for reporting!
