### ISSUE TITLE
Save SIP + RTP

### ISSUE THREAD

**Issue by ownmaster** [irontec/sngrep#301]
I see an option to save SIP + RTP to .pcap file in save dialog (F2), but this option is not selectable. Is this feature not implemented, or do I miss something and it should work?

**Comment by davemidd** [comment]
By default, sngrep only captures SIP.
If you invoke it with the '-r' option, it'll also capture the RTP.

From the wiki page:
-r --rtp: Capture RTP packets payload

Hope that helps.

**Comment by Kaian** [comment]
@davemidd is right.

Take into account that storing RTP packets will use a lot of memory, so use capture filters if you have a heavy loaded system.

**Comment by ownmaster** [comment]
Oh, didn't realize that option is necessary for working this files, since I don't really capture anything. Thanks.
