### ISSUE TITLE
SNGREP not showing some SIP messages when they are over UDP fragmented

### ISSUE THREAD

**Issue by alaertegv** [irontec/sngrep#304]
Hi. The tool is great, thank you for make it available. Nevertheless I am having problem with some messages not showed. It seems SNGREP is not able to recognized as SIP long messages that is using UDP, fragmented. I can see the message is in the PCAP using Tshark or Wireshark, but SNGREP cannot present the message. I know RFC recommends using TCP for big SIP messages, but from time to time we see products using UDP for it. Is there any reason for SNGREP does not recognized those messages? Is there anything I can do, manually, to workaround it?

Thanks
Alaerte

**Comment by Kaian** [comment]
Closed due to lack of activity.

Feel free to send me a pcap to reproduce this problem if you're able to reproduce this issue.

Regards!
