### ISSUE TITLE
selection color in xterm

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#31]
hi again :)
If I use sngrep inside xterm with standard colors (white background, black font), the current selection in the list of calls is hard to read: black font on vivid blue is almost unreadable.

so. some better color combination is needed -- probably a bit lighter blue?

I'm at f7cf974a in master branch.

**Comment by Kaian** [comment]
Hi @ssinyagin !

sngrep is in fact designed for dark background terminals.

If you have white background, I **highly recommend** you to set this setting in your configuration file.

`echo set background dark >> $HOME/.sngreprc`

That way, sngrep will stop respecting your configured default background and will set a black background.

**Comment by ssinyagin** [comment]
ok thanks
