### ISSUE TITLE
sngrep 1.4.7 centos7 - RPM not signed

### ISSUE THREAD

**Issue by luismartingil** [irontec/sngrep#314]
Centos-7 latest package (released yesterday) is not signed.

This fails:
```
        sudo rpm --import http://packages.irontec.com/public.key
        REPOFILE=irontec.repo
        cat <<'EOF' > /tmp/${REPOFILE}
[irontec]
name=Irontec RPMs repository
baseurl=http://packages.irontec.com/centos/$releasever/$basearch/
EOF
        sudo mv /tmp/${REPOFILE} /etc/yum.repos.d/
        sudo yum install -y sngrep
```

**Comment by nicolastanski** [comment]
Try to run the command

`yum --nogpgcheck install sngrep`

**Comment by luismartingil** [comment]
Yes - that would do it or just disabling gpgcheck in the repo configuration, but I don't think it's what Irontec wants. Previous versions were signed properly.

**Comment by Kaian** [comment]
Hi!

I have re-run rpmsign in all 1.4.7 rpm files. Could you verify if files are now properly signed?

Thanks!

**Comment by tiagoggsouza** [comment]
I was with the same error and now is OK.

**Comment by luismartingil** [comment]
Done - thanks
