### ISSUE TITLE
CentOS package not signed

### ISSUE THREAD

**Issue by jeffclay** [irontec/sngrep#319]
Error received when trying to install sngrep on Centos 8:

Package sngrep-1.4.7+20200521.20+b132ce9-0.el8.x86_64.rpm is not signed
Error: GPG check FAILED

I did run "rpm --import http://packages.irontec.com/public.key" prior to installing.

**Comment by Kaian** [comment]
Hi @jeffclay 

Thanks for reporting, I've re-run the repo jobs like I did for #314 so this should be fixed.

Can you give it a try?

**Comment by jeffclay** [comment]
Works like a charm now! Thank you
