### ISSUE TITLE
where is the 'capture_launch_thread()' of   implementations?

### ISSUE THREAD

**Issue by MyPrivateAccount** [irontec/sngrep#324]
In “caputure.h” , I found the declaration of “capture_launch_thread() ”，but I not found the  function  implementations.

**Comment by MyPrivateAccount** [comment]
`/**
 * @brief Create a capture thread for online mode
 *
 * @return 0 on success, 1 otherwise
 */
int capture_launch_thread();`

**Comment by Kaian** [comment]
Hi @MyPrivateAccount 

You can usually find implementation in the .c file with the same name.

 https://github.com/irontec/sngrep/blob/master/src/capture.c#L858-L877

Regards

**Comment by MyPrivateAccount** [comment]
Thanks.  but. there have not the function of having not arguments

**Comment by Kaian** [comment]
Well, that's an error in the implementation.

The argument should actually be a local variable, used to iterate in the while loop.

Compilers should complain, not sure how they have passed this one :thinking:

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand

**Comment by MyPrivateAccount** [comment]
Thank you very much for your patience to answer in detail, I begin to understandThank you very much for your patience to answer in detail, I begin to understand
