### ISSUE TITLE
MS Teams weird Audio in Sngrep

### ISSUE THREAD

**Issue by mase2hot** [irontec/sngrep#325]
Hello

I have got MS teams working with Kamailio for outbound calls. SIP Signalling looks correct and audio works both ways testing 10 minutes plus with no issues.

Where I'm not sure if there is an underlying issue is when I looked at sngrep there seems to be weird things going on with RTP. The streams appear to be starting and stopping then showing unassigned.

For inbound calls to MS Teams I see no such behaviour.

It's using RTPEngine to handle media so that MS can be SRTP and my network remain RTP.

Please see image. It doesn't look right but the audio is fine. Is it just a bug in sngrep?

Image below

https://ibb.co/qjrScCc

**Comment by Kaian** [comment]
Hi @mase2hot 

sngrep marks as Unassigned those RTP packets whose payload type id can not be mapped with SDP rtp ids. I would recommend debugging the pcap with wireshark call flow to check those RTP payload types. If the payload is present in the SDP (or it's a standard payload type) then sngrep should display it instead of Unassigned and you hit a bug.

Regards

**Comment by mase2hot** [comment]
Thanks @Kaian for the reply. I see this in Wireshark "Payload type: ITU-T G.711 PCMU (0)" for both streams.

**Comment by Kaian** [comment]
If Wireshark only displays two streams with payload type 0 and sngrep displays 8 with Unassigned it must be a bug in our side. 

Are you using the latest sngrep version (1.4.7)? 
Can you send me a sample .pcap to debug this problem?

Regards!

**Comment by mase2hot** [comment]
1.4.6, I am on. Do you have a private way of receiving the pcap?

**Comment by Kaian** [comment]
Send it to the email in my profile :)

**Comment by mase2hot** [comment]
Emailed a couple of hours back, just checking you received?

**Comment by Kaian** [comment]
Yep, I've received but I haven't time to check its contents.

Thanks for the test file, it helps debugging!

**Comment by Kaian** [comment]
Hi @mase2hot 

This was a bug in RTCP packet handling that was changing the previous RTP streams format.
With the above commit streams are now properly shown.

![streams](https://user-images.githubusercontent.com/800069/93444646-fffedc00-f8d0-11ea-96ee-7b69e7456735.png)

This will be available in 1.4.8

Thanks for reprting!!
