### ISSUE TITLE
Sngrep no captura algunos invites

### ISSUE THREAD

**Issue by carlosvalenzuel-a** [irontec/sngrep#326]
Lanzando **sngrep -c**, o **sngrep** y filtrando con F7 solamente Invites, observo que algunas llamadas de las que puedo seguir su traza en full.log no aparecen cuando busco con F3 en la aplicación.

Esto ha empezado a pasar buscando llamadas concretas que nos reportan sin audio entrante.

Asterisk está instalado en un Centos de Amazon Web Services pero no filtro más que invites, entiendo que captura el dispositivo virtual y el físico.

Gracias por vuestros comentarios.

**Comment by Kaian** [comment]
Hola @carlosvalenzuel-a 

El lenguaje que empleamos en GitHub es inglés, y no hay problema aunque este venga de un traductor. Si lo prefieres, puedes incluir los dos idiomas en la incidencias.

Puedes capturar con otra herramienta, como tpcdump o ngrep al mismo tiempo y generar un pcap que contenga un INVITE que no se muestra en sngrep? Puedes enviarme este .pcap al correo que figura en mi prefil.

Saludos!

--

Hi @carlosvalenzuel-a 

The official language in GitHub is english, and there is no problem if you use a translator. If you prefer, you can include both languages in the issues.

Can you make a capture with another tool, like tcpdump or ngrep at the same time and generate a pcap that haves an INVITE that is not shown in sngprep? You can send me that .pcap to the email that's on my profile.

Regards
