### ISSUE TITLE
feature request: stop the capture

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#33]
a nice to have feature request: a shortcut key that would stop the running capture.

**Comment by Kaian** [comment]
Existing, but not documented! My bad :(

During online mode, you can pause capture using `p`

**Comment by ssinyagin** [comment]
ha, thanks :)
by the way, I pressed "F" by accident, and there's still "Destiny" instead
of "Destination"

On Wed, Feb 25, 2015 at 3:16 PM, Kaian <notifications@github.com> wrote:

> Existing, but not documented! My bad :(
>
> During online mode, you can pause capture using p
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/irontec/sngrep/issues/33#issuecomment-75966091>.
>



-- 
Stanislav Sinyagin
Senior Consultant, CCIE #5478
ssinyagin@k-open.com
+41 79 407 0224

**Comment by Kaian** [comment]
Yay! Is my destiny to fail with that mistraslation.

Thanks for reporting!
