### ISSUE TITLE
improvements: IPv6 address formating

### ISSUE THREAD

**Issue by sergey-safarov** [irontec/sngrep#330]
When I open detail of the message sent via IPv6 I can see
> 2020/09/27 08:05:35.179918 **2600:1f1c:257:8706:a135:3506:d518:b71f**:38600 -> **2600:1f1c:99b:fd00::300**:5080
INVITE sip:+19163120077@example.com SIP/2.0
Record-Route: <sip:[2600:1F1C:257:8706:A135:3506:D518:B71F];transport=tcp;r2=on;lr=on;ftag=dM9u7ofac>
Record-Route: <sip:3.101.84.4;transport=tcp;r2=on;lr=on;ftag=dM9u7ofac>

Here you can see strings like:
1) 2600:1f1c:257:8706:a135:3506:d518:b71f:38600
2) 2600:1f1c:99b:fd00::300:5080

here is the start of the string IPv6 address and the end is port. Values do not contain brackets.

Could you enclose the IPv6 address into brackets?

**Comment by Kaian** [comment]
Hi @sergey-safarov 

Thanks for the request! Above commit should change how ipv6 addresses are displayed in raw screen, so for the next release you'll see this message header format

2020/09/27 08:05:35.179918 [2600:1f1c:257:8706:a135:3506:d518:b71f]:38600 -> [2600:1f1c:99b:fd00::300]:5080



Regards!

**Comment by sergey-safarov** [comment]
Thanks, Kaian.
Looks this good improvement.
I close the feature request as it implemented.
