### ISSUE TITLE
sngrep Unable to grab RTP

### ISSUE THREAD

**Issue by linlin2018** [irontec/sngrep#338]
sngrep -r  ，RTP cannot be displayed using F3 view

**Comment by Kaian** [comment]
Hi @linlin2018 

-r flag is used to store RTP information in memory, so it can be later saved into a PCAP file. Be careful because it uses a lot of RAM. You don't need the -r flag to see RTP flows in Call Flow.

The problem will be probably elsewhere.

Can you provide a test PCAP file with RTP not being displayed?
Take into account that RTP IP address and port must be present in the SDP of the dialog, othewise thet won't be printed. 

Regards

**Comment by linlin2018** [comment]
Hi&nbsp;
I have two doubts: first, insufficient RAM, cloud testing I'm using, and second, NAT problems.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irontec/sngrep"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月11日(星期三) 下午4:25
收件人:&nbsp;"irontec/sngrep"<sngrep@noreply.github.com&gt;;
抄送:&nbsp;" "<123698827@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [irontec/sngrep] sngrep Unable to grab RTP (#338)





 
Hi @linlin2018
 
-r flag is used to store RTP information in memory, so it can be later saved into a PCAP file. Be careful because it uses a lot of RAM. You don't need the -r flag to see RTP flows in Call Flow.
 
The problem will be probably elsewhere.
 
Can you provide a test PCAP file with RTP not being displayed?
 Take into account that RTP IP address and port must be present in the SDP of the dialog, othewise thet won't be printed.
 
Regards

**Comment by Kaian** [comment]
Hi,

I don't think RAM is an issue here, but NAT will probably. sngrep ignores RTP traffic unless it is an IP address present in SDP payload or comes from the same IP address that SIP messages.

Can you provide a test PCAP captured with another tool like tcpdump or ngrep that contains RTP data that is not displayed by sngrep?

Regards

**Comment by linlin2018** [comment]
Hi,
I provide you with two capturing packages. The software itself is not complete.


Please keep the information inside the bag confidential and keep it confidential.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irontec/sngrep"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 下午5:16
收件人:&nbsp;"irontec/sngrep"<sngrep@noreply.github.com&gt;;
抄送:&nbsp;" "<123698827@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [irontec/sngrep] sngrep Unable to grab RTP (#338)





 
Hi,
 
I don't think RAM is an issue here, but NAT will probably. sngrep ignores RTP traffic unless it is an IP address present in SDP payload or comes from the same IP address that SIP messages.
 
Can you provide a test PCAP captured with another tool like tcpdump or ngrep that contains RTP data that is not displayed by sngrep?
 
Regards
