### ISSUE TITLE
Change the default path to save the pcap files

### ISSUE THREAD

**Issue by wrfrohlich** [irontec/sngrep#343]
Hello,

I would like to change the default path for save the pcap file using the **F2**, the default path is /root and I would like to change to /tmp. Is it possible to change this default path or whenever I will save using the **F2** I must change this directory?

![Save](https://user-images.githubusercontent.com/41973611/103653317-23629b00-4f43-11eb-95b9-fc979aa540bb.JPG)

**Comment by Kaian** [comment]
Hi @wrfrohlich 

Sorry for the late response, I was on holidays :)

Yes, you can change default save by changing savepath setting in your ~/.sngreprc or /etc/sngreprc file

    echo set savepath /tmp/ >> ~/.sngreprc

You can get a list of settings running `sngrep --dump-config` or checking the project wiki for a list of settings and possible values.

Regards
