### ISSUE TITLE
Feature-request: Add support to Kamailio SIPDUMP Module format

### ISSUE THREAD

**Issue by buzhaodi** [irontec/sngrep#344]
i use SIPDUMP Module in kamailio for record sip message，Can I use sngrep to parse the text produced by SIPDUMP Module in kamailio?

**Comment by Kaian** [comment]
Hi @buzhaodi 

Sorry for the late response, I was on holidays :)

Nope. Currently the only supported input is PCAP format, so text files won't work. 
I will convert this question to a feature request in case more users are interested in supporting this.

Regards!

**Comment by buzhaodi** [comment]
thanks ,that's great for me! I am waiting for your good news

**Comment by sergey-safarov** [comment]
You can check [instruction](https://github.com/irontec/sngrep/wiki/Send-HEP-traffic-from-Kamailio-to-local-sngrep)
This allows you also to parse TLS encrypted packets (like from text)

**Comment by miconda** [comment]
sipdump module starting with kamailio v5.5.0 can write pcap files that can be visualised with sngrep:

  * https://www.kamailio.org/docs/modules/stable/modules/sipdump.html#sipdump.p.mode

Just be aware that all packets appear as UDP, even they are over TCP/TLS (it was easier to build the pcap, not sure if I have the time soon for further enhancements, it is enough from my perspective -- there is also a meta header that can be inserted to see easier the transport, or look at Via/other headers in SIP to figure it out).

Once sipdumps writes in the file, one can see the traffic live in the pcap file with:

```
tail -c +1 -f /tmp/kamailio-sipdump-DATE.pcap | sngrep -I -
```

Probably this request for feature can be closed if nobody commits to add support for parsing the sipdump text files with sip traffic.

**Comment by Kaian** [comment]
I like the approach provided by miconda, so I'm closing this.

Thanks everyone!
