### ISSUE TITLE
HTML output

### ISSUE THREAD

**Issue by sdwru** [irontec/sngrep#348]
Is there any way to get an html output?  I am using [phpseclib](https://github.com/phpseclib/phpseclib) to ssh into remote servers via PHP and display the command outputs on a web page.  It works well with commands like `top` but it would be nice if I could get sngrep output to display.  

I understand that sngrep is interactive and real time so that would limit what I could do.  Perhaps I could stream pcap and then parse that.

**Comment by Kaian** [comment]
Hi @sdwru 

As you mention, sngrep is designed to be realtime and interactive, so output is changing constantly. I think this kind of feature belong to another tool (maybe without TUI, just console output), or some scripting parsing output of commands like ngrep or tcpdump.

Although having a browser interface will be awesome, i think this is too far from being done.

Regards
