### ISSUE TITLE
CLI options parsing error

### ISSUE THREAD

**Issue by ssinyagin** [irontec/sngrep#35]
hi again :)

these two commands work:
```
sngrep /var/local/sip-2015-02-25--13-56-16.pcap
sngrep -c -I /var/local/sip-2015-02-25--13-56-16.pcap
```
but this one does not:
```
sngrep -c /var/local/sip-2015-02-25--13-56-16.pcap 
Couldn't parse filter /var/local/sip-2015-02-25--13-56-16.pcap : syntax error
```
as -I is optional, it should be always optional :)

**Comment by Kaian** [comment]
Hi!

 Well, `-I` is not optional. In fact `sngrep -h` output is wrong. 

`sngrep [-IO pcap_dump] [-d dev] [-k keyfile] [<bpf filter>|<pcap_dump>]`

When it should say

`sngrep [[-IO pcap_dump] [-d dev] [-k keyfile] [<bpf filter>]|<pcap_dump>]`

As you can see, there are two different ways to pass a pcap file to sngrep, one using `-I` option and another if you only pass that argument. It should be properly (which is not)  documented [here](https://github.com/irontec/sngrep/wiki#command-line-arguments).

The second syntax is more a legacy option. I not really sure (from the coders view) if its better to remove the second syntax or to add more logic to try to detect if any of the _alone_ arguments is a file (which in fact could be worse if you have a file in your current dir with a bpf filter name, like host or port :disappointed: )

With the `match_expression` addition, detection logics will be even worse.

**Comment by ssinyagin** [comment]
then probably it makes sense to drop the old syntax and enforce -I if the
input is from a pcap file

**Comment by Kaian** [comment]
I could do a transitional stage between actual and removing that _feature_.

I could replace the logic that opened the file when only one argument was passed to a simple message:  
`/var/local/sip-2015-02-25--13-56-16.pcap seems a file: You forgot -I ?`

**Comment by ssinyagin** [comment]
well, depends on how people got used to use it :)
