### ISSUE TITLE
[PATCH] [FEATURE] Extended Flow from Bleg(s)

### ISSUE THREAD

**Issue by gmaruzz** [irontec/sngrep#352]
Hello Kaian,

this patch allows for visualizing Extended Call Flow (X-Call-ID, F4) when cursor is on a B-leg (eg, on a call that has an xcallid). 

If current call do not have an xcallid (so, it is an A-leg) then behavior is not modified. 
If current call do has an xcallid (so, it is a B-leg), check if its A-leg call exists. If that A-leg exists, do the extended call flow for that call

this patch apply to today latest git, d69e7b2f49fe1d6357614dde72ddaf941777cef2 

<pre>
diff --git a/src/curses/ui_call_list.c b/src/curses/ui_call_list.c
index 7299955..7c83876 100644
--- a/src/curses/ui_call_list.c
+++ b/src/curses/ui_call_list.c
@@ -632,8 +632,18 @@ call_list_handle_key(ui_t *ui, int key)
                 // Add xcall to the group
                 if (action == ACTION_SHOW_FLOW_EX) {
                     call = vector_item(info->dcalls, info->cur_call);
-                    call_group_add_calls(group, call->xcalls);
-                    group->callid = call->callid;
+                   if(strlen(call->xcallid)){ //giovanni
+                       if(sip_find_by_callid(call->xcallid)){ //giovanni
+                            call_group_del(group, call); // giovanni
+                            call = sip_find_by_callid(call->xcallid); //giovanni
+                            call_group_add(group, call); // giovanni
+                            call_group_add_calls(group, call->xcalls); //giovanni
+                            group->callid = call->callid;
+                       } //giovanni
+                   }else { //giovanni
+                        call_group_add_calls(group, call->xcalls);
+                        group->callid = call->callid;
+                   } //giovanni
                 }

                 if (action == ACTION_SHOW_RAW) {

</pre>

**Comment by Kaian** [comment]
Hi @gmaruzz !!

I like the idea here, thanks a lot!

I have created a PR#353 with the patch applied to both Call Flow and Call List, so you can replace current dialog with its A-leg and their B-legs if extended keybinding is pressed in either screen.

Feel free to check the code there and provide any feedback.

Thanks for the contribution!

**Comment by gmaruzz** [comment]
Thanks a lot to you!!
