### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by jzrlost** [irontec/sngrep#358]
Anytime frame on supporting Raspberry Pi boards?  We use sngrep on our SBC's, but it would be great to use them on some of our endpoints also, which are raspberry Pi's.

thx Josh

**Comment by Kaian** [comment]
Hi Josh!

It should compile and work on any OS that supports libpcap and ncurses, what's exactly the problem?

Regards!

**Comment by jzrlost** [comment]
Looks like it works when you compile it.  I was originally looking for an install package or something like that, but manually compiling it went off without a hitch.  Thank you.
