### ISSUE TITLE
sngrep long time packet capture sent to Homer, sending failed

### ISSUE THREAD

**Issue by daxiondi** [irontec/sngrep#359]
I used sngrep to grab packets for a long time to send to home. At first, there was no problem. About a day later, Homer didn't receive the request from sngrep. Would you like to know where sngrep can see the relevant logs?
Regards

**Comment by Kaian** [comment]
Hi @daxiondi 

sngrep is not designed to be running for long periods so using it like a daemon is not recommended.

Also, HEP support was not added to replace captagent o heplify daemons, but for sending specific dialogs to Homer or to merge multiple sngrep traffic into a single sngrep.

As this is a tool and not a daemon, it lacks logs files.

Regards
