### ISSUE TITLE
Caracteres raros en vez de líneas con terminal configurado en UTF-8.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#36]
Hola,

Como he comentado, estoy usando Putty 0.63.

Para que me aparezcan correctamente las líneas de los marcos de, por ejemplo, el "mc", tengo configurado Putty (Windows -> Translarion -> Remote Character Set) en UTF-8.

Cuando ejecuto "sngrep" con esa codificación las líneas de los marcos del panel, flechas, etc, me salen códigos raros y tengo que cambiar la codificación, por ejemplo, a ISO-8859.

¿Se puede adaptar para no tener que ir cambiando de una codificación a otra?.

Saludos

**Comment by Kaian** [comment]
Buenas!

Duplicada #26.

Prueba empleando la última versión disponible en `master`. Cuenta con una opción `--enable-unicode` que añade compatibilidad con visualización en UTF-8. Tiene como dependencia las librerias wide-character de ncurses (libncursesw5).

```
./configure --enable-unicode
make && make install
echo NCURSES_NO_UTF8_ACS=1 >> /etc/environment
```

La próxima vez que inicies sesión se debería visualizar bien.
