### ISSUE TITLE
IPv6 address in Source and Destination

### ISSUE THREAD

**Issue by sergey-safarov** [irontec/sngrep#363]
I want to search using Source and Destination fields value.
In my case using IPv6 addresses.
The current length of Source and Destination fields do not allow place full IPv6 addresses.
Could you extend the size of the Source and Destination fields?
```
┌────────────────────────────────────────────────┐
│                 Filter options                 │
├────────────────────────────────────────────────┤
│  SIP From:                                     │
│  SIP To:                                       │
│  Source: wanted to plase IPv6 address here     │
│  Destination: and here wanted IPv6 address     │
│  Payload:                                      │
├────────────────────────────────────────────────┤
│  REGISTER   [*]        OPTIONS    [*]          │
│  INVITE     [*]        PUBLISH    [*]          │
│  SUBSCRIBE  [*]        MESSAGE    [*]          │
│  NOTIFY     [*]        REFER      [*]          │
│  INFO       [*]        UPDATE     [*]          │
├────────────────────────────────────────────────┤
│          [ Filter ]         [ Cancel ]         │
└────────────────────────────────────────────────┘
```
Maximal length of IPv6 address is 45 chars. [Link](https://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address)

**Comment by Kaian** [comment]
Hi @sergey-safarov 

Above commit allows the field to internally store a bigger filter string.
Take into account this fields are regular expressions, so avoid using brackets for ipv6 addresses.

Also, if you are filtering a lot of data, it would be better to use BPF filters in command line.

Thanks for reporting!

**Comment by sergey-safarov** [comment]
Thanks @Kaian 
I have made a test of current master and I able to specify IPv6 address like `2000:1111:2222:3333:4444:5555:6666:7777`.
But not able to specify `0000:0000:0000:0000:0000:ffff:192.168.100.228` that will be also the correct address.

Generally, I am fine with the latest update.
So, I close commit.
