### ISSUE TITLE
Where can I find all Call State lists?

### ISSUE THREAD

**Issue by livem** [irontec/sngrep#365]
Where can I find all Call State lists?

- COMPLETED
- CANCELLED
- BUSY
- REJECTED
- ...

Have any documents for sip status codes mapping to **Call State** field ?

Thanks.

**Comment by Kaian** [comment]
Hi @livem 

The possible values are defined in this enum:

https://github.com/irontec/sngrep/blob/d69e7b2f49fe1d6357614dde72ddaf941777cef2/src/sip_call.h#L43-L54

The logic behind the state changes are defined in the function call_update_state here:

https://github.com/irontec/sngrep/blob/d69e7b2f49fe1d6357614dde72ddaf941777cef2/src/sip_call.c#L197

There are no any further documentation for this logic, it has been implemented to provide a hint in call list like wireshark call window, but with a homemade criteria.

Regards!
