### ISSUE TITLE
Saving filters by default

### ISSUE THREAD

**Issue by falves1** [irontec/sngrep#366]
This is more a question or a suggestion. If I set a filter, for example, I never want to see OPTIONS, should this choice not remain in force for as long I use sngrep in the machine, or with the same user? Why do I have to set my filters again and again?  sngrep should make filters persist across uses of the tool, by saving them to an *.ini file somewhere.

**Comment by Kaian** [comment]
Hi @falves1 

Please read the configuration section in the wiki for available options and where they're saved. It may not be up to date, you can also check available settings with `sngrep -D` and update the wiki if you find something missing. 

https://github.com/irontec/sngrep/wiki/Configuration

Looks like filter.methods could work for your problem

Regards
