### ISSUE TITLE
Horizontal scroll feature in call flow

### ISSUE THREAD

**Issue by Kanishk251296** [irontec/sngrep#367]
After joining flow of 2 or more packets , the no of packets exceeds the screen size and there is no way to see those call flows . So please the feature of horizontal scrolling to examine those flows

**Comment by Kaian** [comment]
Hi @Kanishk251296 

This a dup from #210 and I would try to add it in next major version (2.x).

Meanwhile, you can try hidding message preview ( *t* keybinding) or changing the size of your terminal (usually Ctrl + and Ctrl -) to display more arrows in the screen

Regards

**Comment by Kanishk251296** [comment]
Hello all,

Thanks for the update
I will be very useful

Warm regards,
Kanishk jain
