### ISSUE TITLE
Missing INVITE in pcap

### ISSUE THREAD

**Issue by Shaaah** [irontec/sngrep#368]
There are INVITES I can't see in sngrep that I can see in wireshark and ngrep.

sngrep version : 1.4.9

ngrep : 

![1 2](https://user-images.githubusercontent.com/1789275/130081122-d01501c4-362d-49da-b556-694b472f92cd.png)

sngrep :

![2 2](https://user-images.githubusercontent.com/1789275/130081158-e6e0ebfc-73b1-4d79-941f-d4fbc2c34e05.png)

**Comment by Kaian** [comment]
Hi @Shaaah 

Most probably this is a fragmentation issue like #357

When you use a BPF filter with port (like port 5060), libpcap only passes to sngrep the packets that contains a udp or tcp header with port 5060. If your SIP Message is fragmented into multiple packets, the first one will have the UDP header with the port value but the next fragments won't, so libpcap will not pass them to sngrep, making assembly impossibe.

Please, try removing the port 5060 filter and check if the INVITE is displayed. Optionally, use a BPF filter that also consider fragments even if they doesn't contain a UDP header.

      sngrep -I ovh-test4.pcap port 5060 or 'ip[6:2] & 0x3fff != 0'

Regards

**Comment by Shaaah** [comment]
I still can't see the INVITE when removing the port filter or with the other filter you gave.

Do you know of a good anonymizer for pcap files ?

**Comment by Kaian** [comment]
Nope, most of pcaps I receive contain the original data, but I remove them after the debugging is done.

Is the SIP menssage fragmented in multiple packets? 
Does the pcap file contain all fragments in order?

Feel free to send me any pcap to my email with the failing message pcap.

Regards!

**Comment by Kaian** [comment]
In the end, this was a problem in how the pcap info was stored and limitations mentioned in sngrep IP assembly process. sngrep is only able to assemble IP if all fragments are present and sorted.

In this case, all fragments were duplicaticated in the capture, so a two fragment packet was being parsed as Frag1,Frag1,Frag2,Frag2 and failing in assembly. 

Feel free to reopen if you have other sample files.
