### ISSUE TITLE
Bullseye binaries

### ISSUE THREAD

**Issue by gedia** [irontec/sngrep#376]
Hello all,

Are you considering providing a repository for debian bullseye as well? Thanks!

**Comment by Kaian** [comment]
Hi @gedia !

You can find sngrep in official Debian bullseye repositories, but we will also add it to Irontec repositories soon.

Regards!

**Comment by Kaian** [comment]
Version 1.4.9 should be available in Irontec repositories.

**Comment by gedia** [comment]
Wow, that was fast. Thanks!
