### ISSUE TITLE
sngrep marking transport as UDP when its TCP

### ISSUE THREAD

**Issue by recourse** [irontec/sngrep#378]
Hi when capturing some customer traffic I noticed that sngrep is marking the packets as UDP when in fact the transport is TCP. 

I can provide pcaps out of bound.  

sngrep -V
sngrep - 1.4.9
Copyright (C) 2013-2018 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with Wide-character support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with IPv6 support.
 * Compiled with EEP/HEP support.

Written by Ivan Alonso [aka Kaian]

**Comment by Kaian** [comment]
Hi @recourse 

I assume you refer to the Transport column displayable in the list.

Feel free to send me a sample pcap to my email, I'll check it as soon as I can.

Thanks for reporting!

**Comment by Kaian** [comment]
Above commit should fix the problem, that looks related to assembled TCP packets.

I have also noticed that timestamps and delta calculation are wrong in call flow, so I'll try to also check that if I have some time.

Thanks for the pcap file, it helps a lot for debugging.

**Comment by recourse** [comment]
That worked thank you very much!
