### ISSUE TITLE
sngrep Doesn't show kdmq packages if select some request type in the filters

### ISSUE THREAD

**Issue by gostkov** [irontec/sngrep#384]
Hi guys.

I see KDMQ packages in the list, if I exclude some sip request type in the Filter (for example I don't want see OPTIONS requests), sngrep accepting filter and hide OPTIONS and KDMQ packages.

p.s. maybe you can add KDMQ requests to the Filter section?

Version: 1.4.9

**Comment by Kaian** [comment]
Hey @gostkov 

Sure, this should be easy to add for the next release.

Meantime, you can use filter.methods setting to configure your filters by default as a workaround

    echo set filter.methods KDMQ,INVITE,REGISTER >> ~/.sngreprc

You can check your active setting by running

    sgnrep -D

Regards!

**Comment by gostkov** [comment]
@Kaian oh, thanks!
