### ISSUE TITLE
segmentation fault on CentOS 7

### ISSUE THREAD

**Issue by WorkingClass** [irontec/sngrep#387]
Hello,

happy Holidays to you All.

I do run into a weird error causing segmentation fault on one server that is running CouchDB as well as Kamailio.

After enabling debug and run "thread apply all backtrace full" after the crash, here is the output:

(gdb) thread apply all backtrace full

Thread 2 (Thread 0x7ffff4a2f700 (LWP 26953)):
#0  0x00000000004066b3 in capture_packet_reasm_tcp (capinfo=0x659d50, packet=0x7fffe8034cd0, tcp=0x7ffff4a29c74, payload=0x7ffff4a29c94 "\240\235e", size_payload=62535) at capture.c:698
        it = {current = 0, current_vector = 0, vector = 0x0, filter = 0x0}
        pkt = 0x4e6b24fa
        new_payload = 0xb200000000 <error: Cannot access memory at address 0xb200000000>
        full_payload = "\003h\002m\000\000\000\024most_recent_by_agenth\001l\000\000\000\001h\002m\000\000\000\003mapm\000\000\000ifunction(doc) { if ( doc.pvt_type != 'status@\360\030\001\000\000\037:\312aL%\311\017\256\000shards/40000000-7fffffff/_global_changes.1620899746l\000\000\000\001h\002R\bh\004R\bR\tl\000\000\000\001m\000\000\000\006_adminjR\005jh\031R\n"...
        original_size = 264647
        valid = 0

The full_paylod is actually something related to CouchDB.

Note: I do have another server with the same config and sngrep, the issue is not happening in that server.

Can you please help.

Thanks,
Victor

**Comment by Kaian** [comment]
Hi!

Are you able to reproduce this issue?
Could you provide a pcap captured at the same time with other tool (tpcdump, ngrep, ..) that can reproduce the crash so we can debug it and test a fix?

Thanks for reporting!

**Comment by WorkingClass** [comment]
Hello,

Sorry for the late reply. I solve it by increasing MAX_CAPTURE_LEN to 64k.

Thanks,

**Comment by Kaian** [comment]
Hi, 

That's quite strange because that crash is happening in _capture_packet_reasm_tcp_, but MAX_CAPTURE_LEN is checked at the start of packet capture:

https://github.com/irontec/sngrep/blob/5673f9ef0e973a421fd7a039d4dbc65596614da1/src/capture.c#L295-L297

So, packets with size_payload > 20k should not even be reach that point.

Thanks!

**Comment by WorkingClass** [comment]
Yes, it's strange.

But the "size_payload" in ths debug log drives me to try to increase the MAX_CAPTURE_LEN to 64k:
Thread 2 (Thread 0x7ffff4a2f700 (LWP 26953)):
#0 0x00000000004066b3 in capture_packet_reasm_tcp (capinfo=0x659d50, packet=0x7fffe8034cd0, tcp=0x7ffff4a29c74, payload=0x7ffff4a29c94 "\240\235e", **size_payload=62535**) at capture.c:698

Thanks,

**Comment by Kaian** [comment]
Hi!

We were checking max capture length per packet, but not after all packets have been assembled. Above commit, should address this.

Thanks for reporting!

**Comment by WorkingClass** [comment]
Great.
Thanks,
    On Monday, May 2, 2022, 04:30:13 a.m. EDT, Kaian ***@***.***> wrote:  
 
 


Hi!

We were checking max capture length per packet, but not after all packets have been assembled. Above commit, should address this.

Thanks for reporting!
