### ISSUE TITLE
Segment fault on Ubuntu

### ISSUE THREAD

**Issue by gbernaldo82** [irontec/sngrep#389]
Hi, good monring!

I've install sngrep in Ubuntu using the official repositories and when I run the sngrep I can inspect the content of the SIP messages but, when I press the ESC key I allways get a Segment fault. I don't know why I have this problem. I tried to build and install the github version and I have the same problem.

Next I show you a screenshot with the backtrace from GDB:
![sngrep_segment_fault](https://user-images.githubusercontent.com/94070947/152765806-d0cc76f2-c932-4f38-8f9f-5779105b3f2d.png)

If you need more info, please, let me know about it.

My system is an Ubuntu:
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

Thanks in advance!

**Comment by Kaian** [comment]
Hi!

I was able to reproduce this in a ubuntu docker container. Looks like the offending code is:

https://github.com/irontec/sngrep/blob/5673f9ef0e973a421fd7a039d4dbc65596614da1/src/curses/ui_panel.c#L172-L179 

According to documentation del_panel does not remove the window it contains, so we add delwin before deleting the panel.
Looks like the funcion has change in recent versions and it segfaults when the window it contains has already been removed, so I decided to reorder those lines and the segfault disappeared.

Please, try to build the above commit and check if the problem persists.

Thanks for reporting!!

**Comment by gbernaldo82** [comment]
Yes, that solved my problem!

Thank you so much!

Have a nice day!

**Comment by Kaian** [comment]
Good to know! This will be available in 1.5.0

Thanks!

**Comment by wdoekes** [comment]
Backreference from Ubuntu bugs: https://bugs.launchpad.net/ubuntu/+source/sngrep/+bug/1974446
