### ISSUE TITLE
Thank You - sngrep - 1.4.6 static binary

### ISSUE THREAD

**Issue by mj162** [irontec/sngrep#391]
Thank you for making `sngrep` available as a static binary in a simple, non-email capturing, arm-twisting-click-through way.

I needed to debug `INVITE`s on a paid SIP account I've used for a year on Blink Linux when I recently started using a Yealink T49G on the same account without success.  Sure, PCAP to Mermaid markdown would have been made for some pretty-printed sequence diagrams.  But I found nothing quick and easy to get-going with until I found `sngrep` static binary.  Whenever you have time to release an updated static. I'm sure many will appreciate.

Peace.

**Comment by Kaian** [comment]
Hi @mj162 

Thanks for your kind words!!

You now have static binaries for latest release (1.4.10) available at the same url 

https://packages.irontec.com/binaries/

I'll try to keep them up-to-date with the releases, if not, feel free to open an issue like this so I won't forget.

Peace!

**Comment by mj162** [comment]
Not at all; the thanks were well-deserved @Kaian .

Thank you I now have 1.4.10 (but sadly am no nearer resolving my un-responded-to `INVITE`s from a YealinkT49G to Dellmont's VoipBuster).  A valuable addition to the toolkit.

"Bad men need compass no more to achieve their ends but that good men look-on and do nothing" -- John Stuart Mill (1867).

Peace, perfect peace!

**Comment by Kaian** [comment]
Peace!
