### ISSUE TITLE
sngrep EEP send and listen not working

### ISSUE THREAD

**Issue by sathiyaraman** [irontec/sngrep#396]
Hi Kaiyan,

I have tried a scenario, where,
Server **A(A.A.A.A)** act as an HOMER with "sngrep -L udp:A.A.A.A:9060" and, 
Client  **B(B.B.B.B)** act as a capture with "sngrep -H udp:A.A.A.A:9060". 
Expecting the SIP packets which B captures should send to A and visible in the A's sngrep window, but Its not visible in A's sngrep. Kindly confirm whether I'm using the syntax correctly.

Thanks & Regards,
Sathiya

**Comment by sathiyaraman** [comment]
sngrep - 1.4.7 in both A and B

**Comment by Kaian** [comment]
Hi!

The syntax is correct and this is how I usually test HEP listener, so the problem may be related with configuration.

Please provide the output of sngrep -D for both Server and Client.

Regards!

**Comment by Kaian** [comment]
I will also recommend you to try the latest master version if you plan to also save the captured packets to pcap. That's a feature that have been recently added and may also contains fixes for the problem described in the issue.

**Comment by sathiyaraman** [comment]
> Hi!
> 
> The syntax is correct and this is how I usually test HEP listener, so the problem may be related with configuration.
> 
> Please provide the output of sngrep -D for both Server and Client.
> 
> Regards!

Hi Kaian,

I have copied the config dump of both Server and client.

[HEP_Server.txt](https://github.com/irontec/sngrep/files/8602737/HEP_Server.txt)
[HEP_Client.txt](https://github.com/irontec/sngrep/files/8602738/HEP_Client.txt)

Regards,
Sathiya

**Comment by sathiyaraman** [comment]
> I will also recommend you to try the latest master version if you plan to also save the captured packets to pcap. That's a feature that have been recently added and may also contains fixes for the problem described in the issue.

Kaian,

I'm more interested in the Hep capturing feature.
but, I have customized the sngrep to capture diameter packets too, had more changes in 1.4.10.
instead of porting all changes to sngrep's 1.5.0 can I merge the updates in those 4 files listed for "hep: support saving HEP packets to PCAP #270" (with the commit id :3a63a0836c42231a52e595ecd678f946e13f82a1) such that i can save the captured packets to pcap right

Regards,
Sathiya

**Comment by Kaian** [comment]
From the config, it looks like the client is sending in HEPv2

```
SettingId: 43    SettingName: eep.send.version     Value: 2
SettingId: 44    SettingName: eep.send.address     Value: 192.168.151.134
SettingId: 45    SettingName: eep.send.port        Value: 9060
SettingId: 46    SettingName: eep.send.pass        Value: foo
SettingId: 47    SettingName: eep.send.id          Value: 2002
```

And the server is expecting HEPv3
```
SettingId: 48    SettingName: eep.listen           Value: on
SettingId: 49    SettingName: eep.listen.version   Value: 3
SettingId: 50    SettingName: eep.listen.address   Value: 192.168.151.144
SettingId: 51    SettingName: eep.listen.port      Value: 9060
SettingId: 52    SettingName: eep.listen.pass      Value: foo
SettingId: 53    SettingName: eep.listen.uuid      Value: off
```

**Comment by Kaian** [comment]
> I'm more interested in the Hep capturing feature. but, I have customized the sngrep to capture diameter packets too, had more changes in 1.4.10. instead of porting all changes to sngrep's 1.5.0 can I merge the updates in those 4 files listed for "hep: support saving HEP packets to PCAP #270" (with the commit id :3a63a0836c42231a52e595ecd678f946e13f82a1) such that i can save the captured packets to pcap right

That commit contains the required code to allow saving received packets from HEP using UI dialog (F2). But there are some limitations, because saving data while capturing from multiples sources is not supported.

Other commits in current master address those problems: they add support for just capturing HEP in listen mode without capturing from network interface. Changes are not too big, so consider also picking these ones:

https://github.com/irontec/sngrep/commit/3a63a0836c42231a52e595ecd678f946e13f82a1
https://github.com/irontec/sngrep/commit/cde88e7a4bd838d62e348498295d0ca037679656
https://github.com/irontec/sngrep/commit/0d489126463569d5cdde191f98154cd23753c757
https://github.com/irontec/sngrep/commit/7ee20e58a8e7ba39be6e5282106913c6cf01f2b1
https://github.com/irontec/sngrep/commit/429b60be48988f3a9914a97bff8dd733fc6e7c88


Regards

**Comment by sathiyaraman** [comment]
> From the config, it looks like the client is sending in HEPv2
> 
> ```
> SettingId: 43    SettingName: eep.send.version     Value: 2
> SettingId: 44    SettingName: eep.send.address     Value: 192.168.151.134
> SettingId: 45    SettingName: eep.send.port        Value: 9060
> SettingId: 46    SettingName: eep.send.pass        Value: foo
> SettingId: 47    SettingName: eep.send.id          Value: 2002
> ```
> 
> And the server is expecting HEPv3
> 
> ```
> SettingId: 48    SettingName: eep.listen           Value: on
> SettingId: 49    SettingName: eep.listen.version   Value: 3
> SettingId: 50    SettingName: eep.listen.address   Value: 192.168.151.144
> SettingId: 51    SettingName: eep.listen.port      Value: 9060
> SettingId: 52    SettingName: eep.listen.pass      Value: foo
> SettingId: 53    SettingName: eep.listen.uuid      Value: off
> ```

after aligned the version as same in server and client, now HEP working as expected. 
Thanks for the great support Kaian.

**Comment by sathiyaraman** [comment]
> > I'm more interested in the Hep capturing feature. but, I have customized the sngrep to capture diameter packets too, had more changes in 1.4.10. instead of porting all changes to sngrep's 1.5.0 can I merge the updates in those 4 files listed for "hep: support saving HEP packets to PCAP #270" (with the commit id :3a63a0836c42231a52e595ecd678f946e13f82a1) such that i can save the captured packets to pcap right
> 
> That commit contains the required code to allow saving received packets from HEP using UI dialog (F2). But there are some limitations, because saving data while capturing from multiples sources is not supported.
> 
> Other commits in current master address those problems: they add support for just capturing HEP in listen mode without capturing from network interface. Changes are not too big, so consider also picking these ones:
> 
> [3a63a08](https://github.com/irontec/sngrep/commit/3a63a0836c42231a52e595ecd678f946e13f82a1) [cde88e7](https://github.com/irontec/sngrep/commit/cde88e7a4bd838d62e348498295d0ca037679656) [0d48912](https://github.com/irontec/sngrep/commit/0d489126463569d5cdde191f98154cd23753c757) [7ee20e5](https://github.com/irontec/sngrep/commit/7ee20e58a8e7ba39be6e5282106913c6cf01f2b1) [429b60b](https://github.com/irontec/sngrep/commit/429b60be48988f3a9914a97bff8dd733fc6e7c88)
> 
> Regards

Thanks for the additional commit references for the enhanced capture. have gone through those changes and looks good to integrate. will start working on those to integrate and test. will get back to you if found any blocks EOD.

**Comment by Kaian** [comment]
> after aligned the version as same in server and client, now HEP working as expected. Thanks for the great support Kaian.

Awesome, I will close this then, as the related problem has been solved.

Feel free to reopen if you need some light about the changes in the mentioned commits.

Regards!
