### ISSUE TITLE
Make Error on OpenBSD amd64

### ISSUE THREAD

**Issue by ftwrobert** [irontec/sngrep#40]
I've got a PC Engines APU box http://www.pcengines.ch/apu.htm that I've installed OpenBSD 5.6 on. I get the following errors when building sngrep.

```
# make
Making all in src
make  all-am
if gcc -DHAVE_CONFIG_H -I. -I. -I.      -g -O2 -MT capture.o -MD -MP -MF ".deps/capture.Tpo" -c -o capture.o capture.c;  then mv -f ".deps/capture.Tpo" ".deps/capture.Po"; else rm -f ".deps/capture.Tpo"; exit 1; fi
In file included from capture.h:40,
                 from capture.c:35:
/usr/include/netinet/if_ether.h:137: error: field 'ea_hdr' has incomplete type
In file included from capture.c:35:
capture.h:99: error: expected specifier-qualifier-list before 'pthread_t'
capture.c: In function 'parse_packet':
capture.c:274: error: incompatible type for argument 1 of 'sip_load_message'
capture.c: In function 'capture_close':
capture.c:304: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_launch_thread':
capture.c:321: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_set_bpf_filter':
capture.c:348: warning: passing argument 3 of 'pcap_compile' discards qualifiers from pointer target type
capture.c: In function 'datalink_size':
capture.c:447: error: 'DLT_LINUX_SLL' undeclared (first use in this function)
capture.c:447: error: (Each undeclared identifier is reported only once
capture.c:447: error: for each function it appears in.)
capture.c: In function 'lookup_hostname':
capture.c:499: error: 'AF_INET' undeclared (first use in this function)
*** Error 1 in src (Makefile:277 'capture.o')
*** Error 1 in src (Makefile:174 'all')
*** Error 1 in /usr/src/sngrep-master (Makefile:231 'all-recursive')
#                                                     

```
It seems as though ./bootstrap.sh and ./configure have no problems themselves.

```
# ./bootstrap.sh                                                                                                                                                                                        
Generating the configure script ...
# ./configure                                                                                                                                                                                           
configure     configure.ac  
# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for egrep... (cached) /usr/bin/grep -E
checking for pthread_create in -lpthread... yes
checking for pcap_open_offline in -lpcap... yes
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for initscr in -lncurses... yes
checking for new_panel in -lpanel... yes
checking for new_form in -lform... yes
checking for new_item in -lmenu... yes

 ██╗██████╗  ██████╗ ███╗   ██╗████████╗███████╗ ██████╗
 ██║██╔══██╗██╔═══██╗████╗  ██║╚══██╔══╝██╔════╝██╔════╝
 ██║██████╔╝██║   ██║██╔██╗ ██║   ██║   █████╗  ██║     
 ██║██╔══██╗██║   ██║██║╚██╗██║   ██║   ██╔══╝  ██║     
 ██║██║  ██║╚██████╔╝██║ ╚████║   ██║   ███████╗╚██████╗
 ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚══════╝ ╚═════╝

configure: 
configure: sngrep configure finished                                    
configure: ======================================================       
configure: OpenSSL Support              : no                    
configure: Unicode Support              : no                            
configure: Perl Expressions Support     : no              
configure: IPv6 Support                 : no              
configure: ======================================================       
configure: 
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands

```

**Comment by Kaian** [comment]
Hi @ftwrobert !

Thanks for reporting, It seams a problem with some specific includes for Linux systems.

I'll try to find a system with OpenBSD (not so easy..) to properly test the required includes.

**Comment by ftwrobert** [comment]
I've got a few systems at my disposal, let me know if I can be of any assistance.

**Comment by Kaian** [comment]
We'll I've done some blind changes reading some recomendations. If you can test them (and most probably print the next error) it woult be nice.

If there are too many incompatibilities, then maybe I should request one of those enviroments.

Thanks in advance!

**Comment by ftwrobert** [comment]
I have no problem going back and forth; But on that note, let me see what I can do about getting you access to a system - it may be this weekend before I can pull my spare box out and put it together..

Here's the next output.

# make
Making all in src
make  all-am
if gcc -DHAVE_CONFIG_H -I. -I. -I.      -g -O2 -MT capture.o -MD -MP -MF ".deps/capture.Tpo" -c -o capture.o capture.c;  then mv -f ".deps/capture.Tpo" ".deps/capture.Po"; else rm -f ".deps/capture.Tpo"; exit 1; fi
In file included from capture.h:40,
                 from capture.c:35:
/usr/include/netinet/if_ether.h:137: error: field 'ea_hdr' has incomplete type
In file included from capture.c:35:
capture.h:99: error: expected specifier-qualifier-list before 'pthread_t'
capture.c: In function 'parse_packet':
capture.c:274: error: incompatible type for argument 1 of 'sip_load_message'
capture.c: In function 'capture_close':
capture.c:304: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_launch_thread':
capture.c:321: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_set_bpf_filter':
capture.c:348: warning: passing argument 3 of 'pcap_compile' discards qualifiers from pointer target type
capture.c: In function 'datalink_size':
capture.c:447: error: 'DLT_LINUX_SLL' undeclared (first use in this function)
capture.c:447: error: (Each undeclared identifier is reported only once
capture.c:447: error: for each function it appears in.)
capture.c: In function 'lookup_hostname':
capture.c:499: error: 'AF_INET' undeclared (first use in this function)
*** Error 1 in src (Makefile:277 'capture.o')
*** Error 1 in src (Makefile:174 'all')
*** Error 1 in /usr/src/sngrep-master (Makefile:231 'all-recursive')
#

**Comment by Kaian** [comment]
Hmm that seems the same error. Did you pull the last changes?

At least the DLT_LINUX_SLL should have gone :-m

-------- Mensaje original --------
De: Robert Johnson <notifications@github.com> 
Fecha: 25/03/2015  20:20  (GMT+01:00) 
Para: irontec/sngrep <sngrep@noreply.github.com> 
Cc: Kaian <Kaian@irontec.com> 
Asunto: Re: [sngrep] Make Error on OpenBSD amd64 (#40) 
 
I have no problem going back and forth; But on that note, let me see what I can do about getting you access to a system - it may be this weekend before I can pull my spare box out and put it together..

Here's the next output.

make

Making all in src
make all-am
if gcc -DHAVE_CONFIG_H -I. -I. -I. -g -O2 -MT capture.o -MD -MP -MF ".deps/capture.Tpo" -c -o capture.o capture.c; then mv -f ".deps/capture.Tpo" ".deps/capture.Po"; else rm -f ".deps/capture.Tpo"; exit 1; fi
In file included from capture.h:40,
from capture.c:35:
/usr/include/netinet/if_ether.h:137: error: field 'ea_hdr' has incomplete type
In file included from capture.c:35:
capture.h:99: error: expected specifier-qualifier-list before 'pthread_t'
capture.c: In function 'parse_packet':
capture.c:274: error: incompatible type for argument 1 of 'sip_load_message'
capture.c: In function 'capture_close':
capture.c:304: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_launch_thread':
capture.c:321: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_set_bpf_filter':
capture.c:348: warning: passing argument 3 of 'pcap_compile' discards qualifiers from pointer target type
capture.c: In function 'datalink_size':
capture.c:447: error: 'DLT_LINUX_SLL' undeclared (first use in this function)
capture.c:447: error: (Each undeclared identifier is reported only once
capture.c:447: error: for each function it appears in.)
capture.c: In function 'lookup_hostname':
capture.c:499: error: 'AF_INET' undeclared (first use in this function)
*** Error 1 in src (Makefile:277 'capture.o')
*** Error 1 in src (Makefile:174 'all')
*** Error 1 in /usr/src/sngrep-master (Makefile:231 'all-recursive')

**Comment by ftwrobert** [comment]
I thought I did.. But apparently not; Here you go..

# make
Making all in src
make  all-am
if gcc -DHAVE_CONFIG_H -I. -I. -I.      -g -O2 -MT capture.o -MD -MP -MF ".deps/capture.Tpo" -c -o capture.o capture.c;  then mv -f ".deps/capture.Tpo" ".deps/capture.Po"; else rm -f ".deps/capture.Tpo"; exit 1; fi
In file included from capture.c:35:
capture.h:113: error: expected specifier-qualifier-list before 'pthread_t'
capture.c: In function 'parse_packet':
capture.c:182: error: dereferencing pointer to incomplete type
capture.c:184: error: dereferencing pointer to incomplete type
capture.c:185: error: dereferencing pointer to incomplete type
capture.c:186: error: dereferencing pointer to incomplete type
capture.c:186: error: dereferencing pointer to incomplete type
capture.c:187: error: dereferencing pointer to incomplete type
capture.c:188: error: dereferencing pointer to incomplete type
capture.c:274: error: incompatible type for argument 1 of 'sip_load_message'
capture.c: In function 'capture_close':
capture.c:304: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_launch_thread':
capture.c:321: error: 'capture_info_t' has no member named 'capture_t'
capture.c: In function 'capture_set_bpf_filter':
capture.c:348: warning: passing argument 3 of 'pcap_compile' discards qualifiers from pointer target type
*** Error 1 in src (Makefile:277 'capture.o')
*** Error 1 in src (Makefile:174 'all')
*** Error 1 in /usr/src/sngrep (Makefile:231 'all-recursive')
#

**Comment by Kaian** [comment]
Hi again,

Try pulling the last changes and make again. There should be some warnings, but sngrep is compiled successfully.

Most probably you must use -d argument to specified the capture device.

**Comment by Kaian** [comment]
Well It seems to compile, but not work as expected. Most probably related to pthread mutex issues :\

**Comment by Kaian** [comment]
`master` should work for BSD systems now.

Pull the latest changes and give it a try :)

**Comment by ftwrobert** [comment]
It has compiled successfully and working good so far; reading from a network device and from a pcap file both seem to work. 

Thank you!

**Comment by Kaian** [comment]
Nice!! Thanks to you :)
