### ISSUE TITLE
"Unable to handle linktype 276" for DLT_LINUX_SLL2

### ISSUE THREAD

**Issue by wdoekes** [irontec/sngrep#402]
Hi!

I got this on the new Ubuntu/Jammy pcaps on `-d any`:
```
# sngrep -I udp5060.pcap.00 
Unable to handle linktype 276
```
Looks like you're running into https://www.tcpdump.org/linktypes/LINKTYPE_LINUX_SLL2.html like I also did in https://github.com/ossobv/sipzamine/commit/1188e56cca5eda4634a0d50416e8a684be1aa8b2

Pardon me if this is fixed already, I only tested the 1.4.10 Ubuntu version. A quick GitHub search in sngrep did not turn up SLL2, so I figured you're still affected.

**Comment by Kaian** [comment]
Above commit should add compatibility with SLL2 link types, just skipping its 20 bytes header.

Feel free to test it and reopen the issue if it desn't work!

Thanks for reporting!
