### ISSUE TITLE
Sngrep 1.5.0 - When try to generate the configure script on CentOS7 return: configure.ac:1: error: Autoconf version 2.71 or higher is required

### ISSUE THREAD

**Issue by RodolfoCDSantos** [irontec/sngrep#409]
First of all I would like to thank you, Mr. Kaian and all contributors for creating this piece of art called SNGREP.

That said, here's my problem:
This is what I see when I try ./boostrap.sh:
Generating the configure script ...
configure.ac:1: error: Autoconf version 2.71 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: echo failed with exit status: 63

CentOS 7 is up to date and in the official repository the latest version is 2.69. I've tried compiling the Autoconf 2.71 
binaries and it still didn't work. Please help me to resolve this. Thank you in advance.

**Comment by Kaian** [comment]
Hi Rodolfo!

Thanks for your kind words! :)

I've run bootstrap without erros in a centos:7 docker container with autoconf 2.69:

```
[root@8d70e0fb0b10 sngrep]# ./bootstrap.sh 
Generating the configure script ...

[root@8d70e0fb0b10 sngrep]# autoreconf -V
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.


[root@8d70e0fb0b10 sngrep]# autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.


[root@8d70e0fb0b10 sngrep]# automake --version
automake (GNU automake) 1.13.4
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

I don't see where 2.71 is even defined in configure files.
You can try running each bootstrap command individually and check which one is giving you that error:

```
aclocal
autoconf
autoheader
automake --add-missing --copy 2>/dev/null
```

You have also binaries in [copr](https://copr.fedorainfracloud.org/coprs/irontec/sngrep/) if you want to skip the compile phase

Regards!

**Comment by Kaian** [comment]
Closed due to lack of feedback. Feel free to reopen if you have more info!
