### ISSUE TITLE
sngrep display : the last two characters of each line are missing

### ISSUE THREAD

**Issue by gilles0606** [irontec/sngrep#410]
hello,

I test on multiple linux, and with puttty and other terminal.
when an element is displayed on several lines the last two characters of each line are missing

![sample](https://user-images.githubusercontent.com/38776814/185786887-b8201cea-753f-41f0-992c-8e573c32b55a.jpg)

In this sample, refer, is displayer as : re--r, the fe missing.

i reproduce this on all version and all my linux box.

a idea  to solve ?

raw display have the same problem.
but, save the packet text, all characters is present.

Thanks

**Comment by gilles0606** [comment]
I make a patch for correction for me...

in the file src/curses/ui_manager.c

Change in function draw_message_pos :

Original : 
        // Move to the next line if line is filled or a we reach a line break
        if (column > width || payload[i] == '\n') {
            line++;
            column = 0;
            continue;
        }

Patch : 
        // Move to the next line if line is filled or a we reach a line break
        if (column > width || payload[i] == '\n') {
            line++;
            if(column > width)
            	i=i-2;
            column = 0;
            continue;
        }
 
just add 
            if(column > width)
            	i=i-2;

and work fine with me.

but I don't know if I'm fixing a bug that's only in my house because of something else, or if it's really a bug?
your opinion ?

**Comment by Kaian** [comment]
Hi @gilles0606 

Thanks for reporting!!

Looks like the new line logic was not correct and was skipping characters when it shouldn't.

Above commit should fix the problem both in preview and raw message display. Give it a try if you have some time.

Regards

**Comment by gilles0606** [comment]
Hi,

I confirm that it works fine.
THANKS.

(with the new identity fields, multilines are mandatory and a single missing character makes a bad signature)

I switch back from sngrep-mypatch to sngrep  ;-)

Thanks.

**Comment by gilles0606** [comment]
Thanks
