### ISSUE TITLE
Instalando sngrep en centOS 7

### ISSUE THREAD

**Issue by Porygonzzz** [irontec/sngrep#413]
Saludos,

Mi problema consiste  en que sigo los pasos de :

1.- Clonar el repo en el centOS 7 de mi máquina virtual 
2.- Ejecutar ./bootstrap.sh
3.- Al ejecutar ./configure me da como resultado  lo siguiente:

configure: error:  You need to have libpcap installed to compile sngrep.

y no se como debo instalarlo para que pueda reconocerlo

Agradecería mucho su apoyo

**Comment by Kaian** [comment]
Hi!

Github project language is english, please avoid other languages when opening issues. Use a translator, there is no problem in the text is not accurate, we'll probably understand :)

You can follow wiki page for centos to install dependencies: https://github.com/irontec/sngrep/wiki/Building#centosfedora
You can also get binary files if you dont want to compile from sources: https://github.com/irontec/sngrep/wiki/Installing-Binaries#fedora--centos--rhel-linux

Regards!
