### ISSUE TITLE
Header Line-Wrap Truncating Characters

### ISSUE THREAD

**Issue by etgcloudvoicesupport** [irontec/sngrep#414]
SNGREP is truncating 2 characters from headers every time it line wraps, making it difficult to copy/paste long headers accurately (such as stir/shaken Identity headers)

for example take this identity header:

Identity: fdafsdfjoijeRERERafpaeQfFEJafjkl.fdaljearljfojapsodfjpuaERFl3k4ALSDfjlo3jr1.345kjlkjaerpuAEerljoia;info=<https://example.com/cert.pem>;alg=ES256;ppt=shaken

if sngrep line-wraps after the "ljfo" this is what it looks like: 

Identity: fdafsdfjoijeRERERafpaeQfFEJafjkl.fdaljearljfo
psodfjpuaERFl3k4ALSDfjlo3jr1.345kjlkjaerpuAEerljoia
nfo=<https://example.com/cert.pem>;alg=ES256;pp
shaken

and if you look closely there are 2 missing characters for every row after it wraps..

This could be an issue with my terminal environment but I have tried with multiple terminal emulators ZOC6, Putty, and MobaXterm.

**Comment by Kaian** [comment]
This is probably a duplicated from #410

Could you check if this is still occurs in 1.6.0?

Regards

**Comment by etgcloudvoicesupport** [comment]
My bad, I looked through the issues but forgot to look at closed issues. The latest release does fix it, Buster only has 1.4.6.

**Comment by Kaian** [comment]
You can get 1.6.0 debian buster binaries from Irontec Debian Repository. Not sure what version is available at buster-backports.

https://github.com/irontec/sngrep/wiki/Installing-Binaries#debian
