### ISSUE TITLE
displayalias option missing in documentation

### ISSUE THREAD

**Issue by m-j-b** [irontec/sngrep#419]
The `displayalias` option as mentioned here https://github.com/irontec/sngrep/issues/282 is missing from the wiki https://github.com/irontec/sngrep/wiki/Configuration#options .  The user can add `alias` entries to the config file but unless `displayalias` is set to 'on' they will not work.

**Comment by Kaian** [comment]
Hi @m-j-b 

Wiki is open so everyone can fix and update any missing information.

Feel free to add the entry for `displayalias` or any other setting not documented.

Thanks a lot in advance!

**Comment by Kaian** [comment]
Thanks!!
