### ISSUE TITLE
Unknown file format

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#421]
while trying to open  pcap file in sngrep it throws an message (Couldn't open pcap file /home/saja3825/HSS_S6A_MSG.pcap: unknown file format) how to open this pcap
[HSS_S6A_MSG.pcap.gz](https://github.com/irontec/sngrep/files/10287127/HSS_S6A_MSG.pcap.gz)

**Comment by Kaian** [comment]
Hi @sajai20 

```
$ file HSS_S6A_MSG.pcap 
HSS_S6A_MSG.pcap: Snoop capture file - version 2 (Ethernet)
```

This file type doesn't seem to be supported by libpcap, so you won't be able to open it with sngrep (or tcpdump, ngrep or other tool relaying on libpcap to open files).

You can try opening the file in Wireshark and save as Wireshark/tcpdump/... - pcap.

There is no SIP messages in the capture, but at least you can open it (also with other tools.)

Regards!

**Comment by sajai20** [comment]
thank you kaian
