### ISSUE TITLE
100 cpu when ssh connection disconnected

### ISSUE THREAD

**Issue by isrlgb** [irontec/sngrep#424]
hi
using the latest version
if  running sngrep and the ssh connection drops sngrep continues to run and 100% cpu

root      3015 91.5  3.9 357416 324164 ?       Rl   Jan05 3028:35 sngrep -c
![image](https://user-images.githubusercontent.com/20945429/211170923-886237c4-98c8-479d-a538-e0f98392f7b0.png)
![image](https://user-images.githubusercontent.com/20945429/211170947-8e483d42-7a6d-4e8f-9c18-de5d26552182.png)

what can be done

**Comment by Kaian** [comment]
Hi!

There is no much you can done at that point, apart from killing the process.
I recommend creating an alias for sngrep to avoid running for too long periods.

    alias sngrep='timeout 600 sngrep' 

Or something like that to autostop sngrep after 10 minutes. 

Regards

**Comment by isrlgb** [comment]
the idea is nice but isnt it a bug that with a orphaned sngrep where its trying to ouput to the tty that is gone?

**Comment by Kaian** [comment]
Hi!

I've done some testing and looks like sngrep receives SIGCONT signal when parent ssh connections dissapears, si I have add it the signal exit handler.

Not sure if this will work in every scenario (I have tested killing the client connection), but let's give it a try.

This will be included in sgrep 1.7.0

Thanks for the report @isrlgb !!

**Comment by isrlgb** [comment]
Thank you very much!

**Comment by denyspozniak** [comment]
@Kaian we usually keep sngrep running in the subshell via screen, could this commit affect that?

**Comment by Kaian** [comment]
@denyspozniak It may affect. For example, running sngrep in background with & at the end seems to work, but halting a running sngrep with `Ctrl+Z` and sending it to background with `bg`, will stop it.

As far as I understand, _screen_ is the one being run in background and not sngrep, so no signal should be received in that case, but I would recommend to try the above commit and report any finding.

Regards

**Comment by isrlgb** [comment]
i have compiled from git and it fixed the problem for me but still runs in
screen so that looks ok
