### ISSUE TITLE
trace sip packet incorrect , loss  TRANSFER / REFER message

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#43]
trace sip packet incorrect , loss  TRANSFER / REFER message

**Comment by Kaian** [comment]
Most probably related with #44

**Comment by michael2009** [comment]
from A invite B , B answer with 200 OK
next A give reinvite or refer
but sngrep not show reinvite or refer , lost 
test with new git version

**Comment by Kaian** [comment]
Duplicate #44

**Comment by michael2009** [comment]
yes. solved for REFER  cap lost issue
