### ISSUE TITLE
Error: Irontec RPMs repository - RHEL9 based OS

### ISSUE THREAD

**Issue by adora-tech** [irontec/sngrep#437]
Hello,

In my case I use AlmaLinux 9.2.

`Errors during downloading metadata for repository 'irontec':
  - Status code: 404 for http://packages.irontec.com/centos/9/x86_64/repodata/repomd.xml (IP: 151.80.176.3)
Error: Failed to download metadata for repo 'irontec': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
`

Thank you,
Iulius Ciorica

**Comment by Kaian** [comment]
Hi @adora-tech !

Irontec RPM repositories are no longer maintained.

Please check wiki to configure COPR repositories instead: https://github.com/irontec/sngrep/wiki/Installing-Binaries#fedora--centos--rhel-linux

Thanks!
