### ISSUE TITLE
trace sip packet incorrect , loss  PRACK  message

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#44]
trace sip packet incorrect , loss  PRACK  message

**Comment by Kaian** [comment]
Hi @michael2009!

Can you provide more info about the problem?

What version are of sngrep you using?
Doesn't they apper in the arrow flows? or the arrow appear without label?

Thanks a lot for reporting!!

**Comment by michael2009** [comment]
from A invite B , B give 183 + 100 rel 
next A give PRACK , B give 200 OK
but sngrep not show PRACK , lost 
test with new git version

**Comment by Kaian** [comment]
Could you provide a pcap file with PRACK not showing?

Thanks!

**Comment by michael2009** [comment]
can'nt upload pcap file .  give me your mail id or skype .

**Comment by michael2009** [comment]
my mail  michael@5gcall.com

**Comment by Kaian** [comment]
HI @michael2009,

You can send it to me at kaian@irontec,com

Best regards,

**Comment by Kaian** [comment]
Hi @michael2009,

Thanks a lot for the testing file. As you mention, there was some problems with a couple of request methods not being properly parsed.

I hope this will also fix #43 . Feel free to reopen if something is not working.

Thanks again for the patience and contribution!

**Comment by michael2009** [comment]
checked . PRACK cap issue solved
