### ISSUE TITLE
Dependency problem in debian/control file

### ISSUE THREAD

**Issue by SipSeb** [irontec/sngrep#443]
When refactoring the code to use libpcre2 instead of libpcre3, the runtime dependencies for the built debian package broke. There is no package named `libpcre2`, instead there are packages with UTF-8, UTF-16 and UTF-32 support.

Pull request https://github.com/irontec/sngrep/pull/442 fixes it.

At least on my system (Ubuntu Jammy), sngrep worked afterwards, and I checked Ubuntu and Debian package lists, the `libpcre2-8-0` package has been around for a while already.

**Comment by Kaian** [comment]
Hi @SipSeb !!

Thanks for the contribution!

We package sngrep from Debian squeeze onward, so propably we have to keep original dependency. Adding the new one seems oks to me.

Also, I though that dependencies should be added by `${shlibs:Depends}`, I'll try to check as soon as I have some spare time.


Regards!

**Comment by SipSeb** [comment]
Hi @Kaian,

I edited the PR as you suggested, didn't find the lib package names in distributions older than buster or focal when I checked. But more compatibility is better, I guess.

**Comment by Kaian** [comment]
Sweet, thanks!!
