### ISSUE TITLE
SNGREP display issue

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#445]
@Kaian Please observe that 2 bytes at the end of the line, are getting truncated while we reducing the screen width the below image shows the from header details properly 
![image](https://github.com/irontec/sngrep/assets/110714149/88011cfc-1275-4c87-bd34-14275d1ede76)
if i'm reducing the width of the screen the last two bytes getting truncated you can see that in the below image
![image](https://github.com/irontec/sngrep/assets/110714149/73b76934-bf59-445f-9d3c-746aa02e6e3c)
764 should we visible in the second line but i can see only 4, the number 76 is being truncated.

**Comment by Kaian** [comment]
Hi!

This looks like a duplicate from #410

What version of sngrep are you using?


Regards

**Comment by sajai20** [comment]
Hi kaian

i'm using 1.4.10 version

**Comment by Kaian** [comment]
Hi!

This is a duplicate then and it's already fixed.
Feel free to reopen if you can reprodude the issue in the latest version.

Regards!
