### ISSUE TITLE
Ubuntu Jammy package list out of date

### ISSUE THREAD

**Issue by kdanderso** [irontec/sngrep#448]
https://packages.irontec.com/ubuntu/dists/jammy/main/binary-amd64/Packages shows sngrep at version 1.6.0, but
https://packages.irontec.com/ubuntu/pool/main/s/sngrep only contains version 1.7.0

**Comment by Kaian** [comment]
I have re-exported jammy packages, so this should be fixed.

Thanks for reporting!!
