### ISSUE TITLE
open sngrep then crash . issue because have pptp ppp interface

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#45]
crash when run sngrep . 

sngrep[3506]: segfault at 0 ip 0000000000404a7c sp 00007ff883a83d38 error 4 in sngrep[400000+17000]

issue come when system with ppp device . maybe same issue when with tap, tun , vlan

**Comment by Kaian** [comment]
I assume you're using sngrep without arguments. There are some packets that are not properly handled by capture thread and make sngrep crash. I thought this could be solved in #42 but It seems not. 

As a workaround you can use BPF filters for capturing only SIP (will usually doesn't make sngrep to crash) using something like:

    sngrep port 5060


I'll try to find what those packets are, but as alway if you can provide a crashing pcap so I can debug offline, It would help a lot.

Thanks for reporting!

**Comment by michael2009** [comment]
yes . run  without arguments then issue . because i need dump call for ethX and pppX both type traffic 
if run 
sngrep -d ppp0 or  sngrep port 5060 then no issue

**Comment by Kaian** [comment]
Hi @michael2009 

Could you give it a try to `capture_frag` branch to test if still crashes?

Thanks for the testing

**Comment by Kaian** [comment]
Hi,

 I've found the problem. The logic that get local addresses crashed with this kind of interfaces.
 It should be fixed in `master` branch.

Thanks for your time

**Comment by michael2009** [comment]
solved. thanks
