### ISSUE TITLE
Pressing the ESC key doesn't return to the Call List but exits

### ISSUE THREAD

**Issue by tishige** [irontec/sngrep#454]
Hi
Ubuntu 22.04.2 LTS

When pressing the ESC key or 'q' in the message flow screen, the application often exits instead of returning to the Call List.
Although there are instances where it does return to the Call List screen, is there a difference?

Thanks
Ishi

**Comment by Kaian** [comment]
Hi!

What version are you using? I remember a bug like this but long long time ago. You can check running `sngrep --version`.

Also, could you try using the latest available package in Irontec Repositories and check if the problem still happens? 

https://github.com/irontec/sngrep/wiki/Installing-Binaries#debian--ubuntu

Regards

**Comment by tishige** [comment]
Hi Kaian,
You are right!
I thought I had the latest version because it said 'sngrep is already the newest version (1.4.10-1)' after I installed it with 'apt-get install sngrep'.
After building version 1.7.0 from the source,
I was able to return to the Call List by pressing ESC.
Thank you!!

Ishi


> Hi!
> 
> What version are you using? I remember a bug like this but long long time ago. You can check running `sngrep --version`.
> 
> Also, could you try using the latest available package in Irontec Repositories and check if the problem still happens?
> 
> https://github.com/irontec/sngrep/wiki/Installing-Binaries#debian--ubuntu
> 
> Regards
