### ISSUE TITLE
Please provide pre-compiled binaries (with embedded libraries)

### ISSUE THREAD

**Issue by fgadot** [irontec/sngrep#455]
This is a PR
Please provide pre-compiled binaries for both 64bits and 32 bits, with libraries embedded.
I'm working with some old technology here, and compiling sngrep for 32 bits is often challenging :/

**Comment by Wanninger** [comment]
...it would possibly also already help, if there would be an option, like e.g. "--enable-static". Then you could easily create a static compilation directly from the current branch.

**Comment by Kaian** [comment]
Hi!

Static binaries for i386 and amd64 are available at https://packages.irontec.com/binaries/

Please, check if they work in your environment.
 
Best regards

**Comment by Wanninger** [comment]
Works perfectly in my cases - thank you, very much

**Comment by fgadot** [comment]
Working for me. Thank you.
