### ISSUE TITLE
Adding 64-bit ARM to packages

### ISSUE THREAD

**Issue by kohenkatz** [irontec/sngrep#456]
First, thank you for this extremely useful tool!

The Ubuntu package repository currently has support for i386, amd64, and armhf (although the Wiki page says only i386 and amd64, I see a handful of armhf packages in the repository). With the growing popularity of arm64 (e.g. Amazon AWS Graviton, Apple m1/m2), it would be extremely useful if we can have arm64 packages available too.

What would it take for us to get arm64 builds working?

**Comment by Kaian** [comment]
Hi @kohenkatz !

Our packages seems to use Ubuntu Desktop repositories for builidng, and for most releases they only support amd64 and i386. For example, for jammy:

http://en.archive.ubuntu.com/ubuntu/dists/jammy/

Older releases seem to support other architectures, for example vivid:

http://old-releases.ubuntu.com/ubuntu/dists/vivid/

Maybe arm64 is supported in another repositories (Ubuntu Server?), not sure if changing the repository will break compatibility with Ubuntu Desktop, although probably sngrep is more designed for ubuntu server than desktop.

Regards!

**Comment by kohenkatz** [comment]
Hello @Kaian,

[Ubuntu's build of sngrep](https://packages.ubuntu.com/jammy/sngrep) is available for the following architectures: amd64, arm64, armhf, ppc64el, riscv64, and s390x (but *not* i386 anymore). I was using it on arm64 myself, but it's an old version - 1.4.10 - that suffers from the segfault issue described in #389. (They have 1.5 available for 22.10, 1.6 for 23.04, and it looks like 1.7 will be in 23.10, but that doesn't help for 22.04 LTS.)

Packages for architectures other than amd64 (and whatever i386 are left from old Ubuntu releases) are hosted on http://ports.ubuntu.com/ instead of http://archive.ubuntu.com/.

For example, here are the `sngrep` packages built by Ubuntu:

- amd64 (and i386 for 1.2 and 1.4) - http://en.archive.ubuntu.com/ubuntu/pool/universe/s/sngrep/
- arm64 (and other architectures) - http://ports.ubuntu.com/pool/universe/s/sngrep/

**Comment by Kaian** [comment]
Hi @kohenkatz,

Thanks a lot for all the information of Ubuntu repositories. I was able to configure the build matrix for Debian & Ubuntu to include arm64 and armhf for LTS releases of these distributions. This is the current build matrix: https://jenkins.irontec.com/job/sngrep/job/sngrep-binaries/

Please check if Irontec repositories now provide the packages you need.

Best regards
