### ISSUE TITLE
found new bug . crash 

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#46]
[23270.047015] sngrep[22010]: segfault at 7fbc06b15ba8 ip 00007fbc0767436d sp 00007fbc06ad0ea0 error 4 in libpcap.so.1.3.0[7fbc0766a000+2f000]

test use hping3 with sip flood to sip server . and run sngrep at sip server

hping3 -i u1000 -2 --spoof 192.168.1.12  -p 5060  192.168.1.1  -E register -d 650

file   'register' with 650 bytes . one register cap

**Comment by Kaian** [comment]
Hi michael

I was unable to reproduce this issue. I've captured more than 1000 registers with the same payload without crash. 

Can you provide a debug backtrace or a pcap that makes sngrep crash?

Thanks!

**Comment by Kaian** [comment]
Are you still able to reproduce this issue with sngrep 0.4.1 ? 
Can you provide register file you're using with hping?
