### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#460]
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with OpenSSL support.
 * Compiled with EEP/HEP support.
i have compiled sngrep with the following option now i need to add support for ipv6 how to change it

**Comment by Kaian** [comment]
Hi,

You have to recompile using `--enable-ipv6` flag when running ./configure

Check the wiki for a complete list of configuration flags

https://github.com/irontec/sngrep/wiki#building-from-sources
