### ISSUE TITLE
Starting sngrep with -F doesn't work

### ISSUE THREAD

**Issue by SipSeb** [irontec/sngrep#461]
Just a minor glitch: The docs say, you can use `-F` to tell sngrep to ignore the config. This used to work in older versions, but now, my sngrep tells me this:
```
root@hostname:/# sngrep -V
sngrep - 1.7.0
Copyright (C) 2013-2018 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with GnuTLS support.
 * Compiled with Wide-character support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with IPv6 support.
 * Compiled with EEP/HEP support.

Written by Ivan Alonso [aka Kaian]
root@hostname:/# sngrep -F
-F option requires an argument.
```

Starting it with `--no-config` does work, though.

**Comment by Sivasundareswaran** [comment]
you have to give config file name then only it will work 

example :
sngrep -F config_file.conf

**Comment by Kaian** [comment]
Hi!

This error was introduced when the `-T` flag was added to convert to text. It will be fixed in next release.

Sorry for the inconvenience and thanks for reporting!
