### ISSUE TITLE
sngrep1.6.0 Display disorder

### ISSUE THREAD

**Issue by JackMa2023** [irontec/sngrep#464]
system: ubuntu22.04 
sngrep1.6.0 Display disorder.  The specific situation is shown in the figure：
![image](https://github.com/irontec/sngrep/assets/129134671/bb3a16bd-9d18-4936-83e7-b6f3b2a08920)

The same question in sngrep1.7.0.

**Comment by Kaian** [comment]
Hi @JackMa2023 

I think this is a duplicate from https://github.com/irontec/sngrep/issues/290

Regards!

**Comment by JackMa2023** [comment]
@Kaian ,  thanks,  I use the xshell for win11.  version is 7.0.0141.  I  will use other terminated or other version to try.   i will  respond    the result to u.

**Comment by JackMa2023** [comment]
> Hi @JackMa2023
> 
> I think this is a duplicate from #290
> 
> Regards!

thank u again,
 i use sngrep success  on MobaXterm.   Display disorder was disappeared.
xshell7 is the latest version.  so it not fit  sngrep1.6 or sngrep1.7.

**Comment by Kaian** [comment]
Good to know!
