### ISSUE TITLE
Ctrl-z (suspend) terminates sngrep

### ISSUE THREAD

**Issue by enlaichu** [irontec/sngrep#468]
I'm running sngrep 1.6.0.

When I suspend sngrep using Ctrl-Z on my Debian server, and then restore it using fg, sngrep terminates.

I used to be able to suspend and un-suspend sngrep in older versions.

**Comment by Kaian** [comment]
Hi!

There has been some rework on signal handling in a recent pull request (#459), could you give it a try compiling from master? If it works, then this is already fixed for next release.

Thanks!
