### ISSUE TITLE
PgUp  / PgDn steps not updating

### ISSUE THREAD

**Issue by enlaichu** [irontec/sngrep#469]
I'm running sngrep 1.6.0.

When I change the steps for PgUp / PgDn in the Settings -> Call Flow to anything other than the default 4 (e.g. change it to 50), it doesn't reflect. Even after I Save and Accept the settings. 

The PgUp / PgDn still only moves 4 steps at a time.

**Comment by Kaian** [comment]
Hi!

This is a duplicate from #457

Thanks for reporting!
