### ISSUE TITLE
HEP server not working properly

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#470]
Hi

In server 192.168.151.94 we have sngrep installed now we need to route sip packets from 94 server to 144 server in 94 server i have used a command ./sngrep -H udp:192.148.151.144:9060 --no-interface -q and in 144 server i have used ./sngrep -L udp:192.148.151.144:9060 to listen to packet and display still i cannot see any packets in 144 sngrep when i'm exiting the sngrep it's throwing an error like Error binding address: Cannot assign requested address how to over come this issue, what i'm doing wrong here is my configuration is correct.

**Comment by Kaian** [comment]
Hi @sajai20 

The process seems correct, but the error you're receiving is relevant. It means it can not reserve port 9060 for reading packets sent by .94 server. There is another process that is already listing in that port, check with `ss` or `netstat` to check what service is already binded to 9060 or try changing the port in both servers (like 19060).


Regards

**Comment by sajai20** [comment]
i tried to implement in different server now sngrep throwing an error EEP server: failed getaddrinfo() for 10.212.178.19:9060 how to solve this

**Comment by Kaian** [comment]
Is 10.212.178.19 a valid ip in that server? you can also listen in all addresses

    ./sngrep -L udp:0.0.0.0:9060

**Comment by sajai20** [comment]
hi @Kaian  

My requirement is i need to send packets from 8 different server to single server and view all the packets in one server but i cannot use same port every client server due to binding issue how can i solve it using HEP server concept in sngrep can we achieve it -H 0.0.0.0:port in all the eight server and listen in a single server -L 0.0.0.0:port is that possible

**Comment by Kaian** [comment]
In the server receiving the HEP packets run:

    sngrep -L udp:0.0.0.0:9060 

Take note of that server IP address (p.e. 192.168.0.1) and run in the other 8 servers:

    sngrep -H udp:192.168.0.1:9060 

Best regards,

**Comment by Kaian** [comment]
Closes due to lack of activity. If the issue still persist feel free to reopen.
