### ISSUE TITLE
sngrep process still work in background in case i close ssh console.

### ISSUE THREAD

**Issue by ynasida** [irontec/sngrep#472]
Hello,

sngrep 1.6.0. Installed via apt install.
I updated to debian 12 and noted that sngrep process still work in background in case i close ssh console (or in case of timeout because of issue with ISP). It is very uncomfortable. Sngrep processes can spend all RAM memory and be the reason of issue at production servers. I noted that old version of sngrep (1.4.8) does not have this problem at Debian 11.

Please advice.

**Comment by Kaian** [comment]
Hi @ynasida !

This was implemented in sngrep 1.7.0. See https://github.com/irontec/sngrep/releases/tag/v1.7.0

 You can get that version from debian bookworm backports repository or irontec debian packages repositories https://github.com/irontec/sngrep/wiki/Installing-Binaries

Best regards,
