### ISSUE TITLE
mismatching of library 

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#476]
i'm trying to bring up sngrep it's expecting libpanel.so.5 but in my server i have  libpanel.so.6 and libpanel.so.6.1 so i have made a soft link but sngrep dumping core while i'm trying to exit the application,why it's expecting libpanel.so.5 how can i change esngrep tp expect libpanel.so.6 instead of libpanel.so.5

**Comment by linuxmaniac** [comment]
Install the proper version built for your distribution.

**Comment by Kaian** [comment]
Hi!

This will require a bit more information. How are you installing sngrep? Using packages for your distribution like linuxmaniac suggests? Building from sources? Copying the binary from another installed system?


There are binaries versions for latests Debian, Ubuntu, Fedora, etc.

https://github.com/irontec/sngrep/wiki/Installing-Binaries

Regards
