### ISSUE TITLE
crash when cap TLS call in

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#48]
crash when cap TLS call in .
sngrep -k server.key  -I xxxx.pcap
i had upload pcap file and ssl key

**Comment by Kaian** [comment]
Hi michael,

 Your SSL connection is using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA  cipher.
 Right now sngrep only supports TLS_RSA_WITH_AES_128_CBC_SHA and 
TLS_RSA_WITH_AES_256_CBC_SHA ciphers.

 Anyway It should not crash, so I will at least fix that issue.

Best regards,
