### ISSUE TITLE
Setting TERM to xterm-256color will not open sngrep

### ISSUE THREAD

**Issue by patrick330602** [irontec/sngrep#482]
When the TERM is set to `xterm-256color`, it will say: `Error opening terminal: xterm-256color.`
I have to manually set the TERM to `xterm` to open sngrep. 
The system is Red Hat Enterprise Linux 8.8 (Ootpa), with ncurses 6.1-9.20180224.

**Comment by Kaian** [comment]
Hi!

That error is thrown by ncurses itself and as far as I know there is nothing we can do appart from setting the TERM variable to xterm before calling initscr, but I prefer to let the user to set those variables so your workaround for this problem seems legit to me.

Best regards
