### ISSUE TITLE
sngrep not opening in MacOS

### ISSUE THREAD

**Issue by patrick330602** [irontec/sngrep#483]
I installed it via Homebrew, and it tells me `Couldn't open device any: ioctl(SIOCIFCREATE): Operation not permitted` when I try to open it. 
Using MacOS Sonoma 14.4.1 (Intel machine).

**Comment by Kaian** [comment]
Hi,

You need the appropiate permissions to capture from a network device. Be sure your user is properly configured or you are using root user.

Opening pcap files does not require any permission and you should be able to do it as regular user if you want to test.

Regards
