### ISSUE TITLE
Make file error while installing sngrep

### ISSUE THREAD

**Issue by sajai20** [irontec/sngrep#484]
I'm trying to install sngrep in 8.6 linux server but while trying to make i could see the below mentioned error how to get rid of this below mentioned error

capture.c:1211:1: fatal error: opening dependency file .deps/sngrep-capture.Tpo: Permission denied

**Comment by Kaian** [comment]
Hi,

This seems a problem in your enviroment. It looks like you have used root (or other) user to compile sngrep at some point and now you're trying to overwrite that files as a regular user, that can not access that generated files.

Please try to compile as a regular user and only install as root user:
See: https://github.com/irontec/sngrep/wiki/Building#compiling-the-sources

Best regards
