### ISSUE TITLE
Dependencies problem on Ubuntu 24.04!

### ISSUE THREAD

**Issue by ducarpit** [irontec/sngrep#485]
Hi all,
will you provide a specific repository for the new Ubuntu 24.04 Noble Numbat?
I tried to install sngrep with the Ubuntu 22.04 repository (the one for the 24.04 are not available yet) but there are some problems with the dependencies, specific with the libncursesw and libtinfo, it seems sngrep required an older versione than the ones in the official Ubuntu 24.04 repositories.
To solve, i installed by hand the required libraries in the right versions and then the installation works.
Thank you so much
Christian

**Comment by Kaian** [comment]
Hi Christian

I will try to add noble to the list of Irontec Debian repositories for the next release, but you should be able to download sngrep from official Ubuntu repositories (at least 1.8.0)

https://packages.ubuntu.com/noble/sngrep

Best regards!

**Comment by Kaian** [comment]
Hi Christian,

From sngrep 1.8.2 onwards, latest release will be available in Irontec repositories for Ubuntu Noble release.

Follow [wiki](https://github.com/irontec/sngrep/wiki/Installing-Binaries#debian--ubuntu) instructions to configure repositories and public key.


Best regards!
