### ISSUE TITLE
Process keeps running when closing ssh connection

### ISSUE THREAD

**Issue by bmachens** [irontec/sngrep#488]
Hi,
we observed that the sngrep process stays when closing/losing the ssh connection to the system

OS: Debian 12 Bookworm 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
SNGREP:  1.6.0-1

How to reproduce

- Connect from Windows via putty to the VM (Debian 12, headless)
- Open sngrep
- Close the putty window (maybe confirm warning, that closing the window, closes the connection)

Depending on your network traffic, the sngrep process will grow in RAM and/or CPU usage

It looks like, that just the sngrep viewer is closed, but the capturing is still running
Can somebody verify this behaviour?

Regards

**Comment by davemidd** [comment]
Is this not the same as https://github.com/irontec/sngrep/issues/487 ?

**Comment by Kaian** [comment]
This was fixed in 1.7.0 https://github.com/irontec/sngrep/releases/tag/v1.7.0

Please try upgrading your sngrep and check if the problem can be reproduced.

Best regards!

**Comment by bmachens** [comment]
> Is this not the same as #487 ?
Filter was on "open issue". thats why i missed #487 -_-

1.7.0 is part of bookworm-backports, not in baseline bookworm (theres only 1.6.0)

Thanks
