### ISSUE TITLE
remove use of libgcrypt-config

### ISSUE THREAD

**Issue by linuxmaniac** [irontec/sngrep#492]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071954

```
sngrep uses libgcrypt-config to locate libgcrypt. This breaks
against libgcrypt 1.11 which does not ship libgcrypt-config anymore.
Please use pkg-config/pkgconf instead.
```

**Comment by Kaian** [comment]
Hi @linuxmaniac 

Thanks for the info!

I'll try to adapt the configure template to use pkg-config if libgcrypt-config is not found to keep compatibility with older systems. 

Regards!

**Comment by ametzler** [comment]
Just to add some context: libgcrypt added a pkg-config file in version 1.8.5 which was released in August 2019.

**Comment by Kaian** [comment]
Hi!

Above PR adds support for searching libgcrypt flags using pkg-config, keeping libgcrypt-config as fallback for older systems (p.e.: debian buster and older).

Hope it fixes the problem!

Best regards

**Comment by linuxmaniac** [comment]
```
Uploading to ftp-master (via ftp to ftp.upload.debian.org):
  Uploading sngrep_1.8.2-1.dsc: done.
  Uploading sngrep_1.8.2.orig.tar.gz: done.
  Uploading sngrep_1.8.2.orig.tar.gz.asc: done.
  Uploading sngrep_1.8.2-1.debian.tar.xz: done.
  Uploading sngrep_1.8.2-1_amd64.buildinfo: done.
  Uploading sngrep_1.8.2-1_source.changes: done.
Successfully uploaded packages.
```

Thanks!
