### ISSUE TITLE
Question: Input PCAP --> Filter --> Output PCAP

### ISSUE THREAD

**Issue by pksml85** [irontec/sngrep#494]
My sngrep version:

> sngrep - 1.8.1
> Copyright (C) 2013-2018 Irontec S.L.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>  * Compiled with OpenSSL support.
>  * Compiled with Wide-character support.
>  * Compiled with Perl Compatible regular expressions support.
>  * Compiled with EEP/HEP support.
> 
> Written by Ivan Alonso [aka Kaian]

I want sngrep to load in a PCAP file and write a filtered output PCAP file. The input file is from tcpdump and is capturing SIP packets in HEP format from my PBX.

Here, I'm using a match expression to exclude any OPTIONS packets:
`sngrep -E -N -iv "cseq: [0-9]+ OPTIONS" -I tcpdump.pcap -O output.pcap`

Can sngrep write a filtered output file? Thanks!

Edit: Changed title and description of issue.

**Comment by pksml85** [comment]
Nevermind. sngrep has this capability and it's working just as it should. My mistake. Thanks!

**Comment by pksml85** [comment]
OK... I figured out the actual issue.

When a PCAP file requires EEP parsing (the -E option), the match expression will NOT be applied.
Hence this example originally given would not apply the match expression:
`sngrep -E -N -iv "cseq: [0-9]+ OPTIONS" -I tcpdump.pcap -O output.pcap`

A clunky workaround is to first perform EEP parsing. This workflow will produce the desired results:
`sngrep -E -N -I tcpdump.pcap -O eep-parsed.pcap`
`sngrep -N -iv "cseq: [0-9]+ OPTIONS" -I eep-parsed.pcap -O no-options.pcap`

Is it possible to apply match expressions when EEP parsing being performed as well? That way it will only require a single command.

**Comment by Kaian** [comment]
Hi @pksml85

While trying to reproduce this issue I've found that sngrep is not properly saving captured HEP packets from the wire. First of all, all captured packets should retain the same bytes in the save file (if they are fragmented or segmented, they will be saved in that way too). So if you capture HEP from the network interface, the save file will also contain HEP packets. I have added two commits in `master` branch that aims to fulfill this requirement. 

I've generated a pcap file with HEP data, sending the [PCAP used for testing](https://github.com/irontec/sngrep/blob/master/tests/aaa.pcap) while capturing with tcpdump in another shell:

```
(shell 1) # sngrep -I tests/aaa.pcap -H udp:127.0.0.1:9060 -N
Dialog count: 6
```

```
(shell 2) # tcpdump -i any -w tcpdump.pcap port 9060
tcpdump: data link type LINUX_SLL2
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
^C41 packets captured
82 packets received by filter
0 packets dropped by kernel
```

This generates a PCAP file with HEP contents (4 INVITE dialogs and 2 REGISTER).
Filtering out the REGISTER dialogs using the command in the issue description only saves the INVITEs in the new PCAP file.

```
# sngrep -E -N -iv "cseq: [0-9]+ REGISTER" -I tcpdump.pcap -O filtered.pcap
Dialog count: 4
```

These paket should be the same as the ones present in the original tcpdump.pcap file (HEP packets):
```
# sngrep -E -I filtered.pcap -N
Dialog count: 4
```

If you can compile from sources and give it a try to the latest master commits, it would be highly appreciated.

Best regards and thanks for reporting!

**Comment by pksml85** [comment]
This looks great!

```
demo@voipbox:~ # sngrep -E -N -iv "cseq: [0-9]+ OPTIONS" -I 2024-07-21-tcpdump.pcap -O 2024-07-21-tcpdump.current_sngrep.no_options.pcap
Dialog count: 194

demo@voipbox:~ # ./irontec-sngrep-6ee2c9c/src/sngrep -E -N -iv "cseq: [0-9]+ OPTIONS" -I 2024-07-21-tcpdump.pcap -O 2024-07-21-tcpdump.up_to_date_sngrep.no_options.pcap
Dialog count: 194

demo@voipbox:~ # l *.pcap* -t
-rw-r--r-- 1 tcpdump tcpdump 345473024 Jul 25 09:03 2024-07-21-tcpdump.pcap
-rw-r--r-- 1 demo    demo     59941589 Jul 25 09:02 2024-07-21-tcpdump.up_to_date_sngrep.no_options.pcap
-rw-r--r-- 1 demo    demo    348816655 Jul 25 09:02 2024-07-21-tcpdump.current_sngrep.no_options.pcap
``` 

Two more somewhat-unrelated questions:
1) Could it be possible to open a PCAP file (doing EEP parsing) AND listen to a UDP port? 

Here's why this would be helpful: I've been leaving sngrep open long-term so I have historical data I can look at from my PBX, and this consumes a great amount of memory. If I could open a PCAP file AND listen to a UDP port, then sngrep could stay current with SIP requests.

2) I'm using putty with pretty much the default settings on Windows 8.1 and Windows 10. I'm SSH-ing into a Debian 12 box. When pressing the Home and End keys on my keyboard, sngrep asks me if I want to quit. The 7 & 1 on the numeric keypad, which are labeled Home and End, do nothing. Page Up/Down skips down a few dialogs as expected, while the 9 & 3, which are labeled PgUp and PgDn, do nothing.

Is there a way that you know of where the Home and End keys will go to the beginning and the end of the dialogs in sngrep?
(BTW, the Home and End keys work properly in other applications, like nano.)

**Comment by Kaian** [comment]
Hi!

Good to know the commits fixed the problem.

> Could it be possible to open a PCAP file (doing EEP parsing) AND listen to a UDP port?

Looks like you can read from a file and capture HEP from a network device (p.e.: sngrep  -E -I file -d device), but it doesn't allow reading from a file and starting HEP Listener mode (p.e.: sngrep -E -I file -L udp:127.0.0.1:9060). Maybe it's something not to hard to enable, but I should be discussed in another feature-request issue.

> I'm using putty with pretty much the default settings on Windows 8.1 and Windows 10. I'm SSH-ing into a Debian 12 box. When pressing the Home and End keys on my keyboard, sngrep asks me if I want to quit. The 7 & 1 on the numeric keypad, which are labeled Home and End, do nothing. Page Up/Down skips down a few dialogs as expected, while the 9 & 3, which are labeled PgUp and PgDn, do nothing.

I'll try to reproduce this, but [some](https://superuser.com/questions/94436/how-to-configure-putty-so-that-home-end-pgup-pgdn-work-properly-in-bash) [fast](https://stackoverflow.com/questions/55357479/how-to-process-key-home-and-key-end-reliably-under-ncurses) [google searchs](https://stackoverflow.com/questions/78629326/ncurses-c-home-and-end-keys) mention TERM environment variable as something relevant. We could also create a new issue with Home and End keys not working in Putty for future reference.

Best regards and thanks for the testing!
