### ISSUE TITLE
Debian 12 libssl problem

### ISSUE THREAD

**Issue by dm-msk** [irontec/sngrep#500]
Hello

# sngrep
sngrep: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

# dpkg -l | grep sngrep
ii  sngrep                                           1.8.2-1~bpo12+1                           amd64        Ncurses SIP Messages flow viewer

# dpkg -l | grep libssl
ii  libssl-dev:amd64                                 3.0.14-1~deb12u2                          amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.1:amd64                                  1.1.1n-0+deb11u5                          amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:amd64                                    3.0.14-1~deb12u2                          amd64        Secure Sockets Layer toolkit - shared libraries

**Comment by Kaian** [comment]
Hi!

This looks like a problem in the Official Debian 12 backports package.

Maybe @linuxmaniac can assist you here or redirect you to the correct bug reporting site of Debian.

Thanks in advance!

**Comment by dm-msk** [comment]
Thank you.
# whereis sngrep
sngrep: /usr/bin/sngrep /usr/local/bin/sngrep /usr/share/man/man8/sngrep.8.gz

/usr/bin/sngrep work with no issue

**Comment by Kaian** [comment]
Then the problem is that there is a local (probably compiled) version of sngrep that is not up to date with your system libraries. So this is not a problem in sngrep but your environment.

Please remove that local version and use official Debian version or recompile with your new system libraries.

Thanks Victor for your support!!
