### ISSUE TITLE
show wrong for rtp stream include STUN packet .

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#53]
show wrong for rtp stream include STUN packet

**Comment by Kaian** [comment]
Hi @michael2009 !

Thanks again for the test pcap file :)

The RTP packet detection has been improved in `master`.  Now It supports displaying multiple streams in different formats with one SDP setup. 

The problem in #52 should also be fixed. "Unknown" formats will be taken from SDP payload. If they are not "standard" and event not found in SDP the stream will be tagged as "Unassigned".

Thanks for reporting!
