### ISSUE TITLE
issue for payload type .

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#54]
![111](https://cloud.githubusercontent.com/assets/12387494/8888519/51538664-32e3-11e5-9d33-01b0df95c366.JPG)

**Comment by Kaian** [comment]
Hi!

It seams like an invalid pointer to garbage :(
Do you have a pcap file to easily reproduce this issue?

Thanks in advance!

**Comment by Kaian** [comment]
We haven't seen this problem while we were testing.
Can this problem be reproduced?
Is this happening to anyone else?

**Comment by michael2009** [comment]
please check mail . issue54.pcap . and other one more issue

**Comment by Kaian** [comment]
Hi @michael2009 

Thanks for the pcap test file!!

This problem is solved in `master`. I've done some memory fixes in capture process and they seem to solve this issue :)

**Comment by Kaian** [comment]
Hi!

This should be fixed in 0.4.2
