### ISSUE TITLE
too delay exit sngrep because cap too much rtp 

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#55]
Can add one option for show rtp sum only , but don'nt save rtp at memory . 
seem too slow and use much memory

**Comment by Kaian** [comment]
Hi michael!

That setting already exists. To disable RTP packet capture, you can set this option in your sngreprc file (`~/.sngreprc` or `/etc/sngreprc`):

    set capture.rtp off

It also can be changed using Settings window (press 'o' in main sngrep window)

If you have RTP capture disabled, you can enable it from command line (using `-r` argument), in case you need to save RTP sometimes :)

**Comment by Kaian** [comment]
Hi michael!

There was actually a bug with the mentioned setting. Try updating to the last `master` commit and check memory consumtions.

RTP arrows should be displayed but no RTP packet will be stored.
Beware: Even if you see RTP arrows, you only will be able to save SIP data to a new pcap file.
