### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by etamme** [irontec/sngrep#57]
not a real issue - just wanted to say that sngrep is fantastic, I really appreciate the work you have done on it.

**Comment by Kaian** [comment]
Glad to hear it is useful for others. We're always with improvements in mind so lets hope it becomes even better one day.

Thanks for your feedback!! :dancers:

**Comment by linuxmaniac** [comment]
Great work, indeed!!!  :laughing:

**Comment by jarrodb** [comment]
I think this ticket should be re-opened because the project is still fantastic...

**Comment by jungle-boogie** [comment]
This project get a  :100:
