### ISSUE TITLE
Capturing TLS with ECDHE-RSA-AES256-GCM-SHA384

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#59]
Hello,

are the deb files built with all ciphers of openssl? Or is a limitation in the code? I installed jessie deb and I see no packets for a sip client using ECDHE-RSA-AES256-GCM-SHA384. The capture was started before the client connected.

On another test server, where I connect with snom over tls, I can see the packets. The version here is compiled from last git master, as of few minutes ago.

Thanks.

**Comment by Kaian** [comment]
Hi @miconda!

 TLS decrypt is highly experimental. Right now we only support two ciphers (TLS_RSA_WITH_AES_128_CBC_SHA and TLS_RSA_WITH_AES_256_CBC_SHA) as commented on #48.

 I think it won't be hard to implement new ones, but I must setup an enviroment to test it properly.

 Glad to know someone uses the TLS decrypt feature!!

Best regards,

**Comment by miconda** [comment]
OK, I see, thanks for info -- then I will leave it as new feature/enhancement request.

**Comment by Kaian** [comment]
Hi!

I've been researching a bit about this issue. Not sure if it can be solved. According to [1] Ciphers usings ECDHE or DHE can not be decrypted even with the server private key :(
If you know any software that manages to do it, just let me know.

Thanks!

```
DHE and ECDHE provides Perfect Forward Secrecy(PFS), means session keys 
are not derived from private key. So the attacker can not decrypt the traffic even 
when he has the private key used in the session handshake.
In DHE(not DH) the session keys are calculated using the Random Numbers.
You can't decrypt the traffic using private key when DHE or ECDHE is used.
```

[1] http://security.stackexchange.com/questions/71309/it-is-possible-to-decrypt-https-with-the-private-public-pair-if-it-uses-dhe

**Comment by Kaian** [comment]
Hi!

I will close this for now as seems impossible to decrypt those ciphers, even with server private key data. Feel free to reopen if you think there's something I could do for ECDHE or DHE ciphers.

Anyway, thanks for reporting! :)

**Comment by jungle-boogie** [comment]
Yes, the purpose of forward secrecy is to prevent attacks on already captured data if the private key is obtained.

**Comment by miconda** [comment]
I found a discussion on the web when decryption was possible with tshark/wireshark by getting access to some logs from ssl library -- my computer crashed and I lost it before following up here, then I didn't have more time for it, but I will find it again and add it here just for the records.

**Comment by Kaian** [comment]
Nice! Thanks to both for the feedback ;)

**Comment by miconda** [comment]
Here is a link with some info:

  * https://ask.wireshark.org/questions/30290/decrypting-tls_ecdhe_rsa_with_aes_128_cbc_sha-and-tls_ecdhe_rsa_with_aes_128_gcm_sha256-using-sslkeylogfile

It is not clear at first quick read it if was a bug that wireshark couldn't decrypt it by having access to sslkeylogfile.

Anyhow, there is a need for the client or server to write that log file, which makes it out of scope from my point of view for now. So this comment is just for the records, not a request for feature anymore.
