### ISSUE TITLE
Feature request: navigation keys

### ISSUE THREAD

**Issue by miconda** [irontec/sngrep#60]
Hello,

wondering if others will find useful to have some keyboard shortcuts to jump at the top or at the bottom of the current view.

When loading a big pcap takes a while to scroll down to the last dialogs, which will be most recent ones, going back at the top is the same.

Also the diagram view has same kind of inconvenience, when looking at the dialog with lot of messages.

 Having some keys to set the current dialog to be the first or last (for dialogs list view) and the current message in a dialog to be the first or the last (for diagram view) would make jumping straightforward.

Thanks!

**Comment by linuxmaniac** [comment]
:+1:

**Comment by Kaian** [comment]
Hey!

  Call flow already has keybindings for moving to the first (default Home) and last (default End) message in dialog. 
  Is that what you would need in the call list panel?

Thanks for the feedback!

**Comment by miconda** [comment]
Home and End are not on all keyboards (some laptops), but they have some corresponding combination of key (like FN+Arrow UP/Down/...). I tried all combinations I could and that usually work to jump at top/bottom, but no success. Maybe would be good to add some alternative (letter keys) to Home/End (other special keys).

**Comment by Kaian** [comment]
The letter values for those bindings are Ctrl+A and Ctrl+E (Not sure from where I've taken those  :sweat_smile: ).

They can be also be replaced in `sngreprc` using the `bind` option
```
bind home ^A
bind end ^E
```


https://github.com/irontec/sngrep/wiki/Configuration#keybindings

**Comment by miconda** [comment]
I tried with:

```
cat ~/.sngreprc

bind home A
bind end Z
```

But no success to get A and Z to jump to first or last message in a dialog inside the call flow view. I am on mac os x, if that matters.

**Comment by Kaian** [comment]
Sorry, I gave you wrong code for begin action. My bad. I've tried:

```
bind begin A
bind end Z
```
and it seems to work both in call list and call flow in the lastest master under Gentoo.

Umm... I'll try to get what values I get from the input function of ncurses for those keys on MacOSX.

**Comment by miconda** [comment]
CTRL+A and CTRL+E work on a linux box. I noted a typo in the wiki, CTRL+F is listed instead of CTRL+E for 'end', and it is also listed for npage.

**Comment by miconda** [comment]
Still not working with:

```
cat ~/.sngreprc

bind begin A
bind end Z
```

I expect to be a mac os x specific issue -- I will try to look at the code whenever I get the first chance.

**Comment by Kaian** [comment]
Wiki fixed! Thanks again!!

I'm going to test it right now under Yoshemite.

**Comment by Kaian** [comment]
I have tested it and it seems to work as expected in Yoshemite, both with default keybindings and custom bindings in sngreprc. Btw, the keyboards I've used are not Apple.

It's quite strange because the A/Z keybindings should be received and handled properly (most proably they work as expected when writing into any input field like save file name or filter...)

**Comment by miconda** [comment]
I am using a macbook pro laptop. Is any tool that can be used to get the input keys codes as ncurses receives?

**Comment by Kaian** [comment]
It can be tested easly in a couple of lines of code. See https://gist.github.com/Kaian/975832d133e179702060

```
~ $ ./ncurses_intest 
You pressed: 65 (A)
~ $ ./ncurses_intest 
You pressed: 97 (a)
~ $ ./ncurses_intest 
You pressed: 69 (E)
~ $ ./ncurses_intest  # (Ctrl + E)
You pressed: 5 ( )
~ $ ./ncurses_intest  # (Ctrl + A)
You pressed: 1 ( )
```

**Comment by Kaian** [comment]
If you have the time, you can also pull the latest master commit and try:

`sngrep --dump-config`

It will print the configured keybindings including custom system/user/etc ones. They should match the values given by ncurses_intest program. Action ids we're looking for area:

```
ActionID: 11	 Key: 262 	
ActionID: 11	 Key: 1 	
ActionID: 11	 Key: 65 	A
ActionID: 12	 Key: 360 	
ActionID: 12	 Key: 5 	
ActionID: 12	 Key: 90 	Z
```

This option may be helpful in the future if I add ActionName and the rest of configurable settings that appear in the wiki. Just another thing TODO!

Thanks for the testing!

**Comment by miconda** [comment]
ncurses_intest showed the same results as for you.

My macosx decided to freeze and reboot the laptop, after recover I did a cleanup to my sngrep branches, installed fresh and navigation works now. Maybe I had a conflict in key bindings with some other tools not started after reboot.

I close this one for now.
