### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by jungle-boogie** [irontec/sngrep#61]
Hello,

These warnings are generated:

    % make
    Making all in src
    make  all-am
      CC       capture.o
      CC       capture_ws.o
      CC       sip.o
    sip.c:333:33: warning: field precision should have type 'int', but argument has type 'long' [-Wformat]
            sprintf(reqresp, "%.*s", pmatch[1].rm_eo - pmatch[1].rm_so, payload + pmatch[1].rm_so);
                              ~~^~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     sip.c:341:33: warning: field precision should have type 'int', but argument has type 'long' [-Wformat]
            sprintf(reqresp, "%.*s", pmatch[2].rm_eo - pmatch[2].rm_so, payload + pmatch[2].rm_so);
                              ~~^~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    sip.c:368:26: warning: field precision should have type 'int', but argument has type 'long' [-Wformat]
        sprintf(cseq, "%.*s", pmatch[1].rm_eo - pmatch[1].rm_so, payload + pmatch[1].rm_so);
                       ~~^~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings generated.

My CC version:

     % cc --version
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: x86_64-unknown-freebsd10.2
    Thread model: posix

**Comment by Kaian** [comment]
Hi @jungle-boogie ! 

I also noticied those warnings while testing #60 under MacOSX. 

I'll try to properly cast regexp values to remove that warning. Integers should be enough for regular expressions since they're executed per SIP payload line, not the whole message.

Thanks for reporting!!!

**Comment by miconda** [comment]
Independently, I noticed the same warnings while compiling last version on mac os x and made a pull request -- it can be discarded if you plan another fix.

**Comment by Kaian** [comment]
The changes in the PR seems perfect to me. Thanks for the fix!
