### ISSUE TITLE
Call flow RTP arrow displayed in wrong direction

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#63]
issue for rtp path arrow
![issue](https://cloud.githubusercontent.com/assets/12387494/10367040/b5fd7392-6e00-11e5-8617-5fe2ee56a535.png)

**Comment by Kaian** [comment]
Hi @michael2009 

 The problem here is wrong direction for the RTP displayed arrow, so I will rewrite the issue title.

Thanks for the pcap file!! :)

**Comment by Kaian** [comment]
It was a bug while displaying the RTP arrow. The internal of the streams was correct.
It should be fixed in `master` last commit.

Thanks!
