### ISSUE TITLE
TLS_RSA_WITH_AES_256_GCM_SHA384

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#64]
issue for tls cap . i had sent mail

**Comment by Kaian** [comment]
Hi @michael2009 !

The cipher used in the TLS connection of the pcap is TLS_RSA_WITH_AES_256_GCM_SHA386.

Right now, sngrep only supports TLS_RSA_WITH_AES_128_CBC_SHA and TLS_RSA_WITH_AES_256_CBC_SHA but I think this cipher decrypt can be implemented.

I mark this as an enhancement.

Thanks for reporting!!

**Comment by kevinlong206** [comment]
Hi Kaian,

I am using FreePBX (Asterisk 11) .  I'd like to be able to view SIP traffic (TLS) from the Asterisk machine itself. I compiled with OpenSSL support, but I'm wondering if the TLS cipher is preventing sngrep from showing the TLS traffic. Only my UDP traffic is showing up, despite me having specified my private key file and no errors are shown.

Asterisk allows specify the tls cipher in the configuration. My "openssl ciphers" command shows the following list,  should I specifiy a particular one of these exact strings in my my Asterisk configuration so I may use sngrep on TLS ? 

ECDHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-SHA384
ECDHE-ECDSA-AES256-SHA384
ECDHE-RSA-AES256-SHA
ECDHE-ECDSA-AES256-SHA
DHE-DSS-AES256-GCM-SHA384
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES256-SHA256
DHE-DSS-AES256-SHA256
DHE-RSA-AES256-SHA
DHE-DSS-AES256-SHA
DHE-RSA-CAMELLIA256-SHA
DHE-DSS-CAMELLIA256-SHA
ECDH-RSA-AES256-GCM-SHA384
ECDH-ECDSA-AES256-GCM-SHA384
ECDH-RSA-AES256-SHA384
ECDH-ECDSA-AES256-SHA384
ECDH-RSA-AES256-SHA
ECDH-ECDSA-AES256-SHA
AES256-GCM-SHA384
AES256-SHA256
AES256-SHA
CAMELLIA256-SHA
PSK-AES256-CBC-SHA
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-SHA256
ECDHE-ECDSA-AES128-SHA256
ECDHE-RSA-AES128-SHA
ECDHE-ECDSA-AES128-SHA
DHE-DSS-AES128-GCM-SHA256
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES128-SHA256
DHE-DSS-AES128-SHA256
DHE-RSA-AES128-SHA
DHE-DSS-AES128-SHA
ECDHE-RSA-DES-CBC3-SHA
ECDHE-ECDSA-DES-CBC3-SHA
DHE-RSA-SEED-SHA
DHE-DSS-SEED-SHA
DHE-RSA-CAMELLIA128-SHA
DHE-DSS-CAMELLIA128-SHA
EDH-RSA-DES-CBC3-SHA
EDH-DSS-DES-CBC3-SHA
ECDH-RSA-AES128-GCM-SHA256
ECDH-ECDSA-AES128-GCM-SHA256
ECDH-RSA-AES128-SHA256
ECDH-ECDSA-AES128-SHA256
ECDH-RSA-AES128-SHA
ECDH-ECDSA-AES128-SHA
ECDH-RSA-DES-CBC3-SHA
ECDH-ECDSA-DES-CBC3-SHA
AES128-GCM-SHA256
AES128-SHA256
AES128-SHA
SEED-SHA
CAMELLIA128-SHA
DES-CBC3-SHA
IDEA-CBC-SHA
PSK-AES128-CBC-SHA
PSK-3DES-EDE-CBC-SHA
KRB5-IDEA-CBC-SHA
KRB5-DES-CBC3-SHA
KRB5-IDEA-CBC-MD5
KRB5-DES-CBC3-MD5
ECDHE-RSA-RC4-SHA
ECDHE-ECDSA-RC4-SHA
ECDH-RSA-RC4-SHA
ECDH-ECDSA-RC4-SHA
RC4-SHA
RC4-MD5
PSK-RC4-SHA
KRB5-RC4-SHA
KRB5-RC4-MD5

**Comment by Kaian** [comment]
Hi @kevinlong206 !

I reply to your email. It should work for the mentioned ciphers in the previous comment, but I've only tested it with a couple of Yealink terminals:

```
# openssl ciphers -V | grep 0x00,0x2F
          0x00,0x2F - AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
# openssl ciphers -V | grep 0x00,0x35
          0x00,0x35 - AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
```

Also, you must capture before the connection establishment (when the session key is negociated).
You can determine the used cipher in your connection using other tools like `ssldump` or `wireshark` (on ServerHello record).

**Comment by kevinlong206** [comment]
No luck so far getting the TLS packets to be seen by sngrep. 

My asterisk transport config:

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
local_net=10.50.55.0/24
external_media_address=x.x.x.x
external_signaling_address=x.x.x.x
cert_file=/etc/asterisk/keys/dev1.crt
priv_key_file=/etc/asterisk/keys/dev1.key
ca_list_file=/etc/asterisk/keys/ca.crt
cipher=AES256-SHA
method=tlsv1



I run:  sngrep -k /etc/asterisk/keys/dev1.key 


But nothing shows up. I disconnect and unregister my SIP phone clients and make a new registration and everything.

**Comment by Kaian** [comment]
Give it a try to ssldump. If that tool is able  to decryt the application_data I could debug what part is not working properly in sngrep.

Thanks!

**Comment by michael2009** [comment]
found TLS issue with AES256-SHA / AES128-SHA . Please check pcap file .

**Comment by michael2009** [comment]
Confirm TLS issue for Centos7/OpenSSL 1.0.1e-fips/Asterisk13/AES256-SHA / AES128-SHA 

can'nt show any flow .

**Comment by Kaian** [comment]
Yes. I can confirm this issue.

Your pcap file helped me to discover a couple of problems parsing TLS 1.1 and 1.2 connections.

We're still working on it. Once again your testing files are ultra helpful.

Thanks @michael2009

**Comment by Kaian** [comment]
I've created a new issue #104 to handle TLS 1.2 error and leave this issue for the possible Cipher enhancement, just not to mix topics :)

**Comment by Kaian** [comment]
Hi @kevinlong206 and @michael2009 

If you have time, please give it a try to the of last `master` commit **compiling with GNUTLS support** (I haven't changed anything in the OpenSSL decrypt code). I have tested with the capture files you've provided and seems to work ok.

Also, please leave your comments in #104 instead of this issue, so we can leave this as an enhacement and close the other issue.

Thanks for the testing!

**Comment by kevinlong206** [comment]
Working so far , thank you! Very cool. Will do some real world debugging soon and provide feedback if I have some , thanks again.

**Comment by michael2009** [comment]
Working now !!!

**Comment by Kaian** [comment]
Wow, that was impossible, I haven't changed nothing until today hehehe.

I have implemented this for gnutls SSL decoding mode, which should now be compatible with old CentOS and BSD systems. So we can decode [three ciphers](https://github.com/irontec/sngrep/blob/master/src/capture_gnutls.c#L42) now.

Sorry for taking a year to do this, we found we need it now :innocent:
