### ISSUE TITLE
Is it possible to install sngrep binary package in Rasberry PI?

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#65]
I tried to install sngrep in a Rasberry PI and It gave me the next error:

——————————————————————————————————————————————
W: Imposible obtener http://packages.irontec.com/debian/dists/wheezy/Release Unable to find expected entry ‘main/binary-armhf/Packages’ in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
—————————————————————————————————————————-———–-

I added the Wheezy repository because I think that It is the most similar to Raspbian linux and the repository key:

deb http://packages.irontec.com/debian wheezy main
wget http://packages.irontec.com/public.key -q -O - | apt-key add -

But when I run "apt-get update", It gives me the previous error.

Need I to compile it to hand or there is another way?

Thanks.

**Comment by Kaian** [comment]
I @ramses-0000!

The wiki section of debian packages says:
`Binaries are built only for amd64 and i386 architectures right now with all supported features enabled.`

For armhf, you must compile sngrep from sources :(

**Comment by Kaian** [comment]
You could also try the armhf package from sid, but I haven't tested it in wheezy.
I also don't recommend mixing debian releasing packages 0:)

https://packages.debian.org/sid/sngrep

**Comment by ramses-0000** [comment]
I go to compile it to hand.

Very thanks Kaian.
