### ISSUE TITLE
Cambiar color de fondo de sngrep y guardar gráfico del diálogo.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#69]
Kaian, buenos días.

¿Hay alguna forma de cambiar el color de fondo de "sngrep", por ejemplo, del negro al blanco y que se inviertan el color blanco de los caracteres, líneas, etc..., para que puedan ser visualizados en el fondo blanco?.

Es sólo una curiosidad, hay veces que para documentar...

Otra cosa que podría ser interesante es poder guardar en formato texto el gráfico del diálogo.

Saludos

**Comment by Kaian** [comment]
Buenas,

 Si usas una consola con fondo blanco puedes intentar jugar con la setting de `background`. No funciona idealmente (falta de testing) pero respeta los colores originales de la terminal.

`echo set background default >> $HOME/.sngreprc`

Sobre guardar en formato gráficas, podría ser una mejora interesante, pero ahora mismo sngrep no está muy preparado para hacer esa tarea. La lógica de salvar y visualización están completamente desacopladas.

Saludos!

**Comment by ramses-0000** [comment]
OK, probado y funciona, aunque creo que la mejor opción, hasta que puedas implementar lo de guardar los gráficos, sea dejar los colores tal y como están, usar el "Copia y Pega", y hacerle algunos arreglitos al gráfico.

El Wireshark te genera el gráfico, pero creo que bastante "descuajaringado", o por lo menos a mi me lo "descuajaringa".


Gracias
