### ISSUE TITLE
Filtrar diálogo de un host, tanto si aparece como Source o como Destination.

### ISSUE THREAD

**Issue by ramses-0000** [irontec/sngrep#70]
Kaian, buenos días,

¿Existe la posibilidad de filtrar los diálogos de un host, aparezca como Origen o Destino del diálogo?.

Es decir, si yo estoy el el Host A capturando con SNGREP y quiero capturar los diálogos entre el Host A y el Host B, que me capture tanto los mensajes que lleguen desde el Host B con destino al Host A, como los que genere el Host A con destino al Host B.

Si en filtros le pongo como como destino el Host B, no veo los diálogos que provienen del Host B, sólo los que genera el Host A con destino Host B, y viceversa.

Saludos

**Comment by Kaian** [comment]
Buenas @ramses-0000 !!

Prueba con:
 `sngrep host A` o `sngrep host B` 

_host host
True if either the IPv4/v6 source or destination of the packet is host._

**Comment by ramses-0000** [comment]
Ah, bien, pero desde línea de comando, no está la opción en los filtros (F7), ¿no?.


Saludos

**Comment by Kaian** [comment]
No, la pantalla de filtros aplica al primer paquete de cada dialogo y diferenciando src/dst.

Tambien puedes introducir la IP en la linea de busqueda (F3) o '/', y mostará las lineas que contentan esa IP

**Comment by ramses-0000** [comment]
Ah, bien, por lo que veo, la opción del F3 creo que es por la que estaba preguntando, es como si en la pantalla de Filtros (F7) hubieses puesto un campo "Host:".

Quizás esta opción del F3 sea mejor que la de "sngrep host x.x.x.x" ya que con F3 te capturaría todos los diálogos, y podrías ver algún cambio de IP, pero en esta última sólo los diálogos entre esos dos hosts...


Gracias

**Comment by Kaian** [comment]
En general, los *filtros de captura* (en linea de comandos) minimizan muchisimo el trabajo de parseo y almacenado de sngrep, por lo que son recomendables. En funcion de la carga del sistema (o del tamaño del pcap), es posible que sean preferibles a los *filtros de visualizacion*.

Hay que tener en cuenta que todo se guarda en memoria, por lo que sngrep puede llegar a consumir muchos recursos cuando gestiona mucha informacion.

Cualquier duda, tambien puedes consultarme en el canal #sngrep de irc.freenode.net

Un saludo!
