### ISSUE TITLE
You dont seem to have ipv6 support (no ip6.h found).

### ISSUE THREAD

**Issue by jungle-boogie** [irontec/sngrep#71]
% ./configure
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether make supports nested variables... (cached) yes
    checking for style of include used by make... GNU
    checking for gcc... no
    checking for cc... cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether cc accepts -g... yes
    checking for cc option to accept ISO C89... none needed
    checking whether cc understands -c and -o together... yes
    checking dependency style of cc... gcc3
    checking how to run the C preprocessor... cc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether cc accepts -g... (cached) yes
    checking for cc option to accept ISO C89... (cached) none needed
    checking whether cc understands -c and -o together... (cached) yes
    checking dependency style of cc... (cached) gcc3
    checking for g++... no
    checking for c++... c++
    checking whether we are using the GNU C++ compiler... yes
    checking whether c++ accepts -g... yes
    checking dependency style of c++... gcc3
    checking whether ln -s works... yes
    checking for egrep... (cached) /usr/bin/grep -E
    checking for pthread_create in -lpthread... yes
    checking for pcap_open_offline in -lpcap... yes
    checking pcap.h usability... yes
    checking pcap.h presence... yes
    checking for pcap.h... yes
    checking ncurses.h usability... yes
    checking ncurses.h presence... yes
    checking for ncurses.h... yes
    checking for initscr in -lncurses... yes
    checking for new_panel in -lpanel... yes
    checking for new_form in -lform... yes
    checking for new_item in -lmenu... yes
    checking netinet/ip6.h usability... no
    checking netinet/ip6.h presence... yes
    configure: WARNING: netinet/ip6.h: present but cannot be compiled
    configure: WARNING: netinet/ip6.h:     check for missing prerequisite headers?
    configure: WARNING: netinet/ip6.h: see the Autoconf documentation
    configure: WARNING: netinet/ip6.h:     section "Present But Cannot Be Compiled"
    configure: WARNING: netinet/ip6.h: proceeding with the compiler's result
    configure: WARNING:     ## -------------------------------- ##
    configure: WARNING:     ## Report this to kaian@irontec.com ##
    configure: WARNING:     ## -------------------------------- ##
    checking for netinet/ip6.h... no
    configure: error:  You dont seem to have ipv6 support (no ip6.h found).

Where would I have netinet/ip6.h?

**Comment by jungle-boogie** [comment]
FYI, freebsd puts ip6.h here:

    /usr/include/netinet/ip6.h
    /usr/include/netinet6/ip6.h

**Comment by jungle-boogie** [comment]
from config.log:

configure:6486: checking netinet/ip6.h usability
configure:6486: cc -c -g -O2  conftest.c >&5
In file included from conftest.c:65:
/usr/include/netinet/ip6.h:82:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
                        ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
/usr/include/netinet/ip6.h:83:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_dst;        /* destination address */
                        ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
2 errors generated.

**Comment by Kaian** [comment]
Hi @jungle-boogie 

Thanks for the report. I have enabled IPv6 by default in the last release as it seems available in most systems. I will fix the place it looks for the include files.

As a workaround, you can disable it with `./configure --disable-ipv6`

**Comment by Kaian** [comment]
Hi!

This should be fixed in master now. ceea6f23599ba55ec78eb5f79cf52a308566a39c

Also, I have changed my mind and disabled all settings by default  (as they were before) until more testing in different enviroments are done.

Please check again with `./configure --enable-ipv6` if you want IPv6 support.

**Comment by jungle-boogie** [comment]
Hi @Kaian,

Thanks for correcting so quickly. Disabling and enabling ipv6 with configure both work and I can make and make install without a problem.

Thanks!
