### ISSUE TITLE
Feature Request: Autoscroll the Flow Viewer

### ISSUE THREAD

**Issue by kismetgerald** [irontec/sngrep#72]
First of all thank you guys for a really great product.  I'm new to VOIP and Freeswitch and having a graphical interface that can allow me to do a SIP trace is very very helpful.

While using SNGREP, I realized that I keep scrolling down in order to see the latest traffic capture.  Perhaps having an option in the settings to enable auto-scrolling of the capture window in the Flow Viewer would be very handy for someone like me.

Thanks again.

**Comment by Kaian** [comment]
Hi @kismetgerald !

Glad to hear that it's useful!

I think you refer to Call List window (as far as i remember from our mails), but just to confirm. In Call List it will scroll to the last dialog, while in Flow viewer it will scroll to the last arrow (message).

Thanks for your feedback!!

**Comment by kismetgerald** [comment]
Hello Kaian,

Thanks for the quick response.  I'm referring to the initial window that comes up as soon as you launch sngrep.  The title says "sngrep - SIP messages flow viewer".

This is what I'm currently using as part of my test server monitoring and hope to use it in production when I get there.

**Comment by Kaian** [comment]
Okey! Yes, thats Call List.

For a reference of the names chosen for each window, take a look at [sngrep wiki](https://github.com/irontec/sngrep/wiki#interface). Sure not the best names but that way we can identify each window :)

Always beware that sngrep stores all its information in memory. In production environments I recomend using bpf filters and capture limit (both from the command line) to minimize the amount of memory used.

**Comment by kismetgerald** [comment]
Sure, I will check out the Wiki and familiarize myself with the window names.

Concerning using BPF filters, I'm not yet experienced but will learn quickly.  Although, i'd be interested in seeing an example of how you would use capture limit from the command line.  I see that I can pass the -L switch - but what value does that take?

**Comment by Kaian** [comment]
Hi @kismetgerald 

The command line argument for capture dialog limit is `-l` which defaults to 20000 dialogs.
When that limit has been reached the capture thread discards any new packet (even if it belongs to a previous call). 

This option exists to prevent an unattended sngrep to capture until no memory is available in the system (and nobody wants that!)

If you're only interested in SIP messages in a heavy load system, just try with
`sngrep -l 5000 port 5060`

The first value (-l 5000)  is the max number of rows of Call List, the second (port 5060) is a bpf filter (tcpdump, ngrep, sipgrep and more tools based on libpcap use them to filter captured packages).

If you want to configure the limit for all your sngrep runs without using command line, add this your $HOME/.sngreprc file:
`set capture.limit 5000`

You can see a list of configurable settings [here](https://github.com/irontec/sngrep/wiki/Configuration)
You can also dump your active settings using `sngrep --dump-config`

**Comment by kismetgerald** [comment]
Aaah, I get it now.  I've been doing this "sngrep port 5060".  So all along I've been using a BPF filter without knowing it.  Ha, I learned something new.....thanks.

But seriously though, it would be really helpful if the window would autoscroll to show the latest packets.  SNGREP makes a really handy live monitoring tool.  I'm loving it thus far.

Right now I'm trying to use it to send capture to a Homer installation, but that's not working too well.  I did this - "sngrep -H udp:x.x.x.x:9060 port 5060" - but nothing is showing up yet on Homer (where I have sngrep running and listening for packets on port 9060.  I know this has nothing to do with this feature request, but hey, since I got you here I might as well try eh?....lol

**Comment by Kaian** [comment]
Heh, now that you know how to change and dump configure settings, take a look at `eep.send.pass` setting. Maybe the default password doesn't match your Homer server.

I will recommend to setup a captagent daemon, and after testing it works, "borrow" its settings! :D

**Comment by kismetgerald** [comment]
lol..........I'm having the trouble with the captagent daemon that's why I'm trying it this way to see if any packets are being sent at all.  The captagent daemon is running on my Freeswitch server, but not sending anything to Homer.

**Comment by Kaian** [comment]
As commit description says:

- Add keybining (default 'A' to toggle autoscroll on/off)
- Add setting (cl.autoscroll) to enable/disable autoscroll on startup
- Any direction keybinding pressed will disable autoscroll

You can toggle autoscroll by pressing `A`. Autoscrolling will be automatically stopped if you press any movement action. Also, a `A` will be displayed above scrollbar to indicate if it's autoscrolling or not.

You can start sngrep autoscrolling by adding `set cl.autoscroll on` in your sngreprc file :)

**Comment by kismetgerald** [comment]
Wow, thank you very much for doing this.  Hope it wasn't too difficult a task?

**Comment by Kaian** [comment]
Not difficult at all !

Most of the code is ready for adding keybindings and settings without too much effort.
I think It won't be something that we will use too much, so If you feel it could be improved or is not what you need drop me a line at irc anytime ;)
