### ISSUE TITLE
--output flag not working

### ISSUE THREAD

**Issue by rizwankh** [irontec/sngrep#73]
I have tested this many times:
[root@kz1 ~]# sngrep -d eth2 -O /tmp/tes.pcap
Couldn't open output dump file /tmp/tes.pcap:
[root@kz1 ~]#

But this never works neither with the latest github master, nor the installed version for centos.

**Comment by Kaian** [comment]
Hi @rizwankh 

Yep, confirmed. We use to save dialogs from save window, so -O option is not used too often 

Thanks for reporting!!.
