### ISSUE TITLE
Feature Request: SNGREP hepv2 support

### ISSUE THREAD

**Issue by ruilibras** [irontec/sngrep#74]
Thanks for a great product and the help given in the irc channel.
I want to ask, if possible, support for HEPv2. It would help me a lot in implementations which use Kamailio with siptrace module (modparam ("siptrace", "hep_mode_on", 2)), but unfortunately i can not capture communications by HEP version mismatch.

Thanks for the help and time available.
Liberal

**Comment by Kaian** [comment]
Hi @ruilibras !

I will see the differences between HEPv2 and HEPv3 and try to implement it.

This change must be properly tested and right now I have no too much spare time, so It wont be done asap, but I'll keep in mind :)

Thanks for reporting!
