### ISSUE TITLE
Error message which reporting success

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#76]
Getting this with *sngrep - 1.1.0* with IPv6 support.

```
sudo sngrep 
Error getting network address: Success
```

**Comment by Kaian** [comment]
What an awful error: Success :sweat_smile: 

By default sngrep captures in interface "any", an alias for all interfaces. Depending on what interfaces do you have, that can cause some errors. You can select capture interface with -d argument, p.e

`sudo sngrep -d eth0`

And you can make that setting persistent adding to your _sngreprc_ file
`set capture.device eth0`

**Comment by dunst0** [comment]
Yep :joy:

With device specified I still getting this error:
```
sudo sngrep -d eth0
Error getting network address: Success
```

**Comment by Kaian** [comment]
Could you paste your `iptables -a` output?
That interface only has ipv6 address?

**Comment by dunst0** [comment]
`iptables -a`? on debian jessie there is no a switch
that interface is has an ipv4 address and a link-local ipv6 address

**Comment by Kaian** [comment]
Ups, I mean `ifconfig -a`. My bad.

Umm that's strange.

**Comment by dunst0** [comment]
```
root@host:~# ifconfig -a
eth0      Link encap:Ethernet  Hardware Adresse xx:xx:xx:dc:b3:31  
          inet Adresse:x.x.x.x  Bcast:x.x.x.x  Maske:x.x.x.x
          inet6-Adresse: fe80::20c:29ff:fedc:b331/64 Gültigkeitsbereich:Verbindung
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metrik:1
          RX packets:10570 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2908 errors:0 dropped:0 overruns:0 carrier:0
          Kollisionen:0 Sendewarteschlangenlänge:1000 
          RX bytes:7008765 (6.6 MiB)  TX bytes:427805 (417.7 KiB)

lo        Link encap:Lokale Schleife  
          inet Adresse:127.0.0.1  Maske:255.0.0.0
          inet6-Adresse: ::1/128 Gültigkeitsbereich:Maschine
          UP LOOPBACK RUNNING  MTU:65536  Metrik:1
          RX packets:2894 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2894 errors:0 dropped:0 overruns:0 carrier:0
          Kollisionen:0 Sendewarteschlangenlänge:0 
          RX bytes:334544 (326.7 KiB)  TX bytes:334544 (326.7 KiB)
```

And it is happend at my fedora laptop as well.

**Comment by Kaian** [comment]
Hi @dunst0 

The code where that message is given seems realted with EEP/HEP process.

Can you provide the output of `sudo sngrep --dump-config | grep eep` 

Thanks!

**Comment by Kaian** [comment]
Also, according to the man page, the message I'm printting is not correct, because the function I'm using for parsing the EEP server address (inet_aton) doesn't set the reason code for failure (errno), so at least I will change that :)

```
inet_aton() returns 1 if the supplied string was successfully interpreted, 
or 0 if the string is invalid (errno is not set on error)
```

**Comment by dunst0** [comment]
```
SettingId: 34	 SettingName: eep.send             Value: off
SettingId: 35	 SettingName: eep.send.address     Value: 10.1.1.1
SettingId: 36	 SettingName: eep.send.port        Value: 9060
SettingId: 37	 SettingName: eep.send.pass        Value: myHep
SettingId: 38	 SettingName: eep.listen           Value: on
SettingId: 39	 SettingName: eep.listen.address   Value: localhost
SettingId: 40	 SettingName: eep.listen.port      Value: 9000
SettingId: 41	 SettingName: eep.listen.pass      Value: myHep
```

**Comment by Kaian** [comment]
Ahhh, EEP process It does not resolve address (at least not yet! 0:) )

Change from localhost to 127.0.0.1

**Comment by dunst0** [comment]
ok, thankss a lot.

BTW thank you for creating and maintaining this great tool. Helps me a lot at work.

**Comment by Kaian** [comment]
Nice!

I'll try to implement EEP address resolution for the next release.
Any other questions, dont hesitate to join the irc channel ;)
