### ISSUE TITLE
Coredump on random traffic

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#83]
Compiled on RHEL6.1 with libncurses included but it will crash after using it for while also lots of garbage left when you navigate screen. So my guess some early libncurses libs have issue?

**Comment by Kaian** [comment]
Hi @nshopik 

Umm, crashes happens here and there sometimes. To check if it is caused while receiving some non-SIP packets, you can test to capture only SIP and check if it crashes after a while. Something like 

    sngrep -d any port 5060 

Are you using 1.2.0 version? It's compiled from sources or rpm package?
Can you provide a screenshot (maybe others have similar issues).

Thanks a lot for your report!

**Comment by nshopik** [comment]
I've compiled from current master. Yes it appears that filter indeed help no crashes, so you probably right about crash on some random packets.

Is there anyway I can share screenshot with you privately?

**Comment by Kaian** [comment]
Yep, send it to kaian@irontec.com ;))

**Comment by Kaian** [comment]
Is there a way to know if the problem is related with sngrep itself?
Does the crash still happen?

Thanks for the feedback!

**Comment by nshopik** [comment]
So far i didn't seen any more crashes but I'm not using it that often. It probably not related to RHEL though, but for some traffic pattern

**Comment by Kaian** [comment]
A lot of changes have been done in capture thread so maybe the cause of this has been fixed and new crashes appear :sweat_smile: 

Feel free to reopen if you find another crash and can provide a backtrace or pcap for debugging it.

Thanks for reporting!

**Comment by nshopik** [comment]
@Kaian Wow, you been busy, lots of commits, it's been while since I've tried more recent build! Thanks

**Comment by Kaian** [comment]
You welcome!

I had some spare time so I've done a couple of commits to replace old crashes by new ones :laughing: 
If there're now big bugs in some days, I will close 1.3.0 release and make packages.
