### ISSUE TITLE
Multiple device selection on none Linux systems.

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#93]
I would like to suggest a feature request. Like you said in an other issue the any device is part of libpcap but only on Linux systems, so I would be great if it would be possible to specify more devices on startup to capture from.

**Comment by Kaian** [comment]
Hi @dunst0 

As far as I know, there is no easy way to listen on multiples interfaces with libpcap.
I think most of the network sniffers based on libpcap doesn't allow multiples interfaces (tcpdump, ngrep, and so) and I amnot totally sure if it is Thread-Safe (as we should launch a thread for each capturing interface). Using multiple child process won't work with sngrep design.

Not an elegant workaround, but If you have the need to capture in multiples interfaces, you can use hep/eep to run two different sngrep (one without showing interface) and send captured data from one sngrep to another.

```
sngrep -Hudp:127.0.0.1:9999 -d eth0 -Nq
sngrep -Ludp:127.0.0.1:9999 -d eth1
```

If you find a way to do this or other tool implementing multiple interface capture with libpcap, don't hesitate to comment it :)

**Comment by dunst0** [comment]
I found some information regarding pcap and multi device caputuring.

Maybe it helps:
http://seclists.org/tcpdump/2012/q2/18

**Comment by Kaian** [comment]
Hii,

After a year... I have created a branch called `multi_device` that implements support for multiple `-d` command line options so multiple capture devices can be now specified.

This requires a lot of testing, just to be sure that all shared structures are properly locked and no memory is now accessed/free'd at the same time from multiple capture threads.

I think someone in the IRC was also interested in this feature, so all the testing is appreciated.

Best regards!

**Comment by Kaian** [comment]
I will merge this into `master` and wait for a bit of testing before releasing :)

**Comment by Kaian** [comment]
This should be supported in 1.4.3

As always, feel free to reopen if it doesn't work as expected and will try to fix it for the next release!

**Comment by dunst0** [comment]
Hi @Kaian I haven't checked for some time the messages in github, so I missed some of your messages. Great to hear that there is now multiple devices. Many thanks to you for implementing that feature and thank you for developing and maintaining that great tool.

**Comment by dunst0** [comment]
Just to let you know, seem that with multi it seems that on FreeBSD I receive ever package double or they are displayed double.

**Comment by Kaian** [comment]
You mean using a single interface in the command line? :thinking:

**Comment by dunst0** [comment]
It seems that with 1.4.3 every package has a retransmission, maybe not a problem from multi interface.

```
17:45:16.353595   │ ─────── INVITE (SDP) ─────> │
17:45:16.353595   │ ─────── INVITE (SDP) ───>>> │
17:45:16.355355   │ <─────── 100 Trying ─────── │
17:45:16.355355   │ <<<───── 100 Trying ─────── │
17:45:16.932852   │ <─────── 180 Ringing ────── │
17:45:16.932852   │ <<<───── 180 Ringing ────── │
17:45:44.644340   │ ────────── CANCEL ────────> │
17:45:44.644340   │ ────────── CANCEL ──────>>> │
17:45:44.645274   │ <────── 200 canceling ───── │
17:45:44.645274   │ <<<──── 200 canceling ───── │
17:45:44.882831   │ <──── 487 Request Termi ─── │
17:45:44.882831   │ <<<── 487 Request Termi ─── │
17:45:44.883180   │ ──────────── ACK ─────────> │
17:45:44.883180   │ ──────────── ACK ───────>>> │
```

**Comment by dunst0** [comment]
it doesn't matter if do `sngrep -d em0` or `sngrep -d em0 -d lo0`

**Comment by Kaian** [comment]
Does this happen when you capture a pcap file with tcpdump or ngrep and open it in sngrep?

**Comment by dunst0** [comment]
Yes even when I capture a file with tcpdump and just open it with sngrep

**Comment by Kaian** [comment]
Then the final test will be checking if the pcap file contains duplicate packets inside. If so, then the problem must be in the interface or libpcap (as all that capture tools use the same library to capture). If packets only appear once in the file and sngrep display them twice, then I must dig a bit more :thinking: 

We've using sngrep 1.4.3 since May, but only in debian based systems.. :S

**Comment by dunst0** [comment]
Wireshark doesn't show up resends in the call flows. :flushed:

**Comment by dunst0** [comment]
![bildschirmfoto 2017-09-07 um 18 21 35](https://user-images.githubusercontent.com/104505/30173874-6fc2de28-93f9-11e7-8fb7-36f10e0e1926.png)

**Comment by Kaian** [comment]
Hmmm.. could you send me a sample pcap to check its contents? 

I don't think wireshark has some duplicated packets removal logic, but I don't know tbh. It's using the same libpcap version that the machine capturing? You can also check if content is duplicated in the capturing maching by running `tcpdump -r your.pcap -A` and check if packets seems duplicated.

Thanks for the testing!

**Comment by dunst0** [comment]
For that I have to create a filter and the problem is the pcap may contains telephone numbers from customers if I doesn't filter it correct, that will be work for tomorrow. I will try to make a pcap. Btw with tcpdump the 180 Ringing isn't displayed multiple times.

**Comment by Kaian** [comment]
If you're compiling from sources, you also have a test pcap in _tests/aaa.pcap_ to give it a try :smile:

**Comment by dunst0** [comment]
With `tests/aaa.pcap` the packets are show double as well 😢

**Comment by Kaian** [comment]
Could you give it a try to latest commits to check if somehow the error still persist? If that's the case then I should not release 1.4.4 :sweat_smile: 

Thanks @dunst0 !

**Comment by dunst0** [comment]
I can't :

```
# make  install
Making install in src
  CC       sngrep-capture.o
In file included from capture.c:37:
./capture.h:72:10: fatal error: 'pcap/sll.h' file not found
#include <pcap/sll.h>
         ^
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /usr/local/src/sngrep/src
*** Error code 1

Stop.
make: stopped in /usr/local/src/sngrep
```

**Comment by Kaian** [comment]
That's #202 , give it a try to latest commit :)

**Comment by dunst0** [comment]
Oh sorry :relaxed:

But with latest version I still see double packets.

```
          192.168.1.2:5060             212.242.33.35:5060
        ──────────┬─────────          ──────────┬─────────
11:56:06.443914   │ ─────── INVITE (SDP) ─────> │
11:56:06.443914   │ ─────── INVITE (SDP) ───>>> │
11:56:06.601590   │ <──── 407 authenticatio ─── │
11:56:06.601590   │ <<<── 407 authenticatio ─── │
11:56:06.606422   │ ──────────── ACK ─────────> │
11:56:06.606422   │ ──────────── ACK ───────>>> │
11:56:23.863488   │ ─────── INVITE (SDP) ─────> │
11:56:23.863488   │ ─────── INVITE (SDP) ───>>> │
```

**Comment by Kaian** [comment]
I've tested the aaa.pcap in a docker container with CentOS 5.11 (where I've tested the #202 fix) and seems ok to me :S

**Comment by dunst0** [comment]
It seem totally strange to me I started the sngrep and this capture now has no duplicates

**Comment by dunst0** [comment]
It seems to be fine to me right now, :flushed: I can't tell why the different behavior was happening maybe a layer 8 error

**Comment by dunst0** [comment]
@Kaian Thank you very much, for the help.
