### ISSUE TITLE
Ability to set unlmited when using --no-interface (homer send mode)

### ISSUE THREAD

**Issue by jmordica** [irontec/sngrep#94]
We use sngrep for live call tracking. Great tool!

We also use it for sending INVITE's only to Homer using option `-c`

I'd like to be able to specific a unlimited number of packets to be captured since we are just sending packets (and not loading them into memory) from what I can tell.

Thanks!

**Comment by Kaian** [comment]
Hi @jmordica !

Sadly, the capture.storage _none_ still stores basic dialog and message information (call-ids, addresses, message types, from and to, etc). What is not stored in memory is the binary content of the captured packets (untouched, with all IP, TCP, UDP headers and so), that is used to save the dialogs into new pcap files. That means it will still increase the allocated memory over time.

The dialog limit exists for multiple reasons. One is to have a small control over unattended sngreps (they tend to eat memory after hours or days...), and it's also used in a hash table size, to index every dialog by call-id (which improves a lot finding a dialog when a new message is captured).

sngrep is not designed to be run during long times (like tcpdump, captagent or other capture tools). Its focused on helping to understand the protocol and debug when there is too much traffic. If you need to send only INVITES, I highly recommend you to do it with an offline pcap, captured with other tool that doesn't leak while running.

Anyway, I will try to improve memory usage to minize that _must have_ dialog information in future versions.

Best regards!

**Comment by Kaian** [comment]
Hi @jmordica 

After thinking about this issue, I have come with a possible solution (I should see how to implement it tho...) that will work with the call-id hash table I mentioned in the previous note.

I could improve the setting `capture.storage none` to only store in memory the call information (basically the call-id and a couple more data) and discard packet binary and message information (after sending it to homer or saving into pcap, depending on sngrep arguments). This should reduce A LOT the memory usage and, after all, that information is not required when no interface is displayed.

To keep the limit and not leak memory over time, I could implement a *capture rotation* setting. That will mean that when the capture.limit has been reached, the first dialog will be removed from memory. This way the memory used by sngrep running as an agent will be configrable (more or less) by the capture.limit setting.

The issue with this change will be that if a response from a dialog that has been removed is captured, it won't be handled, but that quite unlikely  (unless thousands of dialogs are captured every minute.) and could be avoided increasing the limit of dialogs stored in memory.

**Comment by Kaian** [comment]
This requires more testing, but a basic approach of capture rotation has been implemented in the commit above. It basically removes the first capture dialog when capture limit is reached.

`sngrep -l 200 -R port 5060` will keep 200 dialogs in memory and start rotating  the first dialog when a new one appears.

I will check that memory does not increase over time after a couple of days :)

**Comment by Kaian** [comment]
This is now available in sngrep 1.4.0.

I'm still recomend an expert tool like captagent for this task. sngrep is not tested or designed for long runs and memory leaks may still occur 0:-)

Thanks for the request!
