### ISSUE TITLE
No packets captured with device "any" on CentOS - version 1.2.0 - CentOS 7

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#95]
Can't use device any on CentOS because no packets will be captured. But it works when I select the ethernet device.

**Comment by Kaian** [comment]
Hi @dunst0 

Could this be related with #87 ?
If you can, test with a compiled sngrep from `master` to check it's already fixed.

Thanks!

**Comment by dunst0** [comment]
hey @Kaian,

I am unable to build latest master :weary:
```
checking for pthread_create in -lpthread... yes
checking for pcap_open_offline in -lpcap... no
configure: error:  You need to have libpcap installed to compile sngrep.
```
But libpcap is installed `libpcap-1.5.3-8.el7.x86_64`

**Comment by Kaian** [comment]
You need some development packages installed.
https://github.com/irontec/sngrep/wiki/Building#centosfedora

The minimum requirements are `ncurses-devel libpcap-devel` and the common compiling tools (`make gcc autoconf automake`..)

Also, you dont have to do `make install` if you don't want. After just `make` the compiled binary will be in _src_ dir in case you don't want to spread compiled stuff in your system.

**Comment by dunst0** [comment]
Yes sorry my fault. Not my day, I will try it.

**Comment by Kaian** [comment]
No problem, thanks for checking! :)

**Comment by dunst0** [comment]
Yep it seems to work :tada:

**Comment by dunst0** [comment]
Thank you for your great work, sngrep is helping me a lot.

**Comment by Kaian** [comment]
Nice! Glad to hear that :)

Closing this as duplicate then. Thanks for reporting!
